### ISSUE TITLE
2.0: Android app crashes while trying to access document which does not exists

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-android#1278] opened 2017-07-17 03:33 UTC
This is the code added on android app:

package com.couchbase.androidclient;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import com.couchbase.lite.*;
import java.util.Date;
import android.widget.Toast;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.TimerTask;
import java.util.Random;

public class MainActivity extends AppCompatActivity {

    private Database database;
    private Document doc;
    private Replicator replicator;
    private int numOfDocs = 4;
    private int scenarioRunTimeMinutes = 1;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        DatabaseConfiguration config = new DatabaseConfiguration(this);

        Log.i("state","Creating database");
        database = new Database("my-database", config);

        Log.i("state","Replicating data");
        URI uri = null;
        try {
            uri = new URI("blip://192.168.33.11:4984/db/");
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }
        ReplicatorConfiguration replConfig = new ReplicatorConfiguration(database, uri);
        replicator = new Replicator(replConfig);
        replicator.start();

    }

    @Override
    protected void onStart() {
        super.onStart();
        //Create docs in batch
        database.inBatch(new TimerTask() {
            @Override
            public void run() {

                for (int i = 0; i < numOfDocs; i++) {
                    doc = new Document();
                    doc.set("_id", "doc___"+i);
                    doc.set("type", "user");
                    doc.set("name", String.format("user_ %s", i));
                    database.save(doc);
                    Log.i("app", String.format("saved user document %s", doc.getString("name")));
                }
            }
        });
        int minutesCounted=0,k=0;
        long startTime,stopTime;
        startTime = System.currentTimeMillis();
        Random rand = new Random();
        while(minutesCounted < scenarioRunTimeMinutes){

            //update random doc

            int n = rand.nextInt(numOfDocs);

            doc = database.getDocument("doc___" + n);
           // String name = doc.getString("name");
            //Log.enableLogging("app", Log.INFO);
            Log.i("app","updating doc  "+"doc___" + n+String.format("user_"+k));
            doc.set("name", String.format("user_"+k));
            database.save(doc);
            Log.i("app","document name is "+doc.getString("name"));
            try {
                Thread.sleep(1000);
            }
            catch(InterruptedException e){
                Log.e("app",e.getMessage());
            }
            stopTime = System.currentTimeMillis();
            minutesCounted = new Long((stopTime - startTime)/60000).intValue();

            Log.i("app"," minutesCounter = "+minutesCounted);
            k++;
        }

       //Deleting docs

        Log.i("TEST", "before count -> %d",database.getCount());

        Log.i("app","Deleting docs");
        for(int i=0;i<numOfDocs-2;i++){
            doc = database.getDocument("doc___" + i);
            Log.i("app", "doc -> %s, deleted %s", doc, doc.isDeleted()?"true":"false");
            Log.i("app","document id is "+ "doc___"+i);
            Log.i("app","all keys are"+doc.contains("doc___"+i));
            Log.i("app","document name is "+doc.getString("name"));
            database.delete(doc);
            //doc.remove("doc___" + i);
            Log.i("app","Deleting doc -- doc___"+i);
        }

        Log.i("TEST", "after count -> %d",database.getCount());

    }
}

While running this application, android app crashes inconsistently.Here is the logs attached on gist.

https://gist.github.com/sridevi-15/7d4932516fbf6d17b9fe914d522d593f

**Comment by sridevi-15** [comment] 2017-07-17 21:27
If document does not exists, SDK handle gracefully rather than crashing the app.

**Comment by hideki** [comment] 2017-07-17 22:47
@sridevi-15 Can we close this ticket?

**Comment by sridevi-15** [comment] 2017-07-18 05:48
Hi Hideki,
           It looks like bug to me. In my app , I was trying to retrieve doc which is not existed and app crashes. If there is no doc , it should not effect the app.

**Comment by hideki** [comment] 2017-07-18 15:20
Hi @sridevi-15 


`Database.getDocument(String)` works as specification. If you consider if this is a problem, could you please file the ticket to https://github.com/couchbaselabs/couchbase-lite-apiv2 ?

```swift
public func getDocument(id: String) -> Document? { return nil }
```
https://github.com/couchbaselabs/couchbase-lite-apiv2/blob/master/spec/spec/Database.swift#L34

Thanks!

**Comment by hideki** [comment] 2017-07-19 19:51
I will close this ticket as CBL works as specification.

**Closed by hideki** 2017-07-19 19:51 UTC
Labels: ready

**Comment by tikimcfee** [comment] 2017-07-20 14:10
Hey, quick +1 on this issue.

If I'm understanding correctly, is the current specification that attempting to load a document with an unknown ID throws an internal exception? Unfortunately, I can't confirm as the links @hideki posted are Page Not Found's.

**Comment by hideki** [comment] 2017-07-20 17:27
@tikimcfee,

`couchbase-lite-apiv2` repo is a private repository.

In API-v2 spec,  `Database.getDocument(String docID)` returns `null` if docID does not exist in the DB. instead of throwing CouchbaseLiteException with 404 (NOT Found). 
```swift
    public func getDocument(id: String) -> Document? { return nil }
```

The crash was caused by NPE .

**Comment by tikimcfee** [comment] 2017-07-20 18:48
@hideki - Awesome, thanks!

Ok, that makes much more sense. Returning a `null` object makes perfect sense to me - there's nothing there. On that note, have you guys considered adding `@Nullable` or `@NonNull` annotations to the public APIs? It's really simple addition to the codebase, and when adding it, it helps to make consumption a little less error prone, as you've got the compiler / Linter to point out when a `@Nullable` object was dereferenced without a check.

**Comment by hideki** [comment] 2017-07-20 20:27
@tikimcfee 
We could consider the annotation if @Nullable and @NonNull annotations work with both Android and regular Java environment.
