### ISSUE TITLE
Storage Issue(Duplicate documents are storing with same ids)

### ISSUE THREAD

**Issue by prasannakumark** [couchbase/couchbase-lite-android#791] opened 2016-02-23 08:54 UTC
Hi All,

Seems to be there is a issue in CBL(Version 1.2.0).
Let me explain with an example !!!

![android cbl database storage issue version 1 2 1](https://cloud.githubusercontent.com/assets/8381323/13248402/1326fe76-da44-11e5-87b8-a1e8c42d78fd.png)

Even the documents are **not pushing to server after** create/edit the documents with an updates.

Please let me know if need any clarification or any help which i can help over here.

**Comment by hideki** [comment] 2016-02-23 18:24
Hi @prasannakumark,

Document (Document ID) is unique per database. However each document has revision history. I guess you are confused by document and revision relation. I recommend to read following page.
http://developer.couchbase.com/documentation/mobile/1.1.0/develop/guides/couchbase-lite/native-api/document/index.html
http://developer.couchbase.com/documentation/mobile/1.1.0/develop/guides/couchbase-lite/native-api/revision/index.html

Hope this helps.

**Comment by prasannakumark** [comment] 2016-02-24 05:31
Hi @hideki hideki,

Thanks for your quick response, I know that Document (Document ID) is unique per database, but i am querying for get the results, but results are giving duplicate documents per each create/edit(It was not working fine in CBL version 1.1.0). And even create/editing document information not pushing to server for monitoring the revision information in server(because it is very default to monitor the revision information in local databases/monitor the logs).

**Comment by hideki** [comment] 2016-02-24 05:53
Hi @prasannakumark,
Thank you for your reply. Could you please provide sample code to reproduce this issue? It helps us a lot.
Thanks!
Hideki

**Comment by prasannakumark** [comment] 2016-02-26 07:19
Hi **@hideki hideki,**

Sure, What i observed is not related to storage issue. I think it is something related to indexing issue.

**Here is my sample code:**
https://friendpaste.com/6ICGlaLJfyKRWxd0mdXMn5

I have filtering concept in my project like(created,started,completed)
Let me explain with an example:

Let says i have document with "created" status, i updated that document has a started status.

Now, i am going to filter created status documents but still it is showing edited document also in created status filter(Note : that content is showing started as per previous update).
I spent lot of time but i could not able to find what is the exact problem.

Note: if i change my view version(1.6 to 1.7 some thing like this) than it is giving accurate results. This all features are working well in 1.1 version.

Between, changes are not pushing to server immediately, some time it is not all working.

Why i am so interested in 1.2.0 is only reason is postFilter working very well and so faster like performance wish.

Please let me know if you need any information or clarifications!!

Thanks!
Prasanna Kumar

**Comment by hideki** [comment] 2016-02-26 20:47
Hi @prasannakumark,

Thank you for detailed information.

I need to clarify the problem. Please confirm followings

Steps to reproduce the issue
1. Create View based on status.
1. Create new document with `CREATED` status.
1. Query result is one result which document status is `CREATED`
1. Update document with `STARTED` status.
1. Query result is one result which document status is `STARTED` <-- Expected
1. Query result has two results. One result is with document which status is `CREATED`, another result is with document which status is `STARTED` <-- ACTUAL

Problem: Non-current revision (above case revision with`CREATED` status) is still in index. So query returns non-current revision?

**Comment by prasannakumark** [comment] 2016-02-28 03:55
Hi @hideki hideki,

Sure, i will reproduce the issue according to your steps on Monday, mean while this what i am referring,

https://github.com/couchbase/couchbase-lite-android/issues/795.

I though that it is storage issue but not storage issue,surly it is related to "Query not filtering view properly". I will give more details on Monday 

Thanks!
Prasanna Kumar

**Comment by hideki** [comment] 2016-03-07 20:46
Hi @prasannakumark,

Is this duplicated issue with #795? If so, I will close this ticket, and we will keep tracking issue with #795. 

Thanks!

**Comment by prasannakumark** [comment] 2016-03-09 06:58
Hi @hideki hideki,

Yes, this is duplicated issue.

Thanks!

**Comment by hideki** [comment] 2016-03-09 17:17
We will track this with #795.  So I will close this ticket.

**Closed by hideki** 2016-03-09 17:17 UTC
Labels: question, ready, verify

**Comment by hideki** [comment] 2016-04-19 00:40
Hi @prasannakumark,

I recently fixed the issue: https://github.com/couchbase/couchbase-lite-java-core/issues/1098.  In case multiple views exist sometimes old index data with old revision is not deleted. And as result, the query returns out-dated record. Do you think if the issues are same?

Thanks,
Hideki
