### ISSUE TITLE
2.0: Exception raised by Replicator Sync Gateway stopped 

### ISSUE THREAD

**Issue by rajagp** [couchbase/couchbase-lite-android#1471] opened 2017-12-11 23:15 UTC
**Version** : DB20

**Issue**: 

Exception raised when you stop the Sync Gateway . Issue occurs when you register a listener with the replicator

Also reported in [Forums ](https://forums.couchbase.com/t/how-to-stop-continuous-replication-cbl-2-0/15117/5)

Reproducible with any app including Travel Sample App. 

**Logs**
```
12-11 17:53:53.170 21019-21019/com.couchbase.travelsample I/LiteCore [BLIP]: {3} Opening connection...
12-11 17:53:53.170 21019-21019/com.couchbase.travelsample I/LiteCoreJNI: [NATIVE] C4Replicator.create() repl -> 0x0xa5ed7780
12-11 17:53:53.170 21019-21019/com.couchbase.travelsample I/LiteCoreJNI: [NATIVE] C4Replicator.getStatus() repl -> 0xa5ed7780
12-11 17:53:53.170 21019-21069/com.couchbase.travelsample I/LiteCore [Actor]: BLIP[->blip:10.0.2.2:4984/travel-sample/_blipsync] performNextMessage
12-11 17:53:53.170 21019-21069/com.couchbase.travelsample I/LiteCore [Actor]: Repl->blip:10.0.2.2:4984/travel-sample/_blipsync performNextMessage
12-11 17:53:53.170 21019-21019/com.couchbase.travelsample E/Sync: Replicator[<*> blip://10.0.2.2:4984/travel-sample] is connecting, progress 0/0, error: null
12-11 17:53:53.170 21019-21019/com.couchbase.travelsample E/Sync: statusChanged() c4Status -> C4ReplicatorStatus{activityLevel=2, progressUnitsCompleted=0, progressUnitsTotal=0, progressDocumentCount=0, errorDomain=0, errorCode=0, errorInternalInfo=0}
12-11 17:53:53.170 21019-21069/com.couchbase.travelsample E/C4Socket: C4Socket.callback.open() socket -> 0xacfda3c8, scheme -> blip, hostname -> 10.0.2.2, port -> 4984, path -> /travel-sample/_blipsync
12-11 17:53:53.170 21019-21019/com.couchbase.travelsample E/Sync: Replicator[<*> blip://10.0.2.2:4984/travel-sample] is connecting, progress 0/0, error: null
12-11 17:53:53.170 21019-21069/com.couchbase.travelsample E/C4Socket: optionsFleece: not null
12-11 17:53:53.171 21019-21069/com.couchbase.travelsample E/C4Socket: options = {auth={username=demo, type=Basic, password=password}, headers={User-Agent=CouchbaseLite/2.0.0-186 (Java; Android 7.1.1; Android SDK built for x86) Build/0 Commit/5ccb746}}
12-11 17:53:53.172 21019-21069/com.couchbase.travelsample I/LiteCore [Actor]: BLIP[->blip:10.0.2.2:4984/travel-sample/_blipsync] performNextMessage
12-11 17:53:53.172 21019-21069/com.couchbase.travelsample I/LiteCore [Actor]: BLIP[->blip:10.0.2.2:4984/travel-sample/_blipsync] performNextMessage
12-11 17:53:53.172 21019-21069/com.couchbase.travelsample I/LiteCore [Actor]: BLIP[->blip:10.0.2.2:4984/travel-sample/_blipsync] performNextMessage
12-11 17:53:53.172 21019-21069/com.couchbase.travelsample I/LiteCore [Actor]: BLIP[->blip:10.0.2.2:4984/travel-sample/_blipsync] performNextMessage
12-11 17:53:53.172 21019-21069/com.couchbase.travelsample I/LiteCore [Actor]: BLIP[->blip:10.0.2.2:4984/travel-sample/_blipsync] performNextMessage
12-11 17:53:53.172 21019-21069/com.couchbase.travelsample I/LiteCore [Actor]: BLIP[->blip:10.0.2.2:4984/travel-sample/_blipsync] performNextMessage
12-11 17:53:53.172 21019-21069/com.couchbase.travelsample I/LiteCore [Actor]: BLIP[->blip:10.0.2.2:4984/travel-sample/_blipsync] performNextMessage
12-11 17:53:53.172 21019-21069/com.couchbase.travelsample I/LiteCore [Actor]: BLIP[->blip:10.0.2.2:4984/travel-sample/_blipsync] performNextMessage
12-11 17:54:03.186 21019-21080/com.couchbase.travelsample E/WebSocket: WebSocketListener.onFailure() response -> null
   java.net.SocketTimeoutException: connect timed out
       at java.net.PlainSocketImpl.socketConnect(Native Method)
       at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
       at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
       at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
       at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
       at java.net.Socket.connect(Socket.java:605)
       at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:69)
       at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:238)
       at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:158)
       at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
       at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
       at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
12-11 17:54:03.187 21019-21080/com.couchbase.travelsample I/LiteCore [WS]: {2}--> blip:10.0.2.2:4984/travel-sample/_blipsync
12-11 17:54:03.187 21019-21080/com.couchbase.travelsample I/LiteCore [WS]: {2} sent 0 bytes, rcvd 0, in 0.000 sec (-nan/sec, -nan/sec)
12-11 17:54:03.187 21019-21071/com.couchbase.travelsample I/LiteCore [Actor]: BLIP[->blip:10.0.2.2:4984/travel-sample/_blipsync] performNextMessage
12-11 17:54:03.187 21019-21071/com.couchbase.travelsample I/LiteCore [BLIP]: {3} Closed with WebSocket status 1000: 
12-11 17:54:03.187 21019-21071/com.couchbase.travelsample I/LiteCore [Actor]: Repl->blip:10.0.2.2:4984/travel-sample/_blipsync performNextMessage
12-11 17:54:03.187 21019-21071/com.couchbase.travelsample I/LiteCore [Sync]: {5}--> Repl->blip:10.0.2.2:4984/travel-sample/_blipsync
12-11 17:54:03.187 21019-21071/com.couchbase.travelsample I/LiteCore [Sync]: {5} Connection closed with WebSocket status 1000: ""
12-11 17:54:03.187 21019-21071/com.couchbase.travelsample I/LiteCore [Sync]: {5} now stopped
12-11 17:54:03.188 21019-21071/com.couchbase.travelsample I/LiteCoreJNI: [NATIVE] C4Replicator.statusChangedCallback() repl -> 0x0xa5ed7780 status -> 0
12-11 17:54:03.189 21019-21071/com.couchbase.travelsample E/C4Replicator: statusChangedCallback() handle -> 2783803264, status -> C4ReplicatorStatus{activityLevel=0, progressUnitsCompleted=0, progressUnitsTotal=0, progressDocumentCount=0, errorDomain=0, errorCode=0, errorInternalInfo=0}
12-11 17:54:03.189 21019-21072/com.couchbase.travelsample I/LiteCore [Actor]: DB->blip:10.0.2.2:4984/travel-sample/_blipsync performNextMessage
12-11 17:54:03.189 21019-21072/com.couchbase.travelsample I/LiteCore [Sync]: {6}--> DB->blip:10.0.2.2:4984/travel-sample/_blipsync
12-11 17:54:03.189 21019-21072/com.couchbase.travelsample I/LiteCore [Sync]: {6} now idle
12-11 17:54:03.189 21019-21072/com.couchbase.travelsample I/LiteCore [Actor]: Push->blip:10.0.2.2:4984/travel-sample/_blipsync performNextMessage
12-11 17:54:03.189 21019-21072/com.couchbase.travelsample I/LiteCore [Sync]: {7}--> Push->blip:10.0.2.2:4984/travel-sample/_blipsync
12-11 17:54:03.189 21019-21072/com.couchbase.travelsample I/LiteCore [Sync]: {7} now idle
12-11 17:54:03.190 21019-21070/com.couchbase.travelsample I/LiteCore [Actor]: Pull->blip:10.0.2.2:4984/travel-sample/_blipsync performNextMessage
12-11 17:54:03.190 21019-21019/com.couchbase.travelsample E/Sync: statusChanged() c4Status -> C4ReplicatorStatus{activityLevel=0, progressUnitsCompleted=0, progressUnitsTotal=0, progressDocumentCount=0, errorDomain=0, errorCode=0, errorInternalInfo=0}
12-11 17:54:03.190 21019-21070/com.couchbase.travelsample I/LiteCore [BLIP]: {4}--> N8litecore4blip6BLIPIOE 0xacfdad00
12-11 17:54:03.190 21019-21070/com.couchbase.travelsample I/LiteCore [BLIP]: {4} ~BLIPIO: Max outbox depth was 0, avg -nan
12-11 17:54:03.190 21019-21070/com.couchbase.travelsample I/LiteCore [Sync]: {8}--> Pull->blip:10.0.2.2:4984/travel-sample/_blipsync
12-11 17:54:03.190 21019-21019/com.couchbase.travelsample E/Sync: Replicator[<*> blip://10.0.2.2:4984/travel-sample] is stopped, progress 0/0, error: null
12-11 17:54:03.190 21019-21070/com.couchbase.travelsample I/LiteCore [Sync]: {8} now busy
12-11 17:54:03.190 21019-21070/com.couchbase.travelsample I/LiteCore [DB]: Closing DataFile
12-11 17:54:03.190 21019-21071/com.couchbase.travelsample I/LiteCore [Actor]: Repl->blip:10.0.2.2:4984/travel-sample/_blipsync performNextMessage
12-11 17:54:03.190 21019-21071/com.couchbase.travelsample I/LiteCore [Actor]: Repl->blip:10.0.2.2:4984/travel-sample/_blipsync performNextMessage
12-11 17:54:03.191 21019-21019/com.couchbase.travelsample E/Rep schedular  Log: ReplicationTag Stopped
12-11 17:54:03.191 21019-21071/com.couchbase.travelsample I/LiteCore [Actor]: Repl->blip:10.0.2.2:4984/travel-sample/_blipsync performNextMessage
12-11 17:54:03.191 21019-21019/com.couchbase.travelsample I/LiteCoreJNI: [NATIVE] C4Replicator.free() repl -> 0xa5ed7780
```

**Comment by pasin** [comment] 2018-01-19 23:38
https://github.com/couchbase/couchbase-lite-ios/commit/9858459a679ef28389555da1aa23d7f84f4b6a06

**Comment by hideki** [comment] 2018-01-20 01:04
With using self-compiled CBL library from https://github.com/couchbase/couchbase-lite-android/commit/dbc436dc1fa807e80c004cbd16faa407aee1e7f8, I could not reproduce the crash. There is a possibility that the issue is fixed by fixing other issues between DB021 and current master.

**Comment by hideki** [comment] 2018-01-20 01:23
@rajagp Thank you very much for all your help.

I could not reproduce this issue with DB021 and build from the master. If you can not reproduce with the latest build with your test environment, please close this. If you could reproduce the problem, please share how to reproduce the problem?
Thanks!

**Comment by pasin** [comment] 2018-01-21 20:14
I think the issue that causes the crash is not in the above stacktrace. I copied the additional stacktrace from the forum post which is the actual cause of the error which may be happens because if not having permission to use ConnectivityManager for checking reachability?

```
java.lang.SecurityException 
at android.os.BinderProxy.transactNative(Native Method) 
at android.os.BinderProxy.transact(Binder.java:511) 
at android.app.ActivityManagerProxy.registerReceiver(ActivityManagerNative.java:3143) 
at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1189) 
at android.app.ContextImpl.registerReceiver(ContextImpl.java:1157) 
at android.app.ContextImpl.registerReceiver(ContextImpl.java:1151) 
at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:554) 
at com.couchbase.lite.AndroidNetworkReachabilityManager.startListening(AndroidNetworkReachabilityManager.java:49) 
at com.couchbase.lite.NetworkReachabilityManager.addNetworkReachabilityListener(NetworkReachabilityManager.java:38) 
at com.couchbase.lite.Replicator.startReachabilityObserver(Replicator.java:581) 
at com.couchbase.lite.Replicator.handleError(Replicator.java:537) 
at com.couchbase.lite.Replicator.c4StatusChanged(Replicator.java:477) 
at com.couchbase.lite.Replicator.access$000(Replicator.java:35) 
at com.couchbase.lite.Replicator$1$1.run(Replicator.java:390) 
at android.os.Handler.handleCallback(Handler.java:815) 
at android.os.Handler.dispatchMessage(Handler.java:104) 
at android.os.Looper.loop(Looper.java:207) 
at android.app.ActivityThread.main(ActivityThread.java:5728) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 12-12 12:11:23.955 14352-14369/? A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 14369 (Thread-23815)
```

**Comment by pasin** [comment] 2018-01-21 20:17
As we couldn't reproduce this issue, I'm wondering if the issue is related to the app settings or the android version.

**Comment by rajagp** [comment] 2018-01-21 21:12
I tested with DB021 on Travel sample and I don't see the issue that I had reported on DB20. I have
(a) a listener registered with replicator 
(b) replicator in continuous mode
(c) stopped the sync gateway

The replicator on Android CBL stopped and reconnected when SGW was back up again. So I would say that this particular issue is resolved.

(Now, the replicator remains in busy state when I switch to airplane mode and back. But I am going to assume that this issue is likely to have been tackled as part of the replicator fixes in DB022 - but someone else could perhaps verify)

**Comment by hideki** [comment] 2018-01-21 23:35
@rajagp 

> (Now, the replicator remains in busy state when I switch to airplane mode and back. But I am going to assume that this issue is likely to have been tackled as part of the replicator fixes in DB022 - but someone else could perhaps verify)

Could you please file the new ticket for Replicator State issue?

Thanks!

**Comment by hideki** [comment] 2018-01-21 23:38
As this issue is not reproducible with CBL build from master, I will close this issue.

**Closed by hideki** 2018-01-21 23:38 UTC
Labels: P1: high, ready, reproduce/investigate
