### ISSUE TITLE
"leaked IntentReceiver com.couchbase.lite.android.AndroidNetworkReachabilityManager$ConnectivityBroadcastReceiver"

### ISSUE THREAD

**Issue by ashwinbhaskar** [couchbase/couchbase-lite-android#511] opened 2015-02-04 09:12 UTC
"leaked IntentReceiver com.couchbase.lite.android.AndroidNetworkReachabilityManager$ConnectivityBroadcastReceiver"

Getting this exception in android even though I have closed the manager and removed listeners for replications
@Override
    protected void onDestroy() {
        super.onDestroy();
        if(pushReplication!=null) {
            pushReplication.removeChangeListener(this);
            pushReplication.stop();
        }
        if(manager!=null)
            manager.close();
    }

**Comment by Takhion** [comment] 2015-02-07 09:49
Yes, this is happening to us too.

**Comment by hideki** [comment] 2015-02-07 19:00
Hi @ashwinbhaskar and @Takhion 

Thank you for your bug report. Could you please more detailed information? It is ideal if you can provide us information which us explained in following doc.
https://github.com/couchbase/couchbase-lite-android/blob/master/CONTRIBUTING.md

**Comment by Takhion** [comment] 2015-02-07 19:12
@hideki this time I have no idea when or why it happens, it just happens a lot!

**Comment by ashwinbhaskar** [comment] 2015-02-08 10:54
@hideki  : **I am using Couchbase Android Lite - 1..0.4 . Stacktrace :**-
```
 8060-8060/com.xxxx.xxxx E/ActivityThread﹕ Activity com.xxxx.xxxx.activities.ListingActivity has leaked IntentReceiver com.couchbase.lite.android.AndroidNetworkReachabilityManager$ConnectivityBroadcastReceiver@10ac1bd that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity com.xxxx.xxxx.activities.ListingActivity has leaked IntentReceiver com.couchbase.lite.android.AndroidNetworkReachabilityManager$ConnectivityBroadcastReceiver@10ac1bd that was originally registered here. Are you missing a call to unregisterReceiver()?
            at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:907)
            at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:708)
            at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1771)
            at android.app.ContextImpl.registerReceiver(ContextImpl.java:1751)
            at android.app.ContextImpl.registerReceiver(ContextImpl.java:1745)
            at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:488)
            at com.couchbase.lite.android.AndroidNetworkReachabilityManager.startListening(AndroidNetworkReachabilityManager.java:50)
            at com.couchbase.lite.NetworkReachabilityManager.addNetworkReachabilityListener(NetworkReachabilityManager.java:26)
            at com.couchbase.lite.replicator.ReplicationInternal.initNetworkReachabilityManager(ReplicationInternal.java:299)
            at com.couchbase.lite.replicator.ReplicationInternal.start(ReplicationInternal.java:239)
            at com.couchbase.lite.replicator.ReplicationInternal$11.doIt(ReplicationInternal.java:1073)
            at com.couchbase.lite.replicator.ReplicationInternal$11.doIt(ReplicationInternal.java:1069)
            at com.github.oxo42.stateless4j.StateConfiguration$3.doIt(StateConfiguration.java:135)
            at com.github.oxo42.stateless4j.StateConfiguration$3.doIt(StateConfiguration.java:133)
            at com.github.oxo42.stateless4j.StateRepresentation.executeEntryActions(StateRepresentation.java:118)
            at com.github.oxo42.stateless4j.StateRepresentation.enter(StateRepresentation.java:97)
            at com.github.oxo42.stateless4j.StateMachine.publicFire(StateMachine.java:199)
            at com.github.oxo42.stateless4j.StateMachine.fire(StateMachine.java:126)
            at com.couchbase.lite.replicator.ReplicationInternal$1.run(ReplicationInternal.java:191)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

**This is the code where I am creating database.**

```
public void createDatabase() throws Exception {
        Manager manager;
        Manager.enableLogging(TAG, com.couchbase.lite.util.Log.VERBOSE);
        Manager.enableLogging(com.couchbase.lite.util.Log.TAG, com.couchbase.lite.util.Log.VERBOSE);
        Manager.enableLogging(com.couchbase.lite.util.Log.TAG_SYNC_ASYNC_TASK, com.couchbase.lite.util.Log.VERBOSE);
        Manager.enableLogging(com.couchbase.lite.util.Log.TAG_SYNC, com.couchbase.lite.util.Log.VERBOSE);
        Manager.enableLogging(com.couchbase.lite.util.Log.TAG_QUERY, com.couchbase.lite.util.Log.VERBOSE);
        Manager.enableLogging(com.couchbase.lite.util.Log.TAG_VIEW, com.couchbase.lite.util.Log.VERBOSE);
        Manager.enableLogging(com.couchbase.lite.util.Log.TAG_DATABASE, com.couchbase.lite.util.Log.VERBOSE);
        try {
            manager = new Manager(new AndroidContext(this), Manager.DEFAULT_OPTIONS);
            com.couchbase.lite.util.Log.d(TAG, "Manager created");
        } catch (IOException e) {
            com.couchbase.lite.util.Log.e(TAG, "Cannot create manager object");
            return;
        }

        if (!Manager.isValidDatabaseName(dbname)) {
            com.couchbase.lite.util.Log.e(TAG, "Bad database name");
            return;
        }

        try {
            database = manager.getDatabase(dbname);
            com.couchbase.lite.util.Log.d(TAG, "Database created");
        } catch (CouchbaseLiteException e) {
            com.couchbase.lite.util.Log.e(TAG, "Cannot get database");
            return;
        }

        startSync();
    }
```

**And removing listeners and closing DB. **

```
 @Override
    protected void onDestroy() {
        super.onDestroy();
        if(pushReplication!=null) {
            pushReplication.removeChangeListener(this);
            pushReplication.stop();
        }
        if(manager!=null)
            manager.close();
    }
```


Let me know if you need any other details.

**Comment by tleyden** [comment] 2015-02-09 19:43
@hideki it might be worth trying to reproduce this via testing todolite.  Maybe the exception is in the logs, but nobody is noticiting.  @pasin added Crashlytics support I believe, that may help finding these kinds of exceptions easier.

**Comment by ashwinbhaskar** [comment] 2015-02-10 03:20
@hideki  and @tleyden I have given you the full stack trace.  Is there anyway else I can be of help?

**Comment by hideki** [comment] 2015-02-10 06:53
@ashwinbhaskar I will look into this issue during this week. Thanks for your patience.

**Comment by hideki** [comment] 2015-02-12 00:27
Hi @ashwinbhaskar and @Takhion 

So far, I could not reproduce this issue.

From stack trace and source code, CBL calls [registerReceiver](http://developer.android.com/reference/android/content/ContextWrapper.html#registerReceiver(android.content.BroadcastReceiver, android.content.IntentFilter)) when the replicator starts. From stacktrace, it seems that `registerReceiver()` is called multiple times without calling `unregiserReceiver()`. [unregisterReceiver](http://developer.android.com/reference/android/content/ContextWrapper.html#unregisterReceiver(android.content.BroadcastReceiver)) is called in `Manager.close()` method, which is not automatically called.

Some questions:
- Does your app creates multiple Manager instances? For example, Manager per Activity.
- Does your app creates multiple Replicators? For example, app has multiple databases, and replicator per database?
- What is your Android SDK version?

Please share us if you found any observations.

**Comment by hideki** [comment] 2015-02-12 01:05
Hi @ashwinbhaskar and @Takhion 

How many Activity does your app have?

- Single Activity:
According to the [post](http://stackoverflow.com/questions/14357566/activity-has-leaked-intentreceiver-that-was-originally-registered-here-are-you) of stackoverflow, `unregisterReceiver(receiver)` should be called in `onStop()` of Activity life cycle. See [Activity Life Cycle](http://developer.android.com/reference/android/app/Activity.html). In stead of `onDestroy()`, please stop replicator and call `Manager.close()` in `onStop()` method.

- Multiple Activities:
We recommends Manager instance should be single instance per application. Could you please make sure Manager instance is hold in [Application](http://developer.android.com/reference/android/app/Application.html) and given ApplicationContext as Manager constructor parameter. see below
```
manager = new Manager(new AndroidContext(getApplicationContext()), Manager.DEFAULT_OPTIONS);
```
According to Android document [Tasks and Back Stack](http://developer.android.com/guide/components/tasks-and-back-stack.html), Activities in BackStack could be destroyed if there is memory issue.
> When the system stops one of your activities (such as when a new activity starts or the task moves to the background), the system might destroy that activity completely if it needs to recover system memory. When this happens, information about the activity state is lost. If this happens, the system still knows that the activity has a place in the back stack, but when the activity is brought to the top of the stack the system must recreate it (rather than resume it). In order to avoid losing the user's work, you should proactively retain it by implementing the onSaveInstanceState() callback methods in your activity.

Please let us know if this solves `leaked IntentReceiver ` issue.

**Comment by Takhion** [comment] 2015-02-12 07:37
@hideki we only create a single Manager instance with the Application Context the first time that data is needed anywhere in the app, and then never close it. We started noticing the aforementioned error while experimenting with replications, in particular while creating 2 of them at the same time (continuous push/pull). SDK version is 21 (Lollipop).

**Comment by hideki** [comment] 2015-02-12 07:51
@Takhion thanks for additional information.

Our demo application, [ToDoLite Andorid](https://github.com/couchbaselabs/ToDoLite-Android), also creates pull and push replicators with continuous mode, but it creates and starts replicators in Application instance. I tried to reproduce "leaked IntentReceiver" issue with using it. So far, I could not reproduce it.

When you have time, could you please compare the difference between your app and ToDoLite demo app? It might give us hints.

Thanks for all your helps!

**Comment by hideki** [comment] 2015-02-17 19:07
Currently we can not reproduce this issue, so put this ticket in backlog. We will keep our eye open for this issue.

**Closed** 2015-03-20 22:14 UTC
Labels: needsmoreinfo
