### ISSUE TITLE
SQLiteFullException: database or disk is full (code 13)

### ISSUE THREAD

**Issue by SafetyMarcus** [couchbase/couchbase-lite-android#664] opened 2015-09-14 05:54 UTC
I have more and more users seeing this error showing up when they are trying to delete documents. The documents are being retrieved using `getExistingDocument()`.

Full trace:
```
android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
       at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:745)
       at android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:437)
       at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:401)
       at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:537)
       at com.couchbase.lite.android.AndroidSQLiteStorageEngine.endTransaction(SourceFile:100)
       at com.couchbase.lite.Database.endTransaction(SourceFile:1579)
       at com.couchbase.lite.Database.runInTransaction(SourceFile:686)
       at com.couchbase.lite.Document.purge(SourceFile:193)
```

**Comment by hideki** [comment] 2015-09-15 00:49
Hi @SafetyMarcus,

Thank you very much for reporting issue.
From log message, it seems storage is full. But it is not clear what caused this.
Could you please provide supporting information if possible.

Thanks!

**Comment by hideki** [comment] 2015-09-18 23:52
Hi @SafetyMarcus,
Does you app calls [Database.compact()](http://developer.couchbase.com/documentation/mobile/1.1.0/develop/references/couchbase-lite/couchbase-lite/database/database/index.html#void-compact) ?

**Comment by SafetyMarcus** [comment] 2015-09-19 11:43
Hi @hideki. No we are not calling Database.compact() anywhere within the app. Should this be being called? Could it be due to the fact that `getDocumentWithIDAndRev()` is requesting the results be in descending order even though it is being limited to 1? As far as I'm aware this will create a temporary table in memory.

**Comment by pasin** [comment] 2015-11-26 00:18
SQLite_FULL error could be happened due to full main or temp disk. Android uses memory for temp so it's possible that the temp memory is full. I'm not sure if `getDocumentWithIDAndRev()` is causing issue (it's hard to tell).

From your stacktrace, it looks like the error happened in a transaction when calling `purge` method. It's possible that if you have very large revision tree to purge in one transaction, it could be out of temp memory. @SafetyMarcus will you able to reproduce the issue yourself? Do you know if the purged document has a lot of revisions?

As @hideki said, regularly calling `compact()` would help trimming unused revisions. To make the compact() working correctly, you will need to set Database.setMaxRevTreeDepth() to a reasonable number depending on your app (maybe 20). Also please make sure that you manage conflicting documents by tom-stoning losing revisions so that they could be garbaged during compact().

**Comment by pasin** [comment] 2015-12-11 18:38
@SafetyMarcus FYI, we have recently fixed the compact method. That will be included in the next 1.2 release. Meanwhile, you will need to build the library from the master branch. Please let us know if regularly doing compact helps with your issue.

**Comment by pasin** [comment] 2015-12-11 18:40
For now I will close the issue and we can reopen anytime if regularly compacting the database doesn't help. Thanks!

**Closed by pasin** 2015-12-11 18:40 UTC
Labels: needsmoreinfo, waffle:ready

**Comment by SafetyMarcus** [comment] 2016-01-28 07:04
Sorry @pasin, I somehow missed those responses 😓. I am unable to reproduce the issue myself but it is possible that that the users' documents are quite large and purging of even a small number of revisions could be causing this issue. I look forward to the 1.2 release

**Comment by midcloud** [comment] 2017-02-21 07:06
@pasin  I have met the same error. Trace as follow:
02-04 01:17:19.039 W/ContextImpl( 7961): Unable to create files subdir /data/user/0/com.android.launcher3/cache
02-04 01:17:19.040 E/ActivityThread( 7961): Unable to setupGraphicsSupport due to missing cache directory
02-04 01:17:19.056 E/SQLiteLog( 7961): (14) cannot open file at line 30046 of [9491ba7d73]
02-04 01:17:19.056 E/SQLiteLog( 7961): (14) os_unix.c:30046: (13) open(/data/user/0/com.android.launcher3/databases/launcher.db) - 
02-04 01:17:19.058 E/SQLiteDatabase( 7961): Failed to open database '/data/user/0/com.android.launcher3/databases/launcher.db'.
02-04 01:17:19.058 E/SQLiteDatabase( 7961): android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
02-04 01:17:19.058 E/SQLiteDatabase( 7961): 	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
02-04 01:17:19.058 E/SQLiteDatabase( 7961): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
02-04 01:17:19.058 E/SQLiteDatabase( 7961): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
02-04 01:17:19.058 E/SQLiteDatabase( 7961): 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
02-04 01:17:19.058 E/SQLiteDatabase( 7961): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
02-04 01:17:19.058 E/SQLiteDatabase( 7961): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
02-04 01:17:19.058 E/SQLiteDatabase( 7961): 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
02-04 01:17:19.058 E/SQLiteDatabase( 7961): 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
02-04 01:17:19.058 E/SQLiteDatabase( 7961): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
02-04 01:17:19.058 E/SQLiteDatabase( 7961): 	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1155)
02-04 01:17:19.058 E/SQLiteDatabase( 7961): 	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:268)
02-04 01:17:19.058 E/SQLiteDatabase( 7961): 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
02-04 01:17:19.058 E/SQLiteDatabase( 7961): 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
02-04 01:17:19.058 E/SQLiteDatabase( 7961): 	at com.android.launcher3.LauncherProvider$DatabaseHelper.<init>(LauncherProvider.java:468)
02-04 01:17:19.058 E/SQLiteDatabase( 7961): 	at com.android.launcher3.LauncherProvider.onCreate(LauncherProvider.java:123)
02-04 01:17:19.058 E/SQLiteDatabase( 7961): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1730)
02-04 01:17:19.058 E/SQLiteDatabase( 7961): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1705)
02-04 01:17:19.058 E/SQLiteDatabase( 7961): 	at android.app.ActivityThread.installProvider(ActivityThread.java:4999)
02-04 01:17:19.058 E/SQLiteDatabase( 7961): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4594)
02-04 01:17:19.058 E/SQLiteDatabase( 7961): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4534)
02-04 01:17:19.058 E/SQLiteDatabase( 7961): 	at android.app.ActivityThread.access$1500(ActivityThread.java:151)
02-04 01:17:19.058 E/SQLiteDatabase( 7961): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
02-04 01:17:19.058 E/SQLiteDatabase( 7961): 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-04 01:17:19.058 E/SQLiteDatabase( 7961): 	at android.os.Looper.loop(Looper.java:135)
02-04 01:17:19.058 E/SQLiteDatabase( 7961): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
02-04 01:17:19.058 E/SQLiteDatabase( 7961): 	at java.lang.reflect.Method.invoke(Native Method)
02-04 01:17:19.058 E/SQLiteDatabase( 7961): 	at java.lang.reflect.Method.invoke(Method.java:372)
02-04 01:17:19.058 E/SQLiteDatabase( 7961): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
02-04 01:17:19.058 E/SQLiteDatabase( 7961): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
02-04 01:17:19.059 D/AndroidRuntime( 7961): Shutting down VM
02-04 01:17:19.065 I/Process ( 7961): Sending signal. PID: 7961 SIG: 9

**Comment by hideki** [comment] 2017-02-23 05:36
@midcloud 
It seems that the application does not have write permission to the application directory. Did you install the app to SDCARD? or Can you check write permission?
Thanks!

**Comment by IvanAldrich** [comment] 2017-03-07 03:35
@hideki I got the same exception too.. Have you got any idea about it?
`android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:548)
	at android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:437)
	at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:401)
	at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:522)
	at de.greenrobot.dao.AbstractDao.executeInsert(AbstractDao.java:352)
	at de.greenrobot.dao.AbstractDao.insertOrReplace(AbstractDao.java:332)`

**Comment by hideki** [comment] 2017-03-07 06:28
@IvanAldrich,
I guess Android disk is full or the app is installed on SDCARD.
Can you confirm?
Thanks!

**Comment by IvanAldrich** [comment] 2017-03-07 09:07
@hideki Sorry i can't be sure. It's reported by user and i can't know wether it's full or not. Does there any other factor result in this exception? The user reported more than 10 crash in one day..

**Comment by IvanAldrich** [comment] 2017-03-09 02:57
@hideki @pasin It's confirmed that the usableSpace of dataDirectory is 473518080, so I suppose it's not because of the full of disk. In my project I delete a list of Entity in a for statement and then excute replaceOrInsert immediately, is there any possibility this kind of operation cause thi exception?

**Comment by hideki** [comment] 2017-03-09 05:35
From SQLite documentation

> (13) SQLITE_FULL
>
>The SQLITE_FULL result code indicates that a write could not complete because the disk is full. Note that this error can occur when trying to write information into the main database file, or it can also occur when writing into temporary disk files.
Sometimes applications encounter this error even though there is an abundance of primary disk space because the error occurs when writing into temporary disk files on a system where temporary files are stored on a separate partition with much less space that the primary disk.

https://www.sqlite.org/rescode.html#full

I guess application is installed on SDCARD or something.

**Comment by midcloud** [comment] 2017-04-13 00:42
@hideki  Thanks for your kindly reply.
 Finally,we have found the cause. During the device on aging test,the directory /data/user permissions have been changed. so we add  "mkdir /data/user 0711 system system"   in rootdir/init.rc to solve this issue.

**Comment by lyhyesther** [comment] 2018-09-06 02:02
I have the same issue.

android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
	at org.greenrobot.greendao.AbstractDao.insertInsideTx(AbstractDao.java:368)
	at org.greenrobot.greendao.AbstractDao.executeInsert(AbstractDao.java:351)
	at org.greenrobot.greendao.AbstractDao.insertOrReplace(AbstractDao.java:340)

the device system information:
Android:4.4.2

The device cause, sure?
