### ISSUE TITLE
checkpoint id changing for the very same replication

### ISSUE THREAD

**Issue by ilmaruk** [couchbase/couchbase-lite-android#416] opened 2014-09-23 15:32 UTC
Hello,

We are experiencing slow replications and upon investigation, we realised the checkpoint ids, for the very same replications (same source/target, same filter, same query_params) are every so often changing, thus causing requests to the _changes feed to be executed without the since parameter.

We're using the CBLite plugin for Phonegap (based on CBLite for Android 1.0.1) and in seems the checkpoint ids change when the DB is re-created and when the app is paused and then resumed.

Why are checkpoint ids changing? Is this a bug or is there a reason behind this?

Thanks a lot,
Ruggero

**Comment by hideki** [comment] 2015-02-17 21:20
According to comments, it seems this issue (changing checkpoint-id) was caused by multiple changeTracker instances which was fixed by other ticket (https://github.com/couchbase/couchbase-lite-java-core/issues/253). I will close this issue. If this is reproducible with latest master branch, please reopen. Thanks!

**Closed by hideki** 2015-02-17 21:20 UTC
Labels: needsmoreinfo, waffle:ready
