### ISSUE TITLE
2.0: How do we properly stop puller Replicator and delete database ?

### ISSUE THREAD

**Issue by AlBlanc** [couchbase/couchbase-lite-android#1347] opened 2017-08-16 22:26 UTC
Hello Couchbase community,

I am tried to clean my database properly but two exceptions are triggered:

```
E/C4Socket: C4Socket.callback.requestClose() socket -> 0x7d76098990, status -> 1000, message -> null
E/C4Replicator: statusChangedCallback() handle -> 538601726368, status -> C4ReplicatorStatus{activityLevel=4, progressCompleted=0, progressTotal=0, errorDomain=0, errorCode=0, errorInternalInfo=0}
I/Sync: C4ReplicatorListener.statusChanged() status -> C4ReplicatorStatus{activityLevel=4, progressCompleted=0, progressTotal=0, errorDomain=0, errorCode=0, errorInternalInfo=0}
E/AndroidRuntime: FATAL EXCEPTION: Thread-19
  Process: io.sportner.client, PID: 1233
  java.lang.NullPointerException: Attempt to invoke interface method 'boolean okhttp3.WebSocket.close(int, java.lang.String)' on a null object reference
      at com.couchbase.lite.internal.replicator.CBLWebSocket.requestClose(CBLWebSocket.java:192)
      at com.couchbase.litecore.C4Socket.requestClose(C4Socket.java:154)
W/art: Suspending all threads took: 146.438ms
W/System.err: CouchbaseLiteException{domain=1, code=24}
W/System.err:     at com.couchbase.lite.internal.bridge.LiteCoreBridge.convertException(LiteCoreBridge.java:22)
W/System.err:     at com.couchbase.lite.Database.deleteC4DB(Database.java:761)
W/System.err:     at com.couchbase.lite.Database.delete(Database.java:369)
W/System.err:     at io.sportner.client.core.db.DatabaseHelper.delete(DatabaseHelper.java:163)
W/System.err:     at io.sportner.client.core.AppContext.delete(AppContext.java:155)
W/System.err:     at io.sportner.client.core.controllers.AuthController.logout(AuthController.java:62)
W/System.err:     at io.sportner.client.ui.fragments.UserSettingsFragment$3.onClick(UserSettingsFragment.java:70)
W/System.err:     at android.view.View.performClick(View.java:6261)
W/System.err:     at android.view.View$PerformClick.run(View.java:23748)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err:     at android.os.Looper.loop(Looper.java:154)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6776)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
W/System.err: Caused by: LiteCoreException{domain=1, code=24, msg=database busy/locked}
W/System.err:     at com.couchbase.litecore.C4Database.delete(Native Method)
W/System.err:     at com.couchbase.litecore.C4Database.delete(C4Database.java:55)
W/System.err:     at com.couchbase.lite.Database.deleteC4DB(Database.java:759)
W/System.err: 	... 14 more
E/DatabaseHelper: Failed to delete database
```

Here is the  `delete()` methode, I call:

```
public void pauseSync() {
        if (mPuller != null && mPuller.getStatus().getActivityLevel() != Replicator.ActivityLevel.STOPPED) {
            Log.d(TAG, "Pause Synchronisation");
            mPuller.stop();
        }
    }

public void delete() {
        pauseSync();
        mPuller = null;
        if (mDatabase != null) {
            try {
                mDatabase.delete();
                mDatabase.close();
                mDatabase = null;
                Log.i(TAG, "Database is deleted");
            } catch (CouchbaseLiteException e) {
                e.printStackTrace();
                Log.e(TAG, "Failed to delete database");
            }
        }
    }
```

It is because the application still have some `DocumentChangeListener` bind on the database ? 

Please notice also, the exception triggered when i try to stop the replicator which did not authenticate well. (So it is not active) Should I check another replicator status to prevent this case?

**Comment by hideki** [comment] 2017-08-31 22:02
`LiteCoreException{domain=1, code=24, msg=database busy/locked}` Exception was thrown because internal Database is in used. Not because of `DocumentChangeListener`.

`NullPointerException` was thrown by closing the websocket which was not initialized.

**Comment by AlBlanc** [comment] 2017-08-31 22:37
Yeah I saw about for the NPE, the thread was more about the `LiteCoreException` thank you for the explanations.

What do you mean exactly by "Database is in used", should I close it before ?

**Comment by hideki** [comment] 2017-08-31 22:40
When a thread A tried to close the database, I assume the other thread wrote to or read from the database. Therefore, database close operation failed.

**Comment by hideki** [comment] 2017-08-31 23:08
Hi @AlBlanc,

I have tried to reproduce the NPE when calling Replicator.stop() method. So far, I could not reproduce the problem. If you still encounter this problem, could you please share the steps to reproduce the problem? or can you write simple sample codes that can reproduce the problem?

Thanks!

**Comment by hideki** [comment] 2017-09-07 21:15
Hi @AlBlanc,
Do you have any updates?

**Comment by AlBlanc** [comment] 2017-09-08 08:30
Hi @hideki,

Sorry, I can't give you feedback before Monday. I'll come back to you

**Comment by hideki** [comment] 2017-09-18 21:59
As we don't have additional information about this ticket, I will close this for now. If the issue is still reproducible, please reopen the ticket.

**Closed by hideki** 2017-09-18 21:59 UTC
Labels: bug, needsmoreinfo, ready, reproduce/investigate
