### ISSUE TITLE
Replication default limit of 50 rows with CBL 1.3.0 ???

### ISSUE THREAD

**Issue by Stephanevincenza** [couchbase/couchbase-lite-android#955] opened 2016-08-07 20:01 UTC
I'm working on a mobile project with sync gateway and CBL android.
Today I've updated both app and gateway with 1.3
Now, when I start a replication there's a strange new line in the gateway's log 

2016-08-07T21:37:45.483+02:00 HTTP:  #034: POST /ck/_changes?feed=normal&heartbeat=30000&style=all_docs&since=29732&limit=50  (as 13+294)

And my app needs to pull more than 50 docs during installation.
I've never add this problem with 1.2.1 and the same code.....

The replication is not continuous.

**Comment by opicciotto** [comment] 2016-08-08 15:28
Hello,

I have the same issue. We see a "limit=50" in the request, and my local database only replicates 50 documents although I have more than 700 in my server database..
This doesn't occur in CBL Android 1.2.1..

Thx

**Comment by pasin** [comment] 2016-08-08 18:56
Note that couchbase-lite-ios now doesn't set the limit=50. It seems like with the limit set, the single shot replicator can only pull up to 50 and then stop.

**Comment by pasin** [comment] 2016-08-09 01:59
I was able to reproduce the issue and see where the limit get set. I will remove the limit and push the fix soon.

**Comment by Stephanevincenza** [comment] 2016-08-09 06:21
Many thanks for reactivity !!!

**Comment by opicciotto** [comment] 2016-08-09 07:51
Thanks for this : )
Will there be an official build soon ?

**Comment by hideki** [comment] 2016-08-09 10:16
https://github.com/couchbase/couchbase-lite-java-core/commit/ed9a4ec2d99d2d9639af7e8fc0ca395b459bc4dd could fix this issue.

**Comment by hideki** [comment] 2016-08-09 10:28
Till we decide next release number, temporary I put `1.4.0` milestone.

**Comment by pasin** [comment] 2016-08-09 16:11
Let set the release to 1.3.1 for now.

**Comment by pasin** [comment] 2016-08-09 21:00
The issue is fixed and committed to the master branch. I'm closing the issue now. Once I know more about the release that will include the fix, I will update the info on this issue.

**Closed by pasin** 2016-08-09 21:00 UTC
Labels: bug, P1: high, review
