### ISSUE TITLE
`SQLiteException: no such collation sequence: JSON` on Barnes & Noble NOOK HD/HD+

### ISSUE THREAD

**Issue by Takhion** [couchbase/couchbase-lite-android#434] opened 2014-10-21 16:40 UTC
Observed this one through (a lot of) crash reports, seems to target only these devices by producer "BN LLC" (Barnes & Noble):
* BNTV400 (NOOK HD) on 4.0.4
* BNTV600 (NOOK HD+) on 4.0.4

Stacktrace:
```
android.database.sqlite.SQLiteException: no such collation sequence: JSON: , while compiling: SELECT key, value, docid, revs.sequence, revid, json FROM maps, revs, docs WHERE maps.view_id=? AND key in (?) AND revs.sequence = maps.sequence AND docs.doc_id = revs.doc_id ORDER BY key LIMIT ? OFFSET ?
	at android.database.sqlite.SQLiteCompiledSql.native_compile(Native Method)
	at android.database.sqlite.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:68)
	at android.database.sqlite.SQLiteProgram.compileSql(SQLiteProgram.java:143)
	at android.database.sqlite.SQLiteProgram.compileAndbindAllArgs(SQLiteProgram.java:361)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:127)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:94)
	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:53)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:47)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1564)
	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1538)
	at com.couchbase.lite.android.AndroidSQLiteStorageEngine.rawQuery(SourceFile:111)
	at com.couchbase.lite.View.resultSetWithOptions(SourceFile:685)
	at com.couchbase.lite.View.queryWithOptions(SourceFile:852)
	at com.couchbase.lite.Database.queryViewNamed(SourceFile:2062)
	at com.couchbase.lite.Query$1.run(SourceFile:403)
    ...
```

**Comment by hideki** [comment] 2015-02-13 06:06
Hi @Takhion 

From stack-trace, it seems that the native library that CBL provides is not available for BNTVxxx. CBL Android/Java provides two collators for REVID and JSON columns as native library.
```
android.database.sqlite.SQLiteException: no such collation sequence: JSON
```

CBL Android v1.0.3.1 or earlier supports four architectures, armeabi-v7a, armeabi, mips and x86. I assume BNTVxxx uses other architecture that CBL v1.0.3.1 or earlier does not supports.

From v1.0.4, CBL supports seven architectures, arm64-v8a, armeabi-v7a, armeabi, mips, mips64, x86 and x86_64.

If you are currently using v1.0.3.1 or earlier, could you please try to use 1.0.4 or master branch?

1.0.4 is available on maven repository if you are using Android Studio. If you are using Eclipse, please compile from master or 1.0.4 branch?

Thanks,

**Comment by hideki** [comment] 2015-02-13 06:09
@andreibaranouski If possible, could you please run the test with BNTV400 or BNTV600 on AppThwack?

**Comment by Takhion** [comment] 2015-02-13 08:01
Hi @hideki, I'll check if the issue is still present with 1.0.4 as soon as I'm in the office, in the meantime I wanted to share the fact that both BNTV400 and BNTV600 are ARMv7 with Android version 4.0.4, which means they can't be 64 bits!

**Comment by Takhion** [comment] 2015-02-13 12:46
So I checked and the version we currently have in production (where we are seeing the crashes) is [`0.0.0-26`](http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/0.0.0-26/). I think that the AppThwack test will tell you more!

**Comment by hideki** [comment] 2015-02-13 15:25
@Takhion Just I'd like to make sure. Does 1.0.4 not solve the issue?

**Comment by Takhion** [comment] 2015-02-13 15:30
I don't remember if version `0.0.0-26` already contains the extra native collators, but in any case I don't think that that's the problem. I won't be able to test `1.0.4` in production for some weeks, so I believe your best bet is to try with AppThwack or find someone with those devices.

**Comment by hideki** [comment] 2015-02-13 15:46
v0.0.0-26 was built Oct 21, 2014. I believe it was before native library fix.

**Comment by hideki** [comment] 2015-02-13 23:21
We run our unit test with release/1.0.4 using BN Nook on appthwack. 

Device: Barnes & Noble NOOK HD OS: 4.0.4 CPU ARMv7
CBL version: release/1.0.4

We don't observe the android.database.sqlite.SQLiteException, which is custom collator issue with native library.

Followings are not related with this ticket:
Actually two test cases failed with NOOK HD (Fail: 2 out of 292 tests failed)
- ManagerTest.testReplaceDatabaseNamedNoAttachments
- ManagerTest.testReplaceDatabaseNamedWithAttachments

Note: I will close this ticket. If you would encountered this issue with upgrading to v1.0.4, please reopen the ticket.

**Comment by Takhion** [comment] 2015-06-05 18:14
Hi @hideki, unfortunately with `1.1.0-17` (taken from your maven repo, built with Gradle) the issue is still present!

```
android.database.sqlite.SQLiteException: no such collation sequence: REVID: , while compiling: SELECT revid, deleted, sequence, no_attachments, json FROM revs, docs WHERE docs.docid=? AND revs.doc_id=docs.doc_id and current=1 and deleted=0 ORDER BY revid DESC LIMIT 1
	at android.database.sqlite.SQLiteCompiledSql.native_compile(Native Method)
	at android.database.sqlite.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:68)
	at android.database.sqlite.SQLiteProgram.compileSql(SQLiteProgram.java:143)
	at android.database.sqlite.SQLiteProgram.compileAndbindAllArgs(SQLiteProgram.java:361)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:127)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:94)
	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:53)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:47)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1564)
	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1538)
	at com.couchbase.lite.android.AndroidSQLiteStorageEngine.rawQuery(SourceFile:128)
	at com.couchbase.lite.Database.getDocumentWithIDAndRev(SourceFile:1894)
	at com.couchbase.lite.Database.getExistingDocument(SourceFile:456)
	...
```

**Comment by hideki** [comment] 2015-06-06 05:52
Hi @Takhion,

On Appthwack, BNTV400 or BNTV600 is not available with Android 4.x. Available OS is 2.0.4 that Couchbase Lite Android does not support. https://appthwack.com/devicelab  This issue is not possible to reproduce by ourself now.

I believe this error comes from https://github.com/couchbase/couchbase-lite-android/blob/master/jniLibs/armeabi-v7a/libcom_couchbase_touchdb_RevCollator.so

Before the `SQLiteException`, can you see any other error messages?

Thanks!

**Comment by Takhion** [comment] 2015-06-11 06:35
Hi @hideki,

No, everything that comes from before `SQLiteException` has nothing to do with SQL or CBL... I think the only way is to get a physical device and test it there, it's crashing like 100% of the time.

**Comment by hideki** [comment] 2015-06-13 01:23
Hi @Takhion,

We are considering this issue could be same issue which is described following links. Some specific devices load armeabi library instead of armeabi-v7a.
https://groups.google.com/forum/#!msg/android-ndk/N8FLjvM81pg/2rYeClQZcckJ
https://code.google.com/p/android/issues/detail?id=25321

Could you please test Counchbase Lite on Nook with removing armeabi/*.so files?

Have a nice weekends!

**Comment by hideki** [comment] 2015-06-13 01:35
Note to Self:
Workaround: https://moodstocks.com/blog/article/ice-cream-sandwich-why-native-code-support-sucks/

**Comment by Takhion** [comment] 2015-06-25 18:35
@hideki unfortunately I don't personally have access to any of those devices, we just receive a lot of crash reports from users!

**Comment by drspaceboo** [comment] 2015-06-30 22:17
Hi @hideki,
We have been seeing a related issue to this. I'm getting the following crash:
```
Fatal Exception: java.lang.UnsatisfiedLinkError
Couldn't load com_couchbase_touchdb_TDCollateJSON from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.app-1.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]]: findLibrary returned null
```
This is happening on a user's Acer A500.

I've seen similar issues previously with the old Dropbox library where they had the `armeabi` and armeabi-v7a` folders and assumed that all devices would fall back when they didn't find an `armeabi-v7` folder.

Unfortunately one of two things can stop this:
# The device might not fall back correctly
# If an application has an `armeabi-v7` folder declared for something else then it will assume all libraries are in that folder and look there to load them.

We are in the latter camp.


Sidebar: The Moodstocks link you put in is a pretty good solution to this problem in my opinion. We used to do this with Dropbox and had great results. Saw all our native library linking issues disappear.

**Comment by hideki** [comment] 2015-07-01 06:35
Hi @drspaceboo Thank you for sharing information.

**Comment by drspaceboo** [comment] 2015-08-06 03:31
Hi @hideki,
Can we please get an update on when this issue will be resolved? It is now the most reported crash we have from our application.

**Comment by hideki** [comment] 2015-08-06 07:15
Hi @drspaceboo,
We don't have BN Nook device.  Unfortunately, no update for this issue.

**Comment by drspaceboo** [comment] 2015-08-06 07:40
Hi @hideki,
We aren't seeing the issue on a BN Nook, that was the original reporter. We have users on the following devices seeing this crash:
* [Samsung I9300 Galaxy S III](http://www.gsmarena.com/samsung_i9300_galaxy_s_iii-4238.php)
* [Samsung Galaxy Tab Active (LTE) SM-T365] (http://www.samsung.com/ae/consumer/mobile-devices/tablets/others/SM-T365NNGAXSG)
* [Samsung Galaxy Tab 3 SM-T315T](http://pdadb.net/index.php?m=specs&id=5687&c=samsung_sm-t315t_galaxy_tab_3_8.0_lte_16gb)
* [Samsung Galaxy Note (8.0) GT-N5110](http://www.samsung.com/au/consumer/mobile-phone/tablet/tablet/GT-N5110ZWAXSA)
* [ASUS MeMO Pad HD 7 (ME173X)](https://www.asus.com/au/Tablets/ASUS_MeMO_Pad_HD_7_ME173X/)
* [Acer Iconia Tab A500](http://www.gsmarena.com/acer_iconia_tab_a500-3907.php)
* [Fujitsu Stylistic M532](http://www.pcmag.com/article2/0,2817,2410164,00.asp)

**Comment by Takhion** [comment] 2015-08-06 07:45
Hi @hideki,

If you're willing to build the latest stable Couchbase Lite version with
the workaround you mentioned applied to it, I'd be happy to try it with a
subset of our users to see if it solves the problem! The only thing I ask
is that you put it in your Maven repository as we're using Gradle for our
build.

**Comment by hideki** [comment] 2015-08-06 20:26
Hi @drspaceboo,
We have Samsung S3 which OS version is Android 4.1.2.
I run the simple test with S3. However I could not reproduce the issue.
Can you check Android OS versions that causes this issue?
Thanks!

**Comment by hideki** [comment] 2015-08-06 21:20
Hi @Takhion,
Thank you for your kind offer. Preparation could take a time. Could you give me 1 or 2 weeks.
Thanks!

**Comment by drspaceboo** [comment] 2015-08-06 22:25
Hi @hideki,
The user S3 was running 4.1.2. I'll PM you a link to the crashes hopefully that might help.

**Comment by Takhion** [comment] 2015-08-07 08:44
Hi @hideki,
Sure, I'll wait for it, thanks!

**Comment by hideki** [comment] 2015-08-11 01:46
Hi @drspaceboo,

If you can build from source code, Please try to use the following branch which includes the fix. https://github.com/couchbase/couchbase-lite-android/tree/feature/issue_434_jni_lib_load_failure

Add Couchbase Lite to your project as a submodule:
https://github.com/couchbase/couchbase-lite-android/wiki/Add-Couchbase-Lite-to-your-project-as-a-submodule

NOTE: I needs few days to post the jar files on maven.

Thanks.

**Comment by drspaceboo** [comment] 2015-08-11 04:58
Hey Hideki,
We try not to change our dependancies for a build that goes out to all our users, and unfortunately those affected users haven't made themselves known via our support team yet. So at the moment we will need to wait for the Gradle dependancies to go up on Maven before I can let you know if it resolved the issue.

I have high hopes from the change logs though.

Let us know here when it goes up on Maven for Gradle and we can get it in our next release to test against our user base.

**Comment by hideki** [comment] 2015-08-11 22:12
Note to self:

Following is test result with applying ARM v7a detection. The solution does not work with Motorola Xoom. Needs to investigate.

## Real device 
| Device  | Android Version | CPU Family | Result |
| ------------   | ------------- | ------------- | ------------- |
| Nexus 6 | 5.1.1 | ARM | OK |
| Samsung SIII | 4.1.2 | ARM | OK |
| Motorola Xoom | 4.1.2 | ARM | **NG** |

## Emulator 
| API  | Android Version | CPU Family | Result |
| ------------- | ------------- | ------------- | ------------- |
| API 10 | 2.3.3 | ARM | OK |
| API 14 | 4.0 | ARM | OK |
| API 15 | 4.0.3 | ARM | OK |
| API 15 | 4.0.3 | x86 | OK |
| API 16 | 4.1.2 | ARM | OK |
| API 16 | 4.2.2 | x86 | OK |
| API 16 | 4.2.2 | Mips | OK |
| API 18 | 4.3.1 | x86 | OK |
| API 21 | 5.0.1 | ARM | OK |
| API 21 | 5.0.1 | x86 | OK |
| API 22 | 5.1.1 | x86_64 | OK |

**Comment by hideki** [comment] 2015-08-11 22:19
Note to Self:

it seems loading CPU family detection native library failed.
```
08-11 15:14:02.020  24621-24621/? D/dalvikvm﹕ No JNI_OnLoad found in /data/data/self.hideki.issueandroid434/lib/libcom_couchbase_touchdb_TDCollateJSON_util.so 0x41b60648, skipping init
```

Log:
```
08-11 15:14:02.020  24621-24621/? D/dalvikvm﹕ Trying to load lib /data/data/self.hideki.issueandroid434/lib/libcom_couchbase_touchdb_TDCollateJSON_util.so 0x41b60648
08-11 15:14:02.020  24621-24621/? D/dalvikvm﹕ Added shared lib /data/data/self.hideki.issueandroid434/lib/libcom_couchbase_touchdb_TDCollateJSON_util.so 0x41b60648
08-11 15:14:02.020  24621-24621/? D/dalvikvm﹕ No JNI_OnLoad found in /data/data/self.hideki.issueandroid434/lib/libcom_couchbase_touchdb_TDCollateJSON_util.so 0x41b60648, skipping init
08-11 15:14:02.020  24621-24621/? W/dalvikvm﹕ Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/couchbase/touchdb/TDCollateJSON;
08-11 15:14:02.020  24621-24621/? D/AndroidRuntime﹕ Shutting down VM
08-11 15:14:02.020  24621-24621/? W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41581300)
08-11 15:14:02.020  24621-24621/? I/Process﹕ Sending signal. PID: 24621 SIG: 9
08-11 15:14:02.020  24621-24621/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.ExceptionInInitializerError
            at com.couchbase.lite.android.AndroidSQLiteStorageEngine.open(AndroidSQLiteStorageEngine.java:57)
            at com.couchbase.lite.Database.open(Database.java:977)
            at com.couchbase.lite.Manager.getDatabase(Manager.java:243)
            at self.hideki.issueandroid434.MainActivity.helloCBL(MainActivity.java:65)
            at self.hideki.issueandroid434.MainActivity.onCreate(MainActivity.java:34)
            at android.app.Activity.performCreate(Activity.java:5008)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
            at android.app.ActivityThread.access$600(ActivityThread.java:130)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.UnsatisfiedLinkError: Couldn't load com_couchbase_touchdb_TDCollateJSON: findLibrary returned null
            at java.lang.Runtime.loadLibrary(Runtime.java:365)
            at java.lang.System.loadLibrary(System.java:535)
            at com.couchbase.touchdb.TDCollateJSON.<clinit>(TDCollateJSON.java:43)
            at com.couchbase.lite.android.AndroidSQLiteStorageEngine.open(AndroidSQLiteStorageEngine.java:57)
            at com.couchbase.lite.Database.open(Database.java:977)
            at com.couchbase.lite.Manager.getDatabase(Manager.java:243)
            at self.hideki.issueandroid434.MainActivity.helloCBL(MainActivity.java:65)
            at self.hideki.issueandroid434.MainActivity.onCreate(MainActivity.java:34)
            at android.app.Activity.performCreate(Activity.java:5008)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
            at android.app.ActivityThread.access$600(ActivityThread.java:130)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
08-11 15:14:02.020      270-604/? W/ActivityManager﹕ Force finishing activity self.hideki.issueandroid434/.MainActivity
08-11 15:14:02.030     270-4986/? I/ActivityManager﹕ Process self.hideki.issueandroid434 (pid 24621) has died.
```

**Comment by hideki** [comment] 2015-08-12 00:06
https://developer.android.com/ndk/guides/abis.html
https://developer.android.com/ndk/guides/cpu-features.html

**Comment by hideki** [comment] 2015-08-12 00:57
Note to Self:

`android_getCpuFeatures()` method returns 0x1B (0001 1011) on Motorola XOOM.

AND operation with ANDROID_CPU_ARM_FEATURE_NEON 0x04 (0000 0100)  => 0x00. Need to remove ANDROID_CPU_ARM_FEATURE_NEON check from original code.

in cpu-features.h
```C
enum {
    ANDROID_CPU_ARM_FEATURE_ARMv7       = (1 << 0),
    ANDROID_CPU_ARM_FEATURE_VFPv3       = (1 << 1),
    ANDROID_CPU_ARM_FEATURE_NEON        = (1 << 2),
    ANDROID_CPU_ARM_FEATURE_LDREX_STREX = (1 << 3),
    ANDROID_CPU_ARM_FEATURE_VFPv2       = (1 << 4),
    ANDROID_CPU_ARM_FEATURE_VFP_D32     = (1 << 5),
    ANDROID_CPU_ARM_FEATURE_VFP_FP16    = (1 << 6),
    ANDROID_CPU_ARM_FEATURE_VFP_FMA     = (1 << 7),
    ANDROID_CPU_ARM_FEATURE_NEON_FMA    = (1 << 8),
    ANDROID_CPU_ARM_FEATURE_IDIV_ARM    = (1 << 9),
    ANDROID_CPU_ARM_FEATURE_IDIV_THUMB2 = (1 << 10),
    ANDROID_CPU_ARM_FEATURE_iWMMXt      = (1 << 11),
    ANDROID_CPU_ARM_FEATURE_AES         = (1 << 12),
    ANDROID_CPU_ARM_FEATURE_PMULL       = (1 << 13),
    ANDROID_CPU_ARM_FEATURE_SHA1        = (1 << 14),
    ANDROID_CPU_ARM_FEATURE_SHA2        = (1 << 15),
    ANDROID_CPU_ARM_FEATURE_CRC32       = (1 << 16),
};
```

https://developer.android.com/ndk/guides/abis.html
https://developer.android.com/ndk/guides/cpu-features.html

**Comment by hideki** [comment] 2015-08-12 01:37
Hi @Takhion and @drspaceboo,

I just posted `1.1.0-536` which includes the fix of this issue on couchbase maven repository.
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/1.1.0-536/

To download from couchbase maven repository, please add following line in root level build.gradel.
```
maven { url 'http://files.couchbase.com/maven2/' }
```

**Please be aware this is experimental build, not official release.**

1.1.0-516 is built from branch: https://github.com/couchbase/couchbase-lite-android/tree/feature/issue_434_jni_lib_load_failure. Except fix for this issue, all other codes are same with 1.1.0.

Hope this will fix native library loading issue.

Thanks,
Hideki

**Comment by Takhion** [comment] 2015-08-17 14:02
Hi @hideki,
I saw #649, do you have news about this?
We're releasing it today to production on a subset of users to see what happens, I'll keep you updated.

**Comment by hideki** [comment] 2015-08-17 16:32
Hi @Takhion,

> I saw #649, do you have news about this?

We did not merge the fix into the master yet. After we could verify if this fix can solve the problem, we will merge it. Actually we are waiting test results from you.

> We're releasing it today to production on a subset of users to see what happens, I'll keep you updated.

Thank you for all your helps.


Hideki

**Comment by hideki** [comment] 2015-08-22 01:18
Hi @Takhion and @drspaceboo,

Did you have a chance to check if the solution solve the problem? 

Have a nice weekend!

**Comment by Takhion** [comment] 2015-08-24 13:11
Hi @hideki,

I wanted to wait a week to be sure that the issue was fixed, and I was **just** about to tell you that everything was perfect, until this weekend when we received a new flood of errors like this:
```
android.database.sqlite.SQLiteException: no such collation sequence: REVID: , while compiling: SELECT revid, deleted, sequence, no_attachments, json FROM revs, docs WHERE docs.docid=? AND revs.doc_id=docs.doc_id and current=1 and deleted=0 ORDER BY revid DESC LIMIT 1
	at android.database.sqlite.SQLiteCompiledSql.native_compile(Native Method)
	at android.database.sqlite.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:68)
	at android.database.sqlite.SQLiteProgram.compileSql(SQLiteProgram.java:143)
	at android.database.sqlite.SQLiteProgram.compileAndbindAllArgs(SQLiteProgram.java:361)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:127)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:94)
	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:53)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:47)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1564)
	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1538)
	at com.couchbase.lite.android.AndroidSQLiteStorageEngine.rawQuery(SourceFile:128)
	at com.couchbase.lite.Database.getDocumentWithIDAndRev(SourceFile:1894)
	at com.couchbase.lite.Database.getExistingDocument(SourceFile:456)
```

:(

**Comment by hideki** [comment] 2015-08-24 16:27
Hi @Takhion,

Thank you for your report.

RevCollator is one of two native libraries. I applied same logic (rule) that is applied to JSONCollator to this library. I will review code again.

Question: Do you still observe following error message?
```
android.database.sqlite.SQLiteException: no such collation sequence: JSON: , while compiling: SELECT key, value, docid, revs.sequence, revid, json FROM maps, revs, docs WHERE maps.view_id=? AND key in (?) AND revs.sequence = maps.sequence AND docs.doc_id = revs.doc_id ORDER BY key LIMIT ? OFFSET ?
    at android.database.sqlite.SQLiteCompiledSql.native_compile(Native Method)
    at android.database.sqlite.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:68)
```

Thanks!
Hideki

**Comment by Takhion** [comment] 2015-08-25 21:16
Hi @hideki,

So far no, we have no crash report for the JSON collation, I'm not sure exactly what that means.

**Comment by zgramana** [comment] 2015-09-18 23:28
@Takhion are you still seeing reports of either JSON or REVID based exceptions after distributing the fix? If not, we'll close in 1 week.

**Comment by Takhion** [comment] 2015-09-20 20:43
@zgramana we're definitely still seeing reports for the REVID collation like in [this comment](https://github.com/couchbase/couchbase-lite-android/issues/434#issuecomment-134196967).

**Comment by hideki** [comment] 2016-09-15 23:30
We have no plan to support Nook with Android 4.0.x. Sorry.

**Closed** 2016-09-15 23:30 UTC
Labels: bug, testneeded, waffle:backlog
