### ISSUE TITLE
Docs not syncing

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-android#890] opened 2016-06-01 10:15 UTC
I've got a sync problem in my android app.  This user:

![screen shot 2016-06-01 at 11 03 26](https://cloud.githubusercontent.com/assets/5489469/15705763/8505786e-27e8-11e6-82a6-acac92b2c5d1.png)

Is not receiving the documents that it should.  For example, the following document isn't in its local CBL database.  I've checked by iterating over the `_all_docs` endpoint.

![screen shot 2016-06-01 at 11 04 59](https://cloud.githubusercontent.com/assets/5489469/15705822/c0be3cec-27e8-11e6-9fc0-b6d165b4a5e3.png)

The replication tasks seem fine:

![screen shot 2016-06-01 at 11 07 46](https://cloud.githubusercontent.com/assets/5489469/15705934/24805da0-27e9-11e6-9796-b9b7c254932f.png)

And the sync_gateway `_changes` feed for that user does have the document in it:

![screen shot 2016-06-01 at 11 12 40](https://cloud.githubusercontent.com/assets/5489469/15706105/d4eedf7c-27e9-11e6-9cdb-d3b4edc753f1.png)

And there are no errors in the logs. I'm using the latest code (1.2.1 and have also tried with 0.0.0-710).  Any idea what the problem is?

**Comment by jamiltz** [comment] 2016-06-01 12:18
Hi @npomfret - from looking at the screenshots, I can't tell. Can you share your sync function, an example JSON body of the document you would expect the CBL database to have and the user's profile document if there is one.

**Comment by npomfret** [comment] 2016-06-01 14:36
Here's the example doc: https://gist.github.com/npomfret/24587fab54369fceaa89f0f5cf3553b3

The sync function is a little involved, but the bit that deals with `accounts` is just this:

    var channels = [];

    ...
    
    if (doc.type === 'account') {
            if(!doc.user_id) {
                throw({forbidden: "Doc '" + doc.type + "' has no user_id"});
            }

            var publicChannelName = 'ch_public_' + doc.user_id;
            var privateChannelName = 'ch_private_' + doc.user_id;

            access(doc.friends.concat(doc.user_id), publicChannelName);
            access(doc.user_id, privateChannelName);
            access(doc.user_id, "public");

            channels.push(publicChannelName);
            channels.push(privateChannelName);
        }
    
    ...
    
    channels.forEach(function(channelName){
        channel(channelName);
    });

**Comment by jamiltz** [comment] 2016-06-12 15:08
From your screenshot, the document appears in the changes feed for that user so it doesn't seem to be an access rule issue. Is the pull replication pulling on specific channels by any chance? (the rest api can start replications that are bound to specific channels - see the last example on this page http://developer.couchbase.com/documentation/mobile/1.2/develop/references/couchbase-lite/rest-api/server/post-replicate/index.html).

If it isn't then I don't know what might be causing this issue. The most helpful information would be to provide sync gateway + couchbase lite logs when it happened. From there we can search for the `_id` and `rev` to see if the revision was pulled and then inserted in couchbase lite.

**Comment by npomfret** [comment] 2016-06-12 15:13
There's nothing that complicated going on regarding sync.

I'll make sure I grab the logs next time it happens.

**Comment by npomfret** [comment] 2016-06-15 16:40
I have another example, with sync-gateway and client logs.  This time the android client should have just 2 documents, but neither are appearing. So,

The sync-gateway changes feed for that user:

<img width="621" alt="screen shot 2016-06-15 at 17 08 52" src="https://cloud.githubusercontent.com/assets/5489469/16087708/e1088528-331b-11e6-863e-bfb6d0662500.png">

The in-app changes feed:

<img width="546" alt="screen shot 2016-06-15 at 17 09 29" src="https://cloud.githubusercontent.com/assets/5489469/16087730/f4dc66fa-331b-11e6-812f-233d296164d0.png">

The in app sync tasks:

<img width="494" alt="screen shot 2016-06-15 at 17 10 25" src="https://cloud.githubusercontent.com/assets/5489469/16087766/16450a18-331c-11e6-8530-b804a307ec8d.png">

The in-app db info:

<img width="427" alt="screen shot 2016-06-15 at 17 11 20" src="https://cloud.githubusercontent.com/assets/5489469/16087806/38b11542-331c-11e6-9245-ebeab5ded40d.png">

The user:

<img width="503" alt="screen shot 2016-06-15 at 17 25 13" src="https://cloud.githubusercontent.com/assets/5489469/16088254/2bbcf390-331e-11e6-8267-73ca6da925cb.png">

One of the docs that should have been syncd:

<img width="676" alt="screen shot 2016-06-15 at 17 26 37" src="https://cloud.githubusercontent.com/assets/5489469/16088293/5ad9ba78-331e-11e6-9da3-52acec68a59b.png">

The SG and app logs:

https://gist.github.com/npomfret/90a46442f92e69e70858096b696654bd

**Comment by npomfret** [comment] 2016-06-15 17:17
Ok, this is interesting.  I purged the one _deleted_ deleted doc and bounced the sync gateway.  As soon as I did this the client started syncing again.

**Comment by npomfret** [comment] 2016-06-18 09:15
I'm not seeing much (if any) logging from couchbaselite in logcat in android studio.  I've got no filters on and all the logging set to verbose.  Does it no do much logging?

**Comment by npomfret** [comment] 2016-06-18 09:30
Here are some logs from a client that refuses to sync

https://gist.github.com/npomfret/359c2418c2485e075b9c35c15ce620e5

**Comment by npomfret** [comment] 2016-06-18 10:24
Ok, I've stepped through in the debugger and have some more information.

The issue of canceled transactions described above happens in _SQLiteStore.java_, in method _forceInsert_ (line 1613).  In it there's a boolean _success_ that is not getting set the true on certain documents.

![screen shot 2016-06-18 at 11 14 40](https://cloud.githubusercontent.com/assets/5489469/16170292/2c3c9300-3546-11e6-8610-cdaf15ca558d.png)

In my debugger I can see that _localParentSequence_ and _sequence_ are not the same:

![screen shot 2016-06-18 at 11 17 29](https://cloud.githubusercontent.com/assets/5489469/16170319/e081706a-3546-11e6-8507-91ef3daa742a.png)

And so _success_ is false.  From there the transaction gets rolled back and the _storageExitedTransaction_ method in _Database.java_  is called.  This method looks like it throws away the rest of the changes:

![screen shot 2016-06-18 at 11 21 34](https://cloud.githubusercontent.com/assets/5489469/16170321/e6d89b78-3546-11e6-9bd0-0b9596839f6e.png)

...which I believe is why documents aren't getting syncd.

**Comment by npomfret** [comment] 2016-06-20 16:12
Is anyone available to help with this?  Is there any other information I could provide?

**Comment by npomfret** [comment] 2016-06-21 16:47
I'm using 0.0.0-710 - could that be causing it?

**Comment by hideki** [comment] 2016-06-21 16:57
@npomfret, This ticket is still in the Incoming queue. Could you please wait for a while.

**Comment by npomfret** [comment] 2016-06-21 17:15
Thanks @hideki - i've also tried with 0.0.0-746 but got the same problem.  Backing out to the prod release 1.2.1 seem to have made sync work again.  My reason for upgrading is that I need to be able to edit and index docs which isn't possible in the prod release.

**Comment by snej** [comment] 2016-06-29 17:01
This looks like a pretty serious bug, and we don't seem to have done any analysis of it. Should we bring this issue back into 1.3?

**Comment by npomfret** [comment] 2016-06-29 17:33
Let me know if you need any help reproducing. Although it wasn't hard, just try to re-sync a bunch of data.  Only a few docs come though and then it gives up pretty quickly and you see the _CANCEL TRANSACTION_ message.  

I thought initially it was because i had side-by-side databases (so the same doc in more than one db), but I think that was a red herring.

**Comment by snej** [comment] 2016-06-29 17:34
If you could reproduce this without using React-Native, that would be really helpful. Part of the reason this bug hasn't been given higher priority is that the React-Native integration is experimental/unsupported. But it sounds like your issue is not specific to that. Can you put your code into a PhoneGap container and run a replication there?

**Comment by npomfret** [comment] 2016-06-29 17:45
Don't know about phonegap but I can probably just write some java code  to reproduce.  I'm fairly sure its nothing to do with react-native.  All it does it invoke the REST API.

Has anyone tried sync with the latest code?  I've not tried the very latest build but 0.710 and 0.746 certainly had the problem.

**Comment by snej** [comment] 2016-06-29 17:53
Yes, we have a lot of unit tests and functional tests, including ones that cover sync. But sync is very complex and has all sorts of edge cases, so our tests are certainly not complete. We do try to add a unit test for each bug we fix, so the tests get more comprehensive over time.

**Comment by hideki** [comment] 2016-06-30 20:05
Hi @npomfret,
Could you please provide exact configuration and steps to reproduce this issue?
Thanks!

**Comment by npomfret** [comment] 2016-07-01 07:16
Its a fairly out-of-the-box configuration.  

Here's the [java code](https://github.com/couchbaselabs/react-native-couchbase-lite/tree/master/android/src/main/java/me/fraserxu/rncouchbaselite) - there isn't much.

I'm using couchbase-server-enterprise_4.5.0-beta-ubuntu14.04_amd64.deb and couchbase-sync-gateway-community_1.2.1-4_x86_64.deb

My app talks to CBL via the rest api. What else do you need to know?

I have a server with a bunch of docs.  My client sets up bi-directional sync when it starts.  After a few documents get delivered it seems to reliably stop after a few and I see the _CANCEL TRANSACTION_ message in the logs.

I've not tried with the lasted build - I'll see if I can reproduce it still.

**Comment by hideki** [comment] 2016-07-01 07:52
I wonder if this issue is same with https://github.com/couchbase/couchbase-lite-java-core/issues/1317 which issue also shows 'CANCEL transaction'.

**Comment by npomfret** [comment] 2016-07-01 17:52
Looks very similar.  I'm going to see if its still reproducible. What version should I use?

**Comment by hideki** [comment] 2016-07-01 18:18
Please install CBL from Couchbase custom maven repo?
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/1.3.0-7/

**Comment by sethrosetter** [comment] 2016-07-02 00:58
@npomfret Working with @hideki, I'm pretty certain I hit this while writing a test a test. I used http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/1.3.0-8/ and it resolved the issue for me. Can you try out this build?

**Comment by hideki** [comment] 2016-07-02 00:59
I will close this ticket. If you still encounter with latest build, please reopen this.

**Closed** 2016-07-02 00:59 UTC
Labels: bug, react-native, ready, release-prep, reproduce/investigate

**Comment by npomfret** [comment] 2016-07-02 08:52
Thank you so much - I tried 1.3.0-8 and it works.  Can sync and edit documents!!

**Comment by hideki** [comment] 2016-07-02 18:35
It is great to hear 1.3.0-8 works well with your environment.
