### ISSUE TITLE
android query view via REST API still returns multiple doc revisions of one document on Couchbase lite 1.3

### ISSUE THREAD

**Issue by HanzhiDou** [couchbase/couchbase-lite-android#956] opened 2016-08-09 05:38 UTC
Hi,

I build a cordova app using Couchbase-Lite-PhoneGap-Plugin and have same problem as described in the following closed issues in 1.2.1:

Querying local CBLite via REST API returns all doc revisions (not just current rev):
https://github.com/couchbase/couchbase-lite-java-core/issues/1098

Then I upgraded the plugin to 1.3.0 released few days ago, unfortunately the problem is still there.

My view definition is quite simple, and it works very well on iOS:

`            mainproperties_by_uid_workoutid: {
                map: [
                    "function(doc) { if (doc.t && doc.t === 'S' && doc.u && doc.w && doc.edt && doc.stats && doc.stats.d > 0)",
                    " { emit([doc.u, doc.w], { userId: doc.u, workoutId: doc.w, elementDocType: doc.edt, sportType: doc.st, ",
                    " title: doc.tl, planId: doc.pid, goalCategory: doc.gc, goalId: doc.gid, categories: doc.cats, tags: doc.tags, ",
                    " notes: doc.notes, map: doc.map, mapOssUrl: doc.mapOssUrl, stats: doc.stats });",
                    " }",
                    "}"
                ].join('')
            },`

any quick fix or workaround?

Thanks!

**Comment by pasin** [comment] 2016-08-09 18:22
I'm wondering if the issue is related to a race condition that has been recently fixed but not be included in 1.3.

@HanzhiDou do you happen to have at least 2 query requests to the same views at the same time?

**Comment by HanzhiDou** [comment] 2016-08-10 01:42
My app logic: the same doc will be updated several times asynchronously, 409 conflicts will happen sometimes. In case of conflict, it will query view to get the latest _id and _rev of the doc and assign to a new doc which has new info for updating again until the  doc update operation succeed, so both query request and update request might happen at the same time.

I guess it is the same issue and hope so ;-)

**Comment by lucapale** [comment] 2016-08-11 16:47
Same issue here. The view result shows many revisions of the same document, plus includes also the deleted documents (already commented in another issue).
https://www.dropbox.com/s/zj7y4uqyg59tvxw/Schermata%202016-08-11%20alle%2018.25.56.png?dl=0
https://www.dropbox.com/s/94q4v7frz7mw25n/Schermata%202016-08-11%20alle%2018.46.31.png?dl=0

**Comment by sethrosetter** [comment] 2016-08-12 23:02
@pasin. Can we sync up about adding a functional test for this?

**Comment by pasin** [comment] 2016-08-18 00:32
I couldn't reproduce the issue. I have have 3 views setup on the same design doc. I have a loop to update 20 docs simultaneously 1000 times. At the same time, I have a loop that query to one the 3 view that reflect those changes 1000 times.

**Comment by pasin** [comment] 2016-08-18 00:32
@HanzhiDou When you updated to 1.3.0, did you also clear the database before testing?

**Comment by HanzhiDou** [comment] 2016-08-19 00:57
@pasin  I tried both:
- remove my app from phone and reinstalled it, means the database is recreated.  
- delete design doc and recreate it.

The problem happens in both situations, and it happens to me very often, the old wrong docs are still there when the design doc is recreated, so the problem might be not only related to views.

More information: 
- I have multiple views in one design doc
- my app is related to location recording, it will calc stats data and save it several times in background when data changes (not every change),  seems the problem will not occur when the app running in background, it only happens when use open the app, stop the recording  and triggered data updates (manually and automatic triggered to add more information to save again), means the problem might only happens in app running in foreground.
- same code works very well for iOS.

Unfortunately I am not sure that I could make a small app to reproduce it, i will think about it.

**Comment by pasin** [comment] 2016-08-19 06:29
@HanzhiDou 

Can you post the query result and the json of the doc that has the issue? Also you are using SQLite not ForestDB, right?

**Comment by pasin** [comment] 2016-08-23 03:34
@HanzhiDou any updates? We are closing down the 1.3.1 release. It will be great if you could provide more information as requested above asap. Please let me know.

**Comment by HanzhiDou** [comment] 2016-08-28 13:06
very sorry for the late reply. i am hooked by other things last week and did not get any chance to check this out.

> Are you using SQLite not ForestDB?

SQLite.

View result for same document:
_id:b4511f32-c505-452f-9ce1-e1dfab53035b, _rev: 4-e528571f0e5d7ed749ba6b2d93efe220
_id:b4511f32-c505-452f-9ce1-e1dfab53035b, _rev: 6-0089119424a799ed7b6d0c430500ff30

I tried several hours today to find more information,  and finally got new findings: I changed one view definition,  then delete the design doc and recreate it using same design doc name,  the views in the design doc still using old one, even I tried to compact the database, old views are still used in new created design doc. I have to change the view name to make the view change take effects. 

After the view changes,  the duplicated docs are gone, so my earlier findings are not correct, rebuild the view can really make previous duplicated docs in cbl 1.2.1 disappear. however other views whose names are not changed in the new design doc still returns duplicated old docs.

For new docs, query by new renamed view will not return duplicated docs.

So far conclusion:
- duplicated docs problem seems already fixed in 1.3
- new problem is that changing view definition need also change view name, if change the view name from 'a' to 'b' to 'c', then 'a' again with new definition, old definition in earlier 'a' is still used.

Another problem: after upgrade cbl to 1.3, the sync with sync gateway 1.1.1 does not work anymore:

`W/Sync: com.couchbase.lite.replicator.ReplicationInternal$11@d0663d8: error getting remote checkpoint
com.couchbase.lite.replicator.RemoteRequestResponseException: Unauthorized
  at com.couchbase.lite.replicator.RemoteRequest.executeRequest(RemoteRequest.java:265)
  at com.couchbase.lite.replicator.RemoteRequest.execute(RemoteRequest.java:165)
  at com.couchbase.lite.replicator.RemoteRequest.run(RemoteRequest.java:105)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
  at java.lang.Thread.run(Thread.java:833)
W/Sync: PullerInternal{unknown, pull, 217bd}: Progress: set error = com.couchbase.lite.replicator.RemoteRequestResponseException: Unauthorized
W/RemoteRequest: com.couchbase.lite.replicator.RemoteRequest {GET, http://<ip>/sg/<db>/_local/217bd8467805910e24b487a3e7e900a9aa8e2bf4}: aborting request: okhttp3.RealCall@f348331
I/chromium: [INFO:CONSOLE(8)] "sync response: [{"session_id":"repl013"},{"session_id":"repl014"}]", source: file:///android_asset/www/app.js (8)
`
One 500 error is got when do syncing.

My question: do we need also upgraded sync gateway to 1.3 to make sync work?

Thanks!

**Comment by pasin** [comment] 2016-08-29 16:05
@HanzhiDou Thanks a lot for the info.

> duplicated docs problem seems already fixed in 1.3

Glad to hear this so I will close this issue.

> new problem is that changing view definition need also change view name, if change the view name from 'a' to 'b' to 'c', then 'a' again with new definition, old definition in earlier 'a' is still used.

I believe this is expected BUT if the designed doc gets deleted and recreated with the same name, I understand that the index should be deleted as well. I have created a new issue: https://github.com/couchbase/couchbase-lite-java-core/issues/1413.

> Another problem: after upgrade cbl to 1.3, the sync with sync gateway 1.1.1 does not work anymore:

I have created a new issue: https://github.com/couchbase/couchbase-lite-java-core/issues/1414.

**Closed by pasin** 2016-08-29 16:05 UTC
Labels: in progress, needsmoreinfo, reproduce/investigate

**Comment by pasin** [comment] 2016-08-29 21:26
@HanzhiDou I have checked and CBL 1.3 should work with SGW 1.1.1. From the error above, I think there is an issue with authentication. How do you setup the authenticator?

**Comment by HanzhiDou** [comment] 2016-08-30 01:17
@pasin I use so called "Custom Authentication": use an App Server to create user sessions on the Sync Gateway Admin REST API and transfer the session info back to mobile client, there is also a nginx proxy server between mobile and sync gateway. 

All works well before upgraded CBL to 1.3, from the log we can see the sync session is created on cbl.

**Comment by pasin** [comment] 2016-08-30 01:20
@HanzhiDou how do you setup the session cookie to the replicator? Would it be possible to show the code snippet?

**Comment by HanzhiDou** [comment] 2016-08-30 01:46
@pasin  some related code:

`
    pullReplicate: function (remoteDb, localDb, continuous, channels) {
        var channels = channels || ['*'];
        var continuous = continuous || false;

        var source = {
            headers: {
                Cookie: this.getSyncCredential(remoteDb).cookie_name + '=' + this.getSyncCredential(remoteDb).session_id
            },
            url: this.getSyncGatewayBaseUrl() + remoteDb
        };

        return this.replicate(source, localDb, remoteDb, continuous, false, channels);
    }
`

` pushReplicate: function (remoteDb, localDb, continuous, pushFilter) {
        var continuous = continuous || false;

        var target = {
            headers: {
                Cookie: this.getSyncCredential(remoteDb).cookie_name + '=' + this.getSyncCredential(remoteDb).session_id
            },
            url: this.getSyncGatewayBaseUrl() + remoteDb
        };

        return this.replicate(localDb, target, remoteDb, continuous, false, null, pushFilter);
    },`

`     
 replicate: function (source, target, remoteDb, continuous, cancel, channels, pushFilter) {
   var requestData = {
            continuous: continuous,
            source: source,
            target: target,
            create_target: false
        };

        if (cancel) {
            requestData.cancel = true;
        }

        if (channels) {
            requestData.filter = 'sync_gateway/bychannel';
            requestData.query_params = {
                "channels": channels.join(',')
            };
        }

        if (pushFilter) {
            requestData.filter = pushFilter.filter;
            requestData.query_params = pushFilter.query_params;
        }
      
        document.cookie = me.getSyncCredential(remoteDb).cookie_name + ':' + me.getSyncCredential(remoteDb).session_id;

        ajaxRequest({
            url: window.cbliteUrl + '_replicate',
            method: 'POST',
            xhr2: false,
            disableCaching: false,
            withCredentials: true,
            useDefaultXhrHeader: false,
            jsonData: requestData,
            headers: {
//                Cookie: me.getSyncCredential(remoteDb).cookie_name + '=' + me.getSyncCredential(remoteDb).session_id
            },
            timeout: 30000,
            success: function (response) {
            },
            failure: function (response) {
            }
        });
}
`

Due to one error on android, I changed the code to use document.cookie instead of Cookie header on Android.
