### ISSUE TITLE
Using LiteListener with Couchbase mobile 2.0

### ISSUE THREAD

**Issue by nishantpardamwar** [couchbase/couchbase-lite-android#1426] opened 2017-10-29 09:48 UTC
I'm was syncing the database between multiple android devices (P2P) without central server, for this i was using Couchbase v1.4 with lite listener but im trying to migrate to Couchbase 2.0 but i couldn't find How to use LiteListener with couchbase 2.0 or is there any other way to achieve the same ?

**Comment by hideki** [comment] 2017-10-29 19:39
Hi @nishantpardamwar, Peer to Peer feature is in our 2.x roadmap. But we did not start to implement it yet. Meanwhile, Please use CBL 1.x for P2P functionality.

**Comment by NitzDKoder** [comment] 2017-11-02 11:04
@hideki We need this in 2.0.0. Pls confirm if it will be available.? Currently our production app is with CBL 1.4 and heavily uses Listener.

Plan is upgrade to CBL 2.0.

**Comment by NitzDKoder** [comment] 2017-11-02 11:04
+1

**Comment by ddash1** [comment] 2017-11-02 16:12
@ssmotra 
Can you please help clarify if this is 2.0 candidate or not?

**Comment by nishantpardamwar** [comment] 2017-11-03 08:18
@NitzDKoder , @ddash1  guys @hideki  already tagged it, it will be available with the release of 2.1.0

**Comment by hideki** [comment] 2017-11-03 17:47
Hi All,

I just set `2.1.0` milestone as a placeholder (Indicates after 2.0.0). I am sorry for confusing you.
We are still discussing the 2.x architecture for Peer to Peer, and how CBL 2.x supports JavaScript (REST or direct binding).

Thanks,
Hideki

**Comment by djpongh** [comment] 2018-04-13 21:10
duplicate of #1678

**Closed by djpongh** 2018-04-13 21:10 UTC
Labels: backlog, enhancement, pmin
