### ISSUE TITLE
Runtime exception while migrating db from 1.0.0 -> 1.3.1

### ISSUE THREAD

**Issue by welniak** [couchbase/couchbase-lite-android#1023] opened 2016-10-20 15:54 UTC
Hi, we're using quite an outdated version of cbl (1.0.0) and recently started testing the most recent release (1.3.1). 

During the db migration, when Manager instance is created and the lib tries to migrate a document with an attachment, cbl throws a Runtime Exception (works fine if none of the migrated docs has an attachment).

Here are the last logs from the lib along with the error message from the stack trace 

`W/Database: No pending attachment for getDigest: sha1-zgPXo/erDm42FMuSQx265KQ6xrc=`
`V/Database: main CANCEL transaction (level 0)`
..
`com.android.tools.fd.runtime.BootstrapApplication: java.lang.RuntimeException: Database upgrade failed for: <db_name>`

It seems that the Database.pendingAttachmentsByDigest is always empty in our case when reaching Database.installAttachment method. 

Is there any scenario when this is an expected behaviour? The docs seem to be fine (not corrupted) and replicated to CouchDB, along with the attachment.

**Comment by hideki** [comment] 2016-10-20 18:31
Hi @welniak,
Do you migrate CBL from `1.0.0`? or `1.0.4`?

**Comment by welniak** [comment] 2016-10-21 09:36
Hi @hideki, I double checked and we're actually using at the moment a fork of cbl-android from 1.0.0 release branch and a fork of cbl-java-core 1.0.2 with couple of later commits merged.

**Comment by hideki** [comment] 2016-10-28 19:16
Hi @welniak,

Question. I am writing sample app to reproduce this issue. But CBL 1.0.0-1.0.2 does not work with Android M (6.0.1) because of following error. Error that I am facing was fixed with 1.0.3. I am wondering what Android version you are using for your test with CBL1.0.2? or Your forked version has fix of this?

```
10-28 12:10:31.305 25520-25520/hideki.self.issue1023 E/AndroidRuntime: FATAL EXCEPTION: main
Process: hideki.self.issue1023, PID: 25520
java.lang.NoSuchFieldError: no "I" field "mConnectionPtr" in class "Landroid/database/sqlite/SQLiteConnection;" or its superclasses
   at com.couchbase.touchdb.TDCollateJSON.nativeRegisterCustomCollators(Native Method)
   at com.couchbase.touchdb.TDCollateJSON.registerCustomCollators(TDCollateJSON.java:11)
   at com.couchbase.lite.android.AndroidSQLiteStorageEngine.open(AndroidSQLiteStorageEngine.java:46)
   at com.couchbase.lite.Database.open(Database.java:911)
   at com.couchbase.lite.Manager.getDatabase(Manager.java:227)
   at hideki.self.issue1023.MainActivity.initDB(MainActivity.java:32)
   at hideki.self.issue1023.MainActivity.onStart(MainActivity.java:51)
   at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
   at android.app.Activity.performStart(Activity.java:6268)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
   at android.app.ActivityThread.-wrap11(ActivityThread.java)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:148)
   at android.app.ActivityThread.main(ActivityThread.java:5417)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by hideki** [comment] 2016-10-28 20:19
Note to Self:

This issue is reproducible with following sample app.
https://github.com/hideki/cbl-java-tests/tree/master/Issue1023

Error message:
```
10-28 16:05:34.208 3719-3719/? W/Database: No pending attachment for getDigest: sha1-LmsoqJJ6LOn4YS60pYnvrKbBd64=
10-28 16:05:34.214 3719-3719/? D/AndroidRuntime: Shutting down VM
 
 
 --------- beginning of crash
10-28 16:05:34.214 3719-3719/? E/AndroidRuntime: FATAL EXCEPTION: main
 Process: hideki.self.issue1023, PID: 3719
 java.lang.RuntimeException: Unable to start activity ComponentInfo{hideki.self.issue1023/hideki.self.issue1023.MainActivity}: java.lang.RuntimeException: Database upgrade failed for: db
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
     at android.app.ActivityThread.-wrap11(ActivityThread.java)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:148)
     at android.app.ActivityThread.main(ActivityThread.java:5417)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
  Caused by: java.lang.RuntimeException: Database upgrade failed for: db
     at com.couchbase.lite.Manager.upgradeOldDatabaseFiles(Manager.java:799)
     at com.couchbase.lite.Manager.<init>(Manager.java:130)
     at hideki.self.issue1023.MainActivity.initDB(MainActivity.java:87)
     at hideki.self.issue1023.MainActivity.onStart(MainActivity.java:44)
     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
     at android.app.Activity.performStart(Activity.java:6253)
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
     at android.os.Handler.dispatchMessage(Handler.java:102) 
     at android.os.Looper.loop(Looper.java:148) 
     at android.app.ActivityThread.main(ActivityThread.java:5417) 
     at java.lang.reflect.Method.invoke(Native Method) 
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
10-28 16:05:34.215 682-1164/system_process W/ActivityManager:   Force finishing activity hideki.self.issue1023/.MainActivity
```

**Comment by hideki** [comment] 2016-10-28 22:43
Note to Self:
It seems stored filename's lowercase-uppercase different causes migration failure.
1.0.x -> lowercase
1.3.1 -> uppercase

**Comment by hideki** [comment] 2016-10-28 23:29
PR: https://github.com/couchbase/couchbase-lite-java-core/pull/1505

**Comment by hideki** [comment] 2016-10-29 04:00
Hi @welniak,
Can you test migration scenario with 1.3.1-89 which is built from master branch?
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/1.3.1-89/
Thanks!
Hideki

**Closed** 2016-10-29 04:02 UTC
Labels: P1: high, reproduce/investigate

**Comment by welniak** [comment] 2016-11-02 12:32
Hi @hideki,

I built cbl-java-core from master branch today (I already had to create a fork of 1.3.1 release due to other issue, so didn't use maven, I merged master into our current branch instead), the problem seems to be gone now, app doesn't crash during the migration anymore.

Thanks
