### ISSUE TITLE
liteserv-project: PullReplication over ReSTful API failed with out of memory error

### ISSUE THREAD

**Issue by naka-mura** [couchbase/couchbase-lite-android#532] opened 2015-02-23 13:44 UTC
i am starting a pull replication from my WebView Application over the ReSTful API of the liteserv-project.

The replication starts without any problems, but after a while (after 100 - 2000 documents) it stopped with an 'out of memory' exception (see below). 
The source couchdb containts about 20000 JSON Documents without Attachments.

I am working with the actual Versions of the liteserve-Project (e.g. CBL 1.0.3.)

Thanks in advance for your help with best regards
stefan

02-23 12:57:55.484    3080-3112/com.couchbase.liteservandroid D/dalvikvm﹕ GC_FOR_ALLOC freed 81K, 25% free 37071K/49159K, paused 199ms
02-23 12:57:55.687    3080-3112/com.couchbase.liteservandroid D/dalvikvm﹕ GC_FOR_ALLOC freed 76K, 25% free 37089K/49159K, paused 197ms

02-23 12:57:55.687    3080-3112/com.couchbase.liteservandroid I/dalvikvm-heap﹕ Forcing collection of SoftReferences for 9782-byte allocation
02-23 12:57:55.898    3080-3112/com.couchbase.liteservandroid D/dalvikvm﹕ GC_BEFORE_OOM freed 24K, 25% free 37065K/49159K, paused 212ms
02-23 12:57:55.898    3080-3112/com.couchbase.liteservandroid E/dalvikvm-heap﹕ Out of memory on a 9782-byte allocation.
02-23 12:57:55.898    3080-3112/com.couchbase.liteservandroid I/dalvikvm﹕ "CBLManagerWorkExecutor" prio=5 tid=23 RUNNABLE
02-23 12:57:55.898    3080-3112/com.couchbase.liteservandroid I/dalvikvm﹕ | group="TJWS threads" sCount=0 dsCount=0 obj=0x411543d0 self=0x9a6278
02-23 12:57:55.898    3080-3112/com.couchbase.liteservandroid I/dalvikvm﹕ | sysTid=3112 nice=0 sched=0/0 cgrp=default handle=10116584
02-23 12:57:55.898    3080-3112/com.couchbase.liteservandroid I/dalvikvm﹕ | schedstat=( 0 0 0 ) utm=20285 stm=378 core=1
02-23 12:57:55.898    3080-3112/com.couchbase.liteservandroid I/dalvikvm﹕ at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:~94)
02-23 12:57:55.898    3080-3112/com.couchbase.liteservandroid I/dalvikvm﹕ at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:145)
02-23 12:57:55.898    3080-3112/com.couchbase.liteservandroid I/dalvikvm﹕ at java.lang.StringBuilder.append(StringBuilder.java:216)
02-23 12:57:55.898    3080-3112/com.couchbase.liteservandroid I/dalvikvm﹕ at com.couchbase.lite.Database.joinQuoted(Database.java:4281)
02-23 12:57:55.898    3080-3112/com.couchbase.liteservandroid I/dalvikvm﹕ at com.couchbase.lite.Database.findMissingRevisions(Database.java:4301)
02-23 12:57:55.898    3080-3112/com.couchbase.liteservandroid I/dalvikvm﹕ at com.couchbase.lite.replicator.PullerInternal.processInbox(PullerInternal.java:161)
02-23 12:57:55.898    3080-3112/com.couchbase.liteservandroid I/dalvikvm﹕ at com.couchbase.lite.replicator.ReplicationInternal$2.process(ReplicationInternal.java:288)
02-23 12:57:55.898    3080-3112/com.couchbase.liteservandroid I/dalvikvm﹕ at com.couchbase.lite.support.Batcher.processNow(Batcher.java:221)
02-23 12:57:55.898    3080-3112/com.couchbase.liteservandroid I/dalvikvm﹕ at com.couchbase.lite.support.Batcher.access$100(Batcher.java:23)
02-23 12:57:55.898    3080-3112/com.couchbase.liteservandroid I/dalvikvm﹕ at com.couchbase.lite.support.Batcher$1.run(Batcher.java:44)
02-23 12:57:55.898    3080-3112/com.couchbase.liteservandroid I/dalvikvm﹕ at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
02-23 12:57:55.898    3080-3112/com.couchbase.liteservandroid I/dalvikvm﹕ at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
02-23 12:57:55.898    3080-3112/com.couchbase.liteservandroid I/dalvikvm﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:137)
02-23 12:57:55.898    3080-3112/com.couchbase.liteservandroid I/dalvikvm﹕ at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
02-23 12:57:55.898    3080-3112/com.couchbase.liteservandroid I/dalvikvm﹕ at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
02-23 12:57:55.898    3080-3112/com.couchbase.liteservandroid I/dalvikvm﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
02-23 12:57:55.898    3080-3112/com.couchbase.liteservandroid I/dalvikvm﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
02-23 12:57:55.898    3080-3112/com.couchbase.liteservandroid I/dalvikvm﹕ at java.lang.Thread.run(Thread.java:856)
02-23 12:57:55.898    3080-3112/com.couchbase.liteservandroid I/dalvikvm﹕ [ 02-23 12:57:56.117  3080:0xc31 D/dalvikvm ]
    GC_FOR_ALLOC freed 26K, 25% free 37085K/49159K, paused 202ms
02-23 12:57:56.328    3080-3119/com.couchbase.liteservandroid D/dalvikvm﹕ GC_FOR_ALLOC freed 7K, 25% free 37105K/49159K, paused 200ms
02-23 12:57:56.328    3080-3119/com.couchbase.liteservandroid I/dalvikvm-heap﹕ Forcing collection of SoftReferences for 8208-byte allocation
02-23 12:57:56.539    3080-3119/com.couchbase.liteservandroid D/dalvikvm﹕ GC_BEFORE_OOM freed <1K, 25% free 37105K/49159K, paused 212ms
02-23 12:57:56.539    3080-3119/com.couchbase.liteservandroid E/dalvikvm-heap﹕ Out of memory on a 8208-byte allocation.
02-23 12:57:56.539    3080-3119/com.couchbase.liteservandroid I/dalvikvm﹕ "CBLRequestWorker-e758c-1" prio=5 tid=28 RUNNABLE
02-23 12:57:56.539    3080-3119/com.couchbase.liteservandroid I/dalvikvm﹕ | group="TJWS threads" sCount=0 dsCount=0 obj=0x435bc6a0 self=0x96ff98
02-23 12:57:56.539    3080-3119/com.couchbase.liteservandroid I/dalvikvm﹕ | sysTid=3119 nice=0 sched=0/0 cgrp=default handle=9871384
02-23 12:57:56.539    3080-3119/com.couchbase.liteservandroid I/dalvikvm﹕ | schedstat=( 0 0 0 ) utm=714 stm=14 core=1
02-23 12:57:56.539    3080-3119/com.couchbase.liteservandroid I/dalvikvm﹕ at org.apache.http.util.ByteArrayBuffer.<init>(ByteArrayBuffer.java:~53)
02-23 12:57:56.539    3080-3119/com.couchbase.liteservandroid I/dalvikvm﹕ at org.apache.http.impl.io.AbstractSessionInputBuffer.init(AbstractSessionInputBuffer.java:82)
02-23 12:57:56.546    3080-3119/com.couchbase.liteservandroid I/dalvikvm﹕ at org.apache.http.impl.io.SocketInputBuffer.<init>(SocketInputBuffer.java:70)
02-23 12:57:56.546    3080-3119/com.couchbase.liteservandroid I/dalvikvm﹕ at org.apache.http.impl.SocketHttpClientConnection.createSessionInputBuffer(SocketHttpClientConnection.java:83)
02-23 12:57:56.546    3080-3119/com.couchbase.liteservandroid I/dalvikvm﹕ at org.apache.http.impl.conn.DefaultClientConnection.createSessionInputBuffer(DefaultClientConnection.java:170)
02-23 12:57:56.546    3080-3119/com.couchbase.liteservandroid I/dalvikvm﹕ at org.apache.http.impl.SocketHttpClientConnection.bind(SocketHttpClientConnection.java:106)
02-23 12:57:56.546    3080-3119/com.couchbase.liteservandroid I/dalvikvm﹕ at org.apache.http.impl.conn.DefaultClientConnection.openCompleted(DefaultClientConnection.java:129)
02-23 12:57:56.546    3080-3119/com.couchbase.liteservandroid I/dalvikvm﹕ at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:174)
02-23 12:57:56.546    3080-3119/com.couchbase.liteservandroid I/dalvikvm﹕ at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
02-23 12:57:56.546    3080-3119/com.couchbase.liteservandroid I/dalvikvm﹕ at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
02-23 12:57:56.546    3080-3119/com.couchbase.liteservandroid I/dalvikvm﹕ at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
02-23 12:57:56.546    3080-3119/com.couchbase.liteservandroid I/dalvikvm﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
02-23 12:57:56.546    3080-3119/com.couchbase.liteservandroid I/dalvikvm﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
02-23 12:57:56.546    3080-3119/com.couchbase.liteservandroid I/dalvikvm﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
02-23 12:57:56.546    3080-3119/com.couchbase.liteservandroid I/dalvikvm﹕ at com.couchbase.lite.support.RemoteMultipartDownloaderRequest.executeRequest(RemoteMultipartDownloaderRequest.java:65)
02-23 12:57:56.546    3080-3119/com.couchbase.liteservandroid I/dalvikvm﹕ at com.couchbase.lite.support.RemoteMultipartDownloaderRequest.run(RemoteMultipartDownloaderRequest.java:50)
02-23 12:57:56.546    3080-3119/com.couchbase.liteservandroid I/dalvikvm﹕ at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
02-23 12:57:56.546    3080-3119/com.couchbase.liteservandroid I/dalvikvm﹕ at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
02-23 12:57:56.546    3080-3119/com.couchbase.liteservandroid I/dalvikvm﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:137)
02-23 12:57:56.546    3080-3119/com.couchbase.liteservandroid I/dalvikvm﹕ at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
02-23 12:57:56.546    3080-3119/com.couchbase.liteservandroid I/dalvikvm﹕ at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
02-23 12:57:56.546    3080-3119/com.couchbase.liteservandroid I/dalvikvm﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
02-23 12:57:56.546    3080-3119/com.couchbase.liteservandroid I/dalvikvm﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
02-23 12:57:56.546    3080-3119/com.couchbase.liteservandroid I/dalvikvm﹕ at java.lang.Thread.run(Thread.java:856)
02-23 12:57:56.546    3080-3119/com.couchbase.liteservandroid I/dalvikvm﹕ [ 02-23 12:57:56.757  3080:0xc35 D/dalvikvm ]

**Comment by naka-mura** [comment] 2015-02-23 15:35
The problem i described above is when i start a one shot replication.
If i start a continues pull replication, the replication is running longer, but it becomes slower and slower till the process died.

**Comment by tleyden** [comment] 2015-03-05 18:59
Closing as duplicate of https://github.com/couchbase/couchbase-lite-java-core/issues/447

**Closed by tleyden** 2015-03-05 18:59 UTC
