### ISSUE TITLE
CB Lite Replication not pulling documents post upgrade on Mac Sierra

### ISSUE THREAD

**Issue by rizwanbpatel** [couchbase/couchbase-lite-android#1684] opened 2018-03-25 06:17 UTC
**Environment**:

- MacOs Sierra : 10.13.2
- CB : Enterprise Edition 5.0.1 build 5003 
- Docker : Version 17.12.0-ce-mac47 (21805)
- couchbase-lite-java-listener:1.4.1
- couchbase-lite-java-javascript:1.4.1
- CB - Sync Gateway 
  - Couchbase Sync Gateway/1.5.1
  - Docker image: couchbase/sync-gateway@sha256:8c511360684e813b4602c2c9951bb407a7d16a53a613c13503b0d62d6bd6a443

**Issue**
- Uploaded document with the REST endpoints via Postman to Couchbase-sync. 
- Documents synced with the Couchbase server deployed locally.
- These documents are not getting pulled on the Mobile App.

**Sync Gateway**
- DB Details on Browser URL - http://192.168.1.6:4984/db/

> {"committed_update_seq":24,"compact_running":false,"db_name":"db","disk_format_version":0,"instance_start_time":1521953925571225,"purge_seq":0,"state":"Online","update_seq":24}

- Document present on the gateway as 
http://192.168.1.6:4985/_admin/db/db/documents/0ea34e998f1e96270274f76da56190ac

> {
  "baseRate": 12,
  "customId": 3,
  "details": "Net Item of Pizza",
  "itemImageUrl": "3",
  "itemName": "Regular Veggie",
  "type": "items",
  "_rev": "1-64c95ae66cfa4dd2d6220e8183823740",
  "_id": "0ea34e998f1e96270274f76da56190ac"
}

**Code**
- Created a Database View
```
View view = database.getView("app/items");
        if (view.getMap() == null) {
            view.setMap(new Mapper() {
                @Override
                public void map(Map<String, Object> document, Emitter emitter) {
                    if (document.get("type").equals("items")) {
                        emitter.emit(document.get("_id"), null);
                    }
                }
            }, "1");
        }
        Query itemQ = view.createQuery();
        return itemQ;
```
- Above returning me 0 records.

**Gist link**
--Working with previously installed emulator
[Working Logs](https://gist.github.com/rizwanbpatel/ee0603cc8db753d5d52b50d95425e6b2)
-- Not working logs
[Non-Working Logs : **Issue**](https://gist.github.com/rizwanbpatel/ee0603cc8db753d5d52b50d95425e6b2)

**Comment by hideki** [comment] 2018-03-25 15:39
From Non-Working Logs: Issue
- The Replicator immediately entered IDLE state, it indicates no changes on the server. I wonder if the document is successfully created/updated through Sync Gateway? Can you check?
```
03-25 12:05:32.642 3180-3336/com.atoz.dhobi V/Sync: serverVersion: Couchbase Sync Gateway/1.5.1
03-25 12:05:32.642 3180-3336/com.atoz.dhobi V/Sync: com.couchbase.lite.replicator.ReplicationInternal$11@26eb0b88: Remote checkpoint does not exist on server yet: 26e5f7ea65528d74e5884d1f1d10913ae6b625f1
03-25 12:05:32.642 3180-3336/com.atoz.dhobi D/Sync: com.couchbase.lite.replicator.ReplicationInternal$11@26eb0b88: lastSequence mismatch: I had: null, remote had: null
03-25 12:05:32.642 3180-3336/com.atoz.dhobi V/Sync: submit startReplicating()
03-25 12:05:32.643 3180-3336/com.atoz.dhobi V/Sync: com.couchbase.lite.replicator.RemoteRequest {GET, http://192.168.1.6:4984/db/_local/26e5f7ea65528d74e5884d1f1d10913ae6b625f1}: RemoteRequest execute() finished, url: http://192.168.1.6:4984/db/_local/26e5f7ea65528d74e5884d1f1d10913ae6b625f1
03-25 12:05:32.643 3180-3334/com.atoz.dhobi V/Sync: start startReplicating()
03-25 12:05:32.650 3180-3338/com.atoz.dhobi V/Sync: serverVersion: Couchbase Sync Gateway/1.5.1
03-25 12:05:32.650 3180-3338/com.atoz.dhobi D/Sync: com.couchbase.lite.replicator.ReplicationInternal$11@b43a146: Replicating from lastSequence=196
03-25 12:05:32.650 3180-3338/com.atoz.dhobi D/Sync: PusherInternal{http://192.168.1.6:4984/db, push, 93afe}: beginReplicating() called
03-25 12:05:32.655 3180-3338/com.atoz.dhobi D/Sync: PusherInternal{http://192.168.1.6:4984/db, push, 93afe}: Getting changes since 196
03-25 12:05:32.657 3180-3338/com.atoz.dhobi D/Sync: PusherInternal{http://192.168.1.6:4984/db, push, 93afe}: No changes since 196
03-25 12:05:32.657 3180-3338/com.atoz.dhobi V/Sync: com.couchbase.lite.replicator.RemoteRequest {GET, http://192.168.1.6:4984/db/_local/93afe801dd2bb2005a04bd430c7007d4a2546f14}: RemoteRequest execute() finished, url: http://192.168.1.6:4984/db/_local/93afe801dd2bb2005a04bd430c7007d4a2546f14
03-25 12:05:32.658 3180-3339/com.atoz.dhobi D/Sync: PusherInternal{http://192.168.1.6:4984/db, push, 93afe} [fireTrigger()] => WAITING_FOR_CHANGES
03-25 12:05:32.658 3180-3339/com.atoz.dhobi V/Sync: [waitForPendingFutures()] END - thread id: 16
```

**Comment by rizwanbpatel** [comment] 2018-03-27 03:12
- Yes, I had checked sync-gateway and cb-server both; document count is updated and as expected. I Tried with working version of app on an emulator. Attached sample of document listing from sync-gateway.
- Any way by which I can check what version of check flag has been communicating from emulator to CB-SG? 
> {"committed_update_seq":172,"compact_running":false,"db_name":"db","disk_format_version":0,"instance_start_time":1521975223950665,"purge_seq":0,"state":"Online","update_seq":172}

<img width="679" alt="screen shot 2018-03-27 at 8 39 09 am" src="https://user-images.githubusercontent.com/4496892/37944743-77c2502e-319a-11e8-8d32-4f639054939d.png">

**Comment by rizwanbpatel** [comment] 2018-03-30 03:11
Further I tried to visit the Admin as well as Public API _all_docs and surprised to see the below different results.

Request : http://192.168.1.6:4984/db/_all_docs
Response : _{"rows":[],"total_rows":0,"update_seq":172}_

Request : http://192.168.1.6:4985/db/_all_docs
Response : _{"rows":[
{"key":"027973a38549cf027410625fe38762b5","id":"027973a38549cf027410625fe38762b5","value":{"rev":"1-a9446f836536555b0ca694fd82c0795c"}}
,{"key":"054f4f1e-38db-47a0-8711-a6b14653e408","id":"054f4f1e-38db-47a0-8711-a6b14653e408","value":{"rev":"1-d6779f14d171e0b4cbd876dea558f018"}}
,{"key":"064878d5343b5fb7b7dbfc460220fe51","id":"064878d5343b5fb7b7dbfc460220fe51","value":{"rev":"1-a7c60534d340316b9a24fe7afb010945"}}
,........
],
"total_rows":149,"update_seq":172}_


And this is sync-gateway configuration. Is anything missing?
``` 
{ 
  "interface":":4984",  "log": ["*"],
  "databases": {
    "db": {
      "server": "http://172.18.0.2:8091",
      "bucket": "db",
      "username": "admin",
      "password": "abc12345"
     }
  }
} ```

**Comment by hideki** [comment] 2018-03-30 19:22
Hi @rizwanbpatel,
Do you enable guest access if your app does use authentication?

Following is sample SG config that supports CB as backend database. 
```json
{
  "log": ["*"],
  "databases": {
    "db": {
      "server": "http://localhost:8091",
      "bucket": "default",
      "users": { "GUEST": { "disabled": false, "admin_channels": ["*"] } },
      "allow_conflicts": false,
      "revs_limit": 20
    }
  }
}
```

**Comment by rizwanbpatel** [comment] 2018-03-30 20:36
Hi @hideki ,
After following your advice updated  sync config and post that public port _all_docs are in line but still the replication not giving anything on mobile app.

```
{
  "interface":":4984",
  "log": ["*"],
  "databases": {
    "db": {
      "server": "http://172.18.0.2:8091",
      "bucket": "dhobi",
      "username": "admin",
      "password": "abc12345",
      "users": { "GUEST": { "disabled": false, "admin_channels": ["*"] } },
      "allow_conflicts": false,
      "revs_limit": 20
     }
  }
}
```

**Comment by hideki** [comment] 2018-03-30 21:30
Hi @rizwanbpatel,
I am not sure why the replication does not work with your development.
Can you do debug step by step?
As the first step, can you test if todo sample works with your environment?
https://github.com/couchbaselabs/mobile-training-todo

If it does not work, something environment issue.
If it works, the problem could be in the application. So we could debug further

**Comment by rizwanbpatel** [comment] 2018-04-01 04:46
Hi @hideki,

I am starting now with the To-Do app, will update on it. 

Regards,
rizwan

**Comment by rizwanbpatel** [comment] 2018-04-01 12:48
Hi @hideki,

Is below might be the reason for this kind of behavior? As my emulator and Docker are running on MacOs on same machine.

> ⚠️ Docker and x86 Android emulators are not compatible (i.e cannot run simultaneously on the same machine). Make sure Docker isn't running in the background when deploying the application to an x86 Android emulator.

**Comment by hideki** [comment] 2018-04-02 05:35
@rizwanbpatel,

Do you have the replication problem in case of using the real device?

I am not familiar with Docker, and also compatibility with Android x86 emulator. You might try to use ARM emulator or Gennymotion emulator if you need to use an emulator? Or you could install emulator and Docker on to different machines.

**Comment by pasin** [comment] 2018-09-05 22:45
I'm closing this issue as no activities. If the issue is still a concern, please report back and we can reopen the issue. Thanks.

**Closed by pasin** 2018-09-05 22:45 UTC
Labels: icebox, reproduce/investigate
