### ISSUE TITLE
Slow performance for Update/Delete of documents

### ISSUE THREAD

**Issue by jcnorman48** [couchbase/couchbase-lite-android#444] opened 2014-10-27 18:32 UTC
Per this thread on the groups:
https://groups.google.com/forum/#!topic/mobile-couchbase/vbLS2Rgatn0

I'm experiencing slow update and delete speeds at around 1/4 second per document with a database of 50K documents.  Inserts are very fast at around 1K/second.  This has been tested with Samsung Galaxy Tab 4 and Samsung Galaxy S5 with the same results.  This was tested against CB Lite 1.0.2 and 1.0.3.  The following code can replicate the issue:

                try {
                Manager manager = new Manager( new AndroidContext(app), Manager.DEFAULT_OPTIONS);
                Database database = manager.getDatabase( "bigtest7" );

                //create 50k documents
                {
                    long startTime = System.currentTimeMillis();
                    database.beginTransaction();
                    for( int i=0; i<50000; i++ ) {
                        Document document = database.createDocument();
                        Map<String,Object> props = new HashMap<String,Object>();
                        for( int j=0; j<10; j++ ) {
                            props.put( "key" + j , "value" + j );
                        }
                        document.putProperties(props);
                    }
                    database.endTransaction(true);
                    long endTime = System.currentTimeMillis();
                    System.out.println("TIME: CREATE:" + ((endTime-startTime)/1000) );
                }

                //time it takes to delete 200 records
                {
                    List<String> toDelete = new ArrayList<String>();
                    Query query = database.createAllDocumentsQuery();
                    query.setLimit(200);
                    QueryEnumerator enum1 = query.run();
                    while( enum1.hasNext() ) {
                        toDelete.add( enum1.next().getDocumentId() );
                    }

                    long deleteStart = System.currentTimeMillis();
                    database.beginTransaction();
                    for( String toDeleteId:toDelete ) {
                        database.getDocument(toDeleteId).delete();
                    }
                    database.endTransaction(true);
                    long deleteEnd = System.currentTimeMillis();
                    System.out.println("TIME: DELETE:" + ((deleteEnd-deleteStart)/1000) );
                }

            }
            catch( Exception e ) {
                e.printStackTrace();
            }

**Comment by tleyden** [comment] 2015-01-23 19:06
Closing as a duplicate of https://github.com/couchbase/couchbase-lite-java-core/issues/297

**Closed by tleyden** 2015-01-23 19:06 UTC
Labels: performance, S2: critical, size-medium, waffle:in progress
