### ISSUE TITLE
Huge Pull-Replication performance problems compared with iOS

### ISSUE THREAD

**Issue by kvaillant** [couchbase/couchbase-lite-android#1030] opened 2016-10-26 09:02 UTC
Hi, I am re-opening issue #946.

We have been using CouchbaseLite for two years now, and still notice very huge performance difference between iOS and Android. 
These are our platform env:
- Couchbase Lite Version : 1.3.1 (SQLite & ForestDB)
- Couchbase Sync Gateway Version : 1.3.1 (16;f18e833)
- Database Size: 3.3Mo (no attachments)
- Number of Document : 4814

These are our results:

```
iOS Pull Replication Time with iPod 5, iOS 9 : 15s
iOS Pull Replication Time with iPhone 6, iOS 10 : 6s
Android Pull Replication Time with Nexus 5, Android 6.0.1 : minimum was 1m15s, goes up to 5 minutes if I enable ForestDB.
```

Those test were done a dozen times within the exact same environment (same Wifi connection, same Server).

Looking at the logs, iOS seems to be batching a lot of documents really fast, while Android seems to take them by 200s, very slowly comparatively.

Also, if you don’t set the MaxRevTreeDepth for Android, it crashes the replicator event 100% reproduction ratio.

If you are interested, we can privately share with you our test data-set and credentials to figure out what could be the issue.

**Comment by kvaillant** [comment] 2016-11-03 15:07
Hi,
Is there any way to help you debug this android cbl issue ? 
We would like to use CBL-android 1.3.1 with SQLLite for our production platform.

**Comment by hideki** [comment] 2016-11-03 16:27
Hi @kvaillant,

> Is there any way to help you debug this android cbl issue ? 

4814 documents, and total size is 3MB is not huge. The replication should not take too long.

Can you share your data? Replication slowness could be caused by Data. For example, Document has too many revisions, or many conflicts, or size is huge, etc.

**Comment by kvaillant** [comment] 2016-11-04 06:21
Hi @hideki ,
Thank you for your support. I share our access to our platform privately.

**Comment by hideki** [comment] 2016-11-29 00:58
Hi @kvaillant,

Sorry for slow response. I measured latency with using real device against sync gateway server you provided. CBL that I used for this test is built from master branch. As you wrote, CBL Android takes around 60 seconds to pull replicate entire db. As far as I know, pull replication could be caused by memory usage during pull replication.  This issue could be hard to addressed without replicator code architectural change.

#### Test results
Nexus 9 (Android 7.0) with Office Wifi
- `11-28 16:42:48.128  3936  3956 V Test_Issue1030: PerformanceStats: 64990 msec (Issue #1030)`

Nexus 6 (Android 6.0.1) with Office Wifi
- `11-28 16:29:30.504  5169  5184 V Test_Issue1030: PerformanceStats: 64029 msec (Issue #1030)`

Nexus 5 (Android 6.0.1) with Office Wifi
- `11-28 16:26:45.649 22211 22226 V Test_Issue1030: PerformanceStats: 56531 msec (Issue #1030)`

#### Test codes
```java
    public void testPullReplPerformance() throws CouchbaseLiteException, MalformedURLException, InterruptedException {
        if (!performanceTestsEnabled())
            return;

        long start = System.currentTimeMillis();
        Replication repl = database.createPullReplication(new URL("<url>"));
        Authenticator auth = AuthenticatorFactory.createBasicAuthenticator("<username>", "<password>");
        repl.setAuthenticator(auth);
        CountDownLatch latch = new CountDownLatch(1);
        repl.addChangeListener(new LiteTestCaseWithDB.ReplicationFinishedObserver(latch));
        repl.addChangeListener(new Replication.ChangeListener() {
            @Override
            public void changed(Replication.ChangeEvent event) {
                Log.e(TAG, "" + event);
            }
        });
        repl.start();
        latch.await();
        long end = System.currentTimeMillis();
        logPerformanceStats((end - start), "Issue #1030");
    }
```

**Comment by hideki** [comment] 2016-11-29 02:26
Hi @kvaillant,

Can you compile CBL from source code? If yes, can you try following branch for couchbase-lite-java-core module? It could reduce 15 - 30sec for your data.
https://github.com/couchbase/couchbase-lite-java-core/tree/issue/android/1030

**Comment by hideki** [comment] 2016-11-29 21:13
Note to Self:

| | CBL 1.3.1 | branch issue/android/1030 |
| -- | -- | -- |
| Nexus 5/Android 6.0.1 | 59709 ms | 51020 ms |
| Nexus 6/Android 6.0.1 | 58287 ms | 48380 ms |
| Nexus 9/Android 7.0    | 38205 ms | 40033 ms |

**Comment by hideki** [comment] 2016-11-29 22:10
Note to Self:

I could observe following logging message in logcat during pull replication. Need to investigate.
```
11-29 14:08:44.788 15178-15185/hideki.self.issue1030 W/art: Suspending all threads took: 8.428ms
```

**Comment by hideki** [comment] 2016-11-29 22:18
Note to self:

I could observe following message during pull replication. It seems GC suspended all threads for 13sec.
```
11-29 14:12:03.909 18300-18306/hideki.self.issue1030 W/art: Suspending all threads took: 13.338ms
```

**Comment by hideki** [comment] 2016-11-30 03:43
Note to self:

Slowness comes from `SQLiteStore.forceInsert()`, especially from `pruneDocument()`. Some of documents have many revisions. During the inserting  revisions of these documents, `pruneDoucment()` method is called, and it takes time. Maybe, calling `pruneDocument()` for newest revision could be enough?

**Comment by hideki** [comment] 2016-12-03 02:16
Following is method profiling results by DDMS. Major contributor of slowness is `insertRevision()`. Second is `pruneDocument()`.

![screen shot 2016-12-02 at 5 40 47 pm](https://cloud.githubusercontent.com/assets/15889/20855777/bab80b0c-b8b6-11e6-9448-ffe2d94d53f2.png)

**Comment by hideki** [comment] 2016-12-03 03:57
Following is logcat from emulator. it indicates many GC calls are executed during pull replication.
```
12-02 22:55:27.743 1456-1551/hideki.self.issue1030 E/Issue1030: PULL replication event. Source: Replication{https://sync.moby-city.fr/mbct_sync/, pull} Total changes: 5539 Completed changes: 5381
12-02 22:55:27.747 1456-1551/hideki.self.issue1030 E/Issue1030: PULL replication event. Source: Replication{https://sync.moby-city.fr/mbct_sync/, pull} Total changes: 5540 Completed changes: 5381
12-02 22:55:27.747 1456-1551/hideki.self.issue1030 E/Issue1030: PULL replication event. Source: Replication{https://sync.moby-city.fr/mbct_sync/, pull} Total changes: 5541 Completed changes: 5381
12-02 22:55:27.747 1456-1551/hideki.self.issue1030 E/Issue1030: PULL replication event. Source: Replication{https://sync.moby-city.fr/mbct_sync/, pull} Total changes: 5542 Completed changes: 5381
12-02 22:55:27.747 1456-1551/hideki.self.issue1030 E/Issue1030: PULL replication event. Source: Replication{https://sync.moby-city.fr/mbct_sync/, pull} Total changes: 5543 Completed changes: 5381
12-02 22:55:28.099 1456-1581/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 6628K, 68% free 3904K/11896K, paused 5ms, total 5ms
12-02 22:55:28.115 1456-1581/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 490K, 68% free 3925K/11896K, paused 3ms, total 3ms
12-02 22:55:28.123 1456-1581/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 428K, 67% free 4008K/11896K, paused 4ms, total 4ms
12-02 22:55:28.243 1456-1581/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 455K, 66% free 4065K/11896K, paused 4ms, total 4ms
12-02 22:55:28.255 1456-1581/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 505K, 66% free 4070K/11896K, paused 3ms, total 3ms
12-02 22:55:28.263 1456-1581/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 457K, 66% free 4124K/11896K, paused 2ms, total 2ms
12-02 22:55:28.271 1456-1581/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 439K, 65% free 4197K/11896K, paused 2ms, total 2ms
12-02 22:55:28.291 1456-1581/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 259K, 63% free 4449K/11896K, paused 3ms, total 3ms
12-02 22:55:28.315 1456-1581/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 676K, 64% free 4309K/11896K, paused 4ms, total 4ms
12-02 22:55:28.335 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 373K, 63% free 4447K/11896K, paused 4ms, total 4ms
12-02 22:55:28.383 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 533K, 63% free 4452K/11896K, paused 5ms, total 5ms
12-02 22:55:28.419 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 496K, 63% free 4495K/11896K, paused 3ms, total 3ms
12-02 22:55:28.459 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 522K, 62% free 4526K/11896K, paused 3ms, total 3ms
12-02 22:55:28.495 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 538K, 62% free 4552K/11896K, paused 3ms, total 3ms
12-02 22:55:28.535 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 501K, 62% free 4624K/11896K, paused 4ms, total 4ms
12-02 22:55:28.567 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 556K, 61% free 4663K/11896K, paused 3ms, total 3ms
12-02 22:55:28.615 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 551K, 61% free 4722K/11896K, paused 7ms, total 7ms
12-02 22:55:28.663 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 579K, 60% free 4772K/11896K, paused 4ms, total 4ms
12-02 22:55:28.703 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 599K, 60% free 4819K/11896K, paused 2ms, total 2ms
12-02 22:55:28.739 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 610K, 60% free 4870K/11896K, paused 4ms, total 4ms
12-02 22:55:28.779 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 595K, 59% free 4953K/11896K, paused 3ms, total 3ms
12-02 22:55:28.799 1456-1582/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 599K, 58% free 5057K/11896K, paused 3ms, total 4ms
12-02 22:55:28.819 1456-1582/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 726K, 58% free 5071K/11896K, paused 5ms, total 5ms
12-02 22:55:28.839 1456-1582/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 689K, 57% free 5122K/11896K, paused 6ms, total 6ms
12-02 22:55:28.867 1456-1582/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 673K, 57% free 5211K/11896K, paused 6ms, total 6ms
12-02 22:55:28.899 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 753K, 56% free 5250K/11896K, paused 3ms, total 3ms
12-02 22:55:28.935 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 746K, 56% free 5310K/11896K, paused 3ms, total 3ms
12-02 22:55:28.975 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 746K, 55% free 5389K/11896K, paused 3ms, total 3ms
12-02 22:55:29.019 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 754K, 54% free 5487K/11896K, paused 6ms, total 6ms
12-02 22:55:29.071 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 833K, 54% free 5538K/11896K, paused 7ms, total 7ms
12-02 22:55:29.127 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 800K, 53% free 5639K/11896K, paused 7ms, total 7ms
12-02 22:55:29.175 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 943K, 53% free 5630K/11896K, paused 4ms, total 4ms
12-02 22:55:29.231 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 803K, 52% free 5758K/11896K, paused 7ms, total 7ms
12-02 22:55:29.291 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 959K, 52% free 5772K/11896K, paused 7ms, total 7ms
12-02 22:55:29.339 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 908K, 51% free 5844K/11896K, paused 4ms, total 4ms
12-02 22:55:29.383 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 912K, 51% free 5936K/11896K, paused 4ms, total 4ms
12-02 22:55:29.427 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 959K, 50% free 6011K/11896K, paused 4ms, total 4ms
12-02 22:55:29.495 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 787K, 48% free 6283K/11896K, paused 9ms, total 9ms
12-02 22:55:29.555 1456-1551/hideki.self.issue1030 E/Issue1030: PULL replication event. Source: Replication{https://sync.moby-city.fr/mbct_sync/, pull} Total changes: 5543 Completed changes: 5481
12-02 22:55:29.835 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 3416K, 67% free 4016K/11896K, paused 3ms, total 3ms
12-02 22:55:29.875 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 513K, 67% free 4015K/11896K, paused 3ms, total 3ms
12-02 22:55:29.911 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 481K, 66% free 4045K/11896K, paused 3ms, total 3ms
12-02 22:55:29.947 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 493K, 66% free 4064K/11896K, paused 3ms, total 3ms
12-02 22:55:29.983 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 496K, 66% free 4079K/11896K, paused 3ms, total 3ms
12-02 22:55:30.015 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 457K, 66% free 4134K/11896K, paused 3ms, total 3ms
12-02 22:55:30.055 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 465K, 65% free 4180K/11896K, paused 3ms, total 3ms
12-02 22:55:30.103 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 499K, 65% free 4193K/11896K, paused 3ms, total 3ms
12-02 22:55:30.139 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 452K, 65% free 4252K/11896K, paused 3ms, total 3ms
12-02 22:55:30.179 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 501K, 65% free 4263K/11896K, paused 3ms, total 3ms
12-02 22:55:30.215 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 477K, 64% free 4298K/11896K, paused 3ms, total 3ms
12-02 22:55:30.251 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 484K, 64% free 4325K/11896K, paused 3ms, total 3ms
12-02 22:55:30.291 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 481K, 64% free 4355K/11896K, paused 4ms, total 4ms
12-02 22:55:30.331 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 451K, 63% free 4416K/11896K, paused 5ms, total 5ms
12-02 22:55:30.371 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 527K, 63% free 4417K/11896K, paused 3ms, total 3ms
12-02 22:55:30.403 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 483K, 63% free 4461K/11896K, paused 3ms, total 3ms
12-02 22:55:30.439 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 465K, 62% free 4538K/11896K, paused 2ms, total 2ms
12-02 22:55:30.475 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 569K, 62% free 4537K/11896K, paused 4ms, total 4ms
12-02 22:55:30.515 1456-1551/hideki.self.issue1030 D/dalvikvm: GC_FOR_ALLOC freed 489K, 62% free 4615K/11896K, paused 2ms, total 2ms
12-02 22:55:30.535 1456-1551/hideki.self.issue1030 E/Issue1030: PULL replication event. Source: Replication{https://sync.moby-city.fr/mbct_sync/, pull} Total changes: 5543 Completed changes: 5543
12-02 22:55:30.535 1456-1551/hideki.self.issue1030 E/Issue1030: PULL replication event. Source: Replication{https://sync.moby-city.fr/mbct_sync/, pull} Transition: RUNNING -> STOPPING Total changes: 5543 Completed changes: 5543
12-02 22:55:30.751 1456-1551/hideki.self.issue1030 E/Issue1030: PULL replication event. Source: Replication{https://sync.moby-city.fr/mbct_sync/, pull} Transition: STOPPING -> STOPPED Total changes: 5543 Completed changes: 5543
12-02 22:55:30.751 1456-1551/hideki.self.issue1030 E/Issue1030: Duration: 32470 ms
```

**Comment by hideki** [comment] 2016-12-03 04:59
Following is method profiling data that was captured with Genymotion emulator. It indicates parsing JSON by Jackson takes a lot of computation time.
<img width="1634" alt="screen shot 2016-12-02 at 8 57 03 pm" src="https://cloud.githubusercontent.com/assets/15889/20856922/fd142a60-b8d1-11e6-8387-68ae39ade2d0.png">

**Comment by hideki** [comment] 2016-12-05 20:54
Note to Self:

CBL iOS pull replication performance:
- iPhone 7 / iOS 10: 14.664 sec
- iPhone 6S emulator on OSX: 19.120 sec

CBL Android pull replication performance:
- Nexus 9 / Android N: 49.269 sec
- Nexus 6 / Android M: 52.258 sec

**Comment by hideki** [comment] 2016-12-05 21:30
Hi @kvaillant,

I investigated issue. According to the method profiling, inserting revision data into SQLite database takes time. Maybe JNI binding makes slow. Or, when copy data into native layer from java layer, it creates a copy of data. So it might use much memory. But these are not improvable in short period of time.

I have one suggestion. Some of documents on the server have many conflicts. CBL Android takes time to process these documents which have many conflicts. So if you could resolve conflicts on the server, pull replication performance should improve a lot.

Thanks!
Hideki

**Comment by hideki** [comment] 2016-12-05 21:33
Note To Self:

How to avoid GC:
- https://developer.android.com/training/articles/perf-tips.html#ObjectCreation

**Comment by kvaillant** [comment] 2016-12-10 10:09
Thank you @hideki for checking this out and sorry for the response delay.

I did compare replication between the two branches of `couchbase-lite-java-core` with my Nexus 5. And it is slightly better indeed:
Branch `issue/android/1030` took 48142ms
Branch `master` took 58030ms

The same takes about 12000ms with an iPhone 6.

I am still surprised by the comparison between iOS and Android. Conflicts have a really small impact on replication time for iOS.

Before sharing access to you, I wrote a nodejs script to resolve conflicts on couchbase server and set revision limit to 20 into Sync Gateway config file (revs_limit = 20).

Maybe, websocket support for cbl-java-core will boost sync performances ? 
I look forward to getting this issue implemented : https://github.com/couchbase/couchbase-lite-java-core/issues/493. 
Do you know why it was removed from milestone 1.5.0 ?


Thanks a lot for your time
Karl

**Comment by kvaillant** [comment] 2016-12-12 10:42
Hi @hideki,

As you suggested, I resolved all existing conflicts (a few documents had 60 unresolved conflicts) on our platform and did another pull replication. 

From branch `issue/android/1030`, we gained nearly 30% less time for replication.

Then **resolving conflicts** is an important key point for performance optimization.

Have a good day !
Karl

**Comment by hideki** [comment] 2016-12-12 18:07
> Do you know why it was removed from milestone 1.5.0 ?

Our focus has shifted to CBL v2.0, which is next major upgrade. If we implement WebSocket to v1.x, its life could be some months. So we will implement it for v2.x.

**Comment by hideki** [comment] 2016-12-12 18:08
> Maybe, websocket support for cbl-java-core will boost sync performances ?

From current my observation, memory usage makes GC busy, and then GC slows application (replication).

**Comment by hideki** [comment] 2016-12-12 18:11
> From branch issue/android/1030, we gained nearly 30% less time for replication.

> Then resolving conflicts is an important key point for performance optimization

Thank you very much for verifying if resolving conflicts can improve pull replication performance.

I talked with iOS engineer, CBL iOS does not have any special logic to handle conflicts during pull replication. But there might exists implementation difference between iOS and Android.

**Comment by hideki** [comment] 2017-01-18 19:30
PR: https://github.com/couchbase/couchbase-lite-java-core/pull/1561

**Closed** 2017-01-19 01:47 UTC
Labels: P1: high, performance

**Comment by AlBlanc** [comment] 2017-02-06 22:06
Can't you make an interface `IReplication`, this way we would be able to create our own? I would like to make a custom one using websocket ...
