### ISSUE TITLE
Test cases WithFilter failure

### ISSUE THREAD

**Issue by jayahariv** [couchbase/couchbase-lite-android#1842] opened 2019-01-25 21:00 UTC
Local2LocalReplicatorTest -> testPullRemovedDocWithFilter() failure. 

Found this happens when replicator instance is returning null inside the [validationFunction](https://github.com/couchbase/couchbase-lite-core/blob/fb62279197ff11e8819324a5905878020e6c7880/Java/src/com/couchbase/litecore/C4Replicator.java#L180) which causing the pullFilter is not getting called.

Tested with below configuration emulator, which returns failure always. 
Android: 4.4
API: 19

**Comment by pasin** [comment] 2019-01-25 21:01
@Sandychuang8 as you have developed this feature. I'm assigning this issue to you.

**Comment by pasin** [comment] 2019-01-29 05:40
It seems like the code that handles replicator context (probably socket context as well) is not correct. It should get the global reference of the context object before passing to the the callbackContext of the replicator parameter. It's also strange that we pass the hash code of the replicator but not the replicator object itself. I will try to refactor this.

**Comment by pasin** [comment] 2019-01-29 05:41
Note that I have fixed the predictive query tests issue. The problem is at the function that converts slice to c-string.

**Closed** 2019-01-30 06:39 UTC
Labels: P1: high, ready
