### ISSUE TITLE
CursorWindowAllocationException thrown in Query.run()

### ISSUE THREAD

**Issue by keith-redbite** [couchbase/couchbase-lite-android#579] opened 2015-04-15 15:05 UTC
Hi,

The following exception was observed in 1.0.4.

### CursorWindowAllocationException
```
android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed.
at android.database.CursorWindow.<init>(CursorWindow.java:104)
at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
at android.database.AbstractCursor.moveToNext(AbstractCursor.java:245)
at com.couchbase.lite.android.AndroidSQLiteStorageEngine$SQLiteCursorWrapper.moveToNext(AndroidSQLiteStorageEngine.java:178)
at com.couchbase.lite.Database.getLastSequenceNumber(Database.java:294)
at com.couchbase.lite.View.updateIndex(View.java:386)
at com.couchbase.lite.Database.queryViewNamed(Database.java:2096)
at com.couchbase.lite.Query.run(Query.java:378)
```

### Query 
The query do have IndexUpdateMode.BEFORE set. 

```
			Query query = view.createQuery();
			query.setIndexUpdateMode(IndexUpdateMode.BEFORE);
			try {
				QueryEnumerator rows = query.run();
				
				results = new ArrayList<>(rows.getCount());
				while(rows.hasNext()) {
					results.add(UUID.fromString((String) rows.next().getValue()));
				}
			} catch (CouchbaseLiteException e) {
				throw new RuntimeException("Couldn't get all items", e);
			}
```

### Mapper
View's mapper

```
	@Override
	public void map(Map<String, Object> map, Emitter emitter) {
		if( map.get("name") != null
				&& entity.get("description") != null){
			
			emitter.emit(
				Arrays.asList(
					((String)map.get("name")).toLowerCase(),
					((String)map.get("description")).toLowerCase()),
				map.get("identity"));
		}
	}
```

I am having difficulty reproducing this issue. My apologies for lack of information as this is as much as I've managed to gather. Thought it best to have it documented tho.

Thanks
Keith

**Comment by hideki** [comment] 2015-04-15 18:31
Hi @keith-redbite,

Thank you very much for reporting issue.

If your document size is larger than 2MB, it is Android SQLite limitation. see https://github.com/couchbase/couchbase-lite-android/issues/256 . If this is case, only solution is to maker document size smaller.

Please check maximum document size, average document size and number of documents which are stored. Also, we would like to know your test device model and Android version.

In case document size is smaller than 2MB, the issues root cause could be same with https://github.com/couchbase/couchbase-lite-android/issues/210 .

Current master branch code is little memory efficient during View.updateIndex(). If you have time, could you please try latest master branch version of CBL Android?

If you are using Android Studio, please specify "0.0.0-511" for CBL Android version in build.gradle file.
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/0.0.0-511/

Or you can use CBL Android as submodule, please refer wiki page: https://github.com/couchbase/couchbase-lite-android/wiki/Add-Couchbase-Lite-to-your-project-as-a-submodule

If you are using Eclipse, currently download build is not available.

Thanks!

**Comment by zgramana** [comment] 2015-04-17 17:46
Closing as a duplicate of issue #310

**Closed** 2015-04-17 17:47 UTC
Labels: duplicate
