### ISSUE TITLE
Gradle build failed with mobile.maven.couchbase.com/maven2 repository

### ISSUE THREAD

**Issue by sytolk** [couchbase/couchbase-lite-android#1605] opened 2018-02-16 17:58 UTC
In my android project I have v.2 branch with Maven repo
```
maven {
        url "http://mobile.maven.couchbase.com/maven2/dev/"
    }

```
But Gradle search other packages in maven.couchbase repo and build failed if received from Maven status code 500 from server: Internal Server Error:
```
* What went wrong:
Could not resolve all files for configuration ':react-native-google-analytics-bridge:debugCompileClasspath'.
> Could not resolve com.google.android.gms:play-services-analytics:+.
  Required by:
      project :react-native-google-analytics-bridge
   > Could not resolve com.google.android.gms:play-services-analytics:+.
      > Failed to list versions for com.google.android.gms:play-services-analytics.
         > Could not list versions using M2 pattern 'http://mobile.maven.couchbase.com/maven2/dev/[organisation]/[module]/[revision]/[artifact]-[revision](-[classifier]).[ext]'.
            > Could not get resource 'http://mobile.maven.couchbase.com/maven2/dev/com/google/android/gms/play-services-analytics/'.
               > Could not GET 'http://mobile.maven.couchbase.com/maven2/dev/com/google/android/gms/play-services-analytics/'. Received status code 500 from server: Internal Server Error
```
Without this repo build succeeded. Do you have an idea what was wrong with couchbase Maven repository? maybe there is "not found" status code for not couchbase packages.

**Comment by hideki** [comment] 2018-02-16 18:08
hi @sytolk,
Can you please share your dependency line for couchbase-lite-android in build.gradle?

**Comment by hideki** [comment] 2018-02-16 18:13
hi @sytolk,

Can you compare your build.gradle with our sample todo app codes?
https://github.com/couchbaselabs/mobile-training-todo/tree/master/android

**Comment by sytolk** [comment] 2018-02-16 20:37
hi @hideki,

for the couchbase dependencies my build.gradle is the same like mobile-training-todo app "feature/2.0 branch" (in my project it's have extra dependencies like play-services-analytics)
To fix this issue I will downloaded AAR library and manually import it in my Maven local repository:
http://mobile.maven.couchbase.com/maven2/dev/com/couchbase/lite/couchbase-lite-android/2.0.0-DB022/couchbase-lite-android-2.0.0-DB022.aar
I suppose that there is a problem with Maven repository installed on url: "http://mobile.maven.couchbase.com/maven2/dev/" and will remove this Maven repo from my Gradle project. Can you check server logs for this: "Internal Server Error" ?

**Comment by hideki** [comment] 2018-02-16 21:13
@borrrden Do you have time to look into the repository log?

**Comment by borrrden** [comment] 2018-02-16 21:21
Usually when this happens it is because the machine hosting the maven feed last access to the NAS machine where the files are stored.  This happens every so often and I don't know why...but I reconnected it so if that is indeed the problem (the logs show a bunch of errors around the OpenFile function in the server which usually indicates this problem) then it should be fixed now.

**Comment by hideki** [comment] 2018-02-16 21:41
hi @sytolk,
It seems our maven repo server cannot handle the request for `com.google.android.gms:play-services-analytics:+`. And the repo server caused the internal error.

**Comment by hideki** [comment] 2018-02-17 01:53
Hi @sytolk,

It seems the problem is caused by the server we are using. However, we can not upgrade the server in short period of time.

https://inedo.com/blog/proget-484-released?utm_source=proget&utm_medium=latestnews&utm_campaign=pginternal
```
PG-1102 - FIX: Maven feeds endpoints return 500 instead of 404 when 
```
https://inedo.com/blog/proget-487-released
```
PG-1129 - FIX: Requesting maven-metadata.xml of a snapshot version of a nonexistent package returns 500 instead of 404
```

**Comment by hideki** [comment] 2018-02-17 02:02
FYI: https://stackoverflow.com/questions/32909421/could-not-find-com-google-android-gmsplay-services-analytics8-1-0

**Comment by sytolk** [comment] 2018-02-19 09:47
Thanks @hideki 

> we can not upgrade the server in short period of time

 I think it's a good idea to add optional installation here?
 https://github.com/couchbase/couchbase-lite-android#installation
To download couchbase-lite-android-2.0.0-DB022.aar file and include it locally like that:
https://medium.com/@notestomyself/how-to-include-external-aar-file-using-gradle-6604b378e808

**Comment by hideki** [comment] 2018-03-29 22:53
@sytolk,
We updated ProGet server to `4.8.12` which has the fix of PG-1102. Can you test the maven dependency? Thank you!
https://inedo.com/blog/proget-484-released?utm_source=proget&utm_medium=latestnews&utm_campaign=pginternal

**Comment by hideki** [comment] 2018-03-30 20:09
ProGet 4.8.12 Maven repo has the issue with Android Studio 3.1.0.
We upgraded ProGet to 5.0.10. With 5.0.10, dependency issue is gone.

We believe this upgrade solves maven repo issues.

**Closed by hideki** 2018-03-30 20:09 UTC
Labels: P2: medium, ready

**Comment by sytolk** [comment] 2018-04-02 11:36
It's work now thanks!
