### ISSUE TITLE
CBLite use of deleted global reference 0x200ce6 after java.io.EOFException

### ISSUE THREAD

**Issue by K-Leon** [couchbase/couchbase-lite-android#1907] opened 2019-04-29 10:22 UTC
First of thanks for your hard work.

I just stumbled upon a "rare" issue - in some error conditions related to a flaky connection the device seems to crash randomly. 

I'm using Iridium Build right now.

Luckily it happens on our Debug App Version so i have a pretty good log about what was going on.

https://gist.github.com/K-Leon/82139c4ddd4e053b7fa278580dc338e9

Best Regards,
Leon

**Comment by K-Leon** [comment] 2019-05-02 23:04
I had the same issue again - seems to be related to connection switches. ( Just turned on WIFI )

**Comment by bmeike** [comment] 2019-05-08 23:44
Duplicate of https://github.com/couchbase/couchbase-lite-java/issues/114.  The issue is being tracked there...

**Closed by bmeike** 2019-05-08 23:44 UTC
