### ISSUE TITLE
Crash during 1.1 to 1.2 migration causes permanent loss of data

### ISSUE THREAD

**Issue by sgapr** [couchbase/couchbase-lite-android#888] opened 2016-05-31 12:28 UTC
If a user swipes out the app while 1.1 -> 1.2 migration is going on, then the following check in the code will cause data to be lost on the next run.

https://github.com/couchbase/couchbase-lite-java-core/blob/09b6111ace0d49c82e52d2749819f0158d013b7e/src/main/java/com/couchbase/lite/Manager.java#L831

**Comment by tikimcfee** [comment] 2016-06-13 12:01
I can confirm this - if an upgrade does not complete and the app is closed (process is stopped), the DatabaseUpgrader has already deleted and created files it checks to determine if it should upgrade. Ideally, this should be an entirely non-destructive process until the entire import is complete. If there is not enough disk space, there should be a callback to alert the dev to handle the scenario in w/e way it makes sense. As it is, it was highly unexpected the creation of the Manager class causes an upgrade - we had to find that out accidentally, and wrap the creation of that object up in a new path from 1.1 -> 1.2. Required callback implementations (abstract manager class?) would be well warranted here.

**Comment by sgapr** [comment] 2016-08-08 07:36
Is there a solution / workaround for this. Given the android N issue #801, migrating seems necessary but can still cause loss of data.

**Comment by hideki** [comment] 2016-08-08 08:27
@sgapr 
If you need to use v1.2.x, you could use [couchbase-lite-android-sqlite-custom] (https://bintray.com/couchbase/couchbase/couchbase-lite-android-sqlite-custom) instead of using system sqlite.

**Comment by Takhion** [comment] 2016-08-23 14:56
We were forced to upgrade from 1.1 to 1.3 because of Android Nougat compatibility, and our users are now experiencing data loss all over the place!! Is there still not a fix for this?

**Comment by Takhion** [comment] 2016-08-23 15:07
@hideki is there anything we can do to help?

**Comment by sgapr** [comment] 2016-08-24 15:25
@Takhion  FWIW, we upgraded to 1.3 using a fork with the following commit to prevent data loss.

https://github.com/sgapr/couchbase-lite-java-core/commit/5cab35a6c7ec79ad0b8ea6f7daec54c00b07c865

**Comment by Takhion** [comment] 2016-08-24 15:47
@sgapr we did something similar: patched to library jar to include a method call before the body of `upgradeDatabase`, where if both the old and the new db are present, we delete the new db and let the function do its thing (which will re-create the new db).
The problem is that there is NO mention of this issue anywhere, and we never reproduced it locally, so we shipped one version of the app with the flawed migration and lots of users experienced total data loss.

**Comment by tikimcfee** [comment] 2016-08-24 16:28
@sgapr 
That fork looks like a great trick to handle the update. Have you added or changed anything else of great significance? We might like to use that fork if there are no objections!
@Takhion 
Agreed - we've mentioned a few times that these game-changing APIs really need to be documented and tested heavily before being dropped. For what it's worth, there is a documentation git repo available, but I can't for the life of me find it. Might be worth it to track it down +1 this mention there as well.

**Comment by hideki** [comment] 2016-08-24 19:07
Hi @sgapr, @Takhion and @tikimcfee,

Sorry for my slow response.
If @sgapr 's solution works fine for this issue, could you please send PR?

**Comment by sgapr** [comment] 2016-08-25 07:26
@hideki Thanks for the fix.
@tikimcfee  You can use the feature branch created by @hideki, he has fixed it in a better way. Feel free to use our fork if needed, this is the only change of importance in our fork (branch mod130), other changes are just for getting it to build easily in our setup.

**Closed** 2016-08-25 22:03 UTC
Labels: cross-platform, P1: high, reproduce/investigate, review
