### ISSUE TITLE
Views seem to stop working: 1.3.0-45

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-android#950] opened 2016-07-29 13:13 UTC
After my app has been running a minute or so I seems that I can no longer query views from the REST API.  They queries never return, or error. I've left it a while, and some are currently at hundreds seconds with no response.  The local database isn't very big, maybe 300 documents with some attachments - maybe 12MB in size.

Here's a log go the app.  Right at the end, the app is completely idle, its just waiting for some queries to return and it logs out any that its been waiting for for a while:

https://gist.githubusercontent.com/npomfret/7f7094d95cebd67108187c161b51f1c2/raw/9ea7abadade3c35440403c6deef9002ca3d67a7a/couchbase%2520java%2520log.txt

**Comment by hideki** [comment] 2016-07-29 13:26
It seems 1.3.0-45 might cause dead-lock during queries.

I have a question and a request.
- How many queries are concurrently sent?
- Could you please take thread-dump with using Android Studio.

**Comment by npomfret** [comment] 2016-07-30 07:23
https://gist.github.com/npomfret/101dab44d0479c139ff6d1676208dbc2

**Comment by npomfret** [comment] 2016-07-30 08:06
Hi

Sorry, I don't think my issue is correct.  I think the deadlock is actually in my application.  I made a change due to the `_changes` feed not working as I expected (will raise a separate issue) and I think it's caused the problem.  Closing

**Comment by npomfret** [comment] 2016-07-31 13:42
I may have spoken too soon, it the db does seem to have locked up on me.  Here's the thread dump

https://gist.github.com/npomfret/8d42d1ce418a06bf5b4a25dc972c5362

**Comment by npomfret** [comment] 2016-07-31 14:29
I also saw this today:

```
07-31 15:23:31.760 21805-11531/com.pomochat I/Database: Db busy, retrying transaction (#1)...
07-31 15:23:33.929 21805-11531/com.pomochat I/Database: Db busy, retrying transaction (#2)...
07-31 15:23:36.099 21805-11531/com.pomochat I/Database: Db busy, retrying transaction (#3)...
07-31 15:23:38.269 21805-11531/com.pomochat I/Database: Db busy, retrying transaction (#4)...
07-31 15:23:40.439 21805-11531/com.pomochat I/Database: Db busy, retrying transaction (#5)...
07-31 15:23:42.609 21805-11531/com.pomochat I/Database: Db busy, retrying transaction (#6)...
07-31 15:23:44.783 21805-11531/com.pomochat I/Database: Db busy, retrying transaction (#7)...
07-31 15:23:46.949 21805-11531/com.pomochat I/Database: Db busy, retrying transaction (#8)...
07-31 15:23:49.119 21805-11531/com.pomochat I/Database: Db busy, retrying transaction (#9)...
07-31 15:23:51.289 21805-11531/com.pomochat I/Database: Db busy, retrying transaction (#10)...
07-31 15:23:53.458 21805-11531/com.pomochat E/Database: Db busy, too many retries, giving up
07-31 15:23:53.496 21805-11531/com.pomochat W/System.err: com.couchbase.lite.internal.database.sqlite.exception.SQLiteDatabaseLockedException: database is locked (code 5)
07-31 15:23:53.496 21805-11531/com.pomochat W/System.err:     at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
07-31 15:23:53.497 21805-11531/com.pomochat W/System.err:     at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:486)
07-31 15:23:53.497 21805-11531/com.pomochat W/System.err:     at com.couchbase.lite.internal.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:330)
07-31 15:23:53.498 21805-11531/com.pomochat W/System.err:     at com.couchbase.lite.internal.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:305)
07-31 15:23:53.498 21805-11531/com.pomochat W/System.err:     at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:499)
07-31 15:23:53.499 21805-11531/com.pomochat W/System.err:     at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:410)
07-31 15:23:53.499 21805-11531/com.pomochat W/System.err:     at com.couchbase.lite.storage.SQLiteStorageEngineBase.beginTransaction(SQLiteStorageEngineBase.java:150)
07-31 15:23:53.503 21805-11531/com.pomochat W/System.err:     at com.couchbase.lite.store.SQLiteStore.beginTransaction(SQLiteStore.java:2309)
07-31 15:23:53.503 21805-11531/com.pomochat W/System.err:     at com.couchbase.lite.store.SQLiteStore.open(SQLiteStore.java:235)
07-31 15:23:53.504 21805-11531/com.pomochat W/System.err:     at com.couchbase.lite.Database.open(Database.java:1251)
07-31 15:23:53.505 21805-11531/com.pomochat W/System.err:     at com.couchbase.lite.Database.open(Database.java:1185)
07-31 15:23:53.506 21805-11531/com.pomochat W/System.err:     at com.couchbase.lite.router.Router.openDB(Router.java:345)
07-31 15:23:53.506 21805-11531/com.pomochat W/System.err:     at com.couchbase.lite.router.Router.start(Router.java:474)
07-31 15:23:53.507 21805-11531/com.pomochat W/System.err:     at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141)
```

**Comment by hideki** [comment] 2016-08-02 01:29
Hi @npomfret,
Thank you very much for last two comments. They are helpful.  From the thread-dump, one of connection is waiting for SQLite Connection in `beginTransaction()`.
https://gist.github.com/npomfret/8d42d1ce418a06bf5b4a25dc972c5362#file-android-thread-dump-L82-L115. However it seems non of other threads is holding the SQLiteConnection. From LogCat message, it seems beginTransaction is waiting because of `SQLite Busy (DBBUSY)`.

Can you build CBL Android by your self? If yes, can you change line 67 in SQLiteStore.java?

From:
```
private static final int kTransactionMaxRetries = 10;
```
To:
```
private static final int kTransactionMaxRetries = 24;
```
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/store/SQLiteStore.java#L67

**Comment by hideki** [comment] 2016-08-02 01:30
ref: https://github.com/couchbase/couchbase-lite-android/issues/929

**Comment by hideki** [comment] 2016-08-02 01:48
CBL iOS waits maximum 50sec total.
```
#define kSQLiteBusyTimeout 5.0 // seconds

#define kTransactionMaxRetries 10
```

**Comment by pasin** [comment] 2016-08-02 03:56
I don't see kSQLiteBusyTimeout is used anywhere in iOS code.

**Comment by hideki** [comment] 2016-08-02 05:48
iOS uses FMDB. It seems FMDB set 2sec for timeout. 
```objective-c
_maxBusyRetryTimeInterval   = 2;
```
https://github.com/ccgus/fmdb/blob/master/src/fmdb/FMDatabase.m#L47

**Comment by pasin** [comment] 2016-08-02 16:33
This is interesting:
https://github.com/ccgus/fmdb/blob/master/src/fmdb/FMDatabase.m#L248

Also this blog post talks about usleep:
http://beets.io/blog/sqlite-nightmare.html

I think we don't compile sqlite with usleep=1 so we should make changes to the build script. I don't think usleep is going to fix the issue but it might help a bit.

**Comment by hideki** [comment] 2016-08-02 17:18
We need to review SQLite build option again.

SQLite build options that we are referencing:
https://github.com/android/platform_external_sqlite/blob/9e7798db1bf08daf62d97021a5cf1609ee3b81d3/dist/Android.mk

SQLite build options of marshmallow (Android 6.x):
https://github.com/android/platform_external_sqlite/blob/marshmallow-release/dist/Android.mk

**Comment by hideki** [comment] 2016-08-03 00:55
PRs for potential fix by compatible build options of SQLite with Android.
https://github.com/couchbase/couchbase-lite-java-native/pull/51
https://github.com/couchbaselabs/couchbase-lite-libsqlcipher/pull/15

**Comment by sethrosetter** [comment] 2016-08-12 23:00
@pasin Once this is resolved, we should add a regression suite for this.

**Comment by hideki** [comment] 2016-08-18 18:27
We applied fix to native libraries. It could fix this issue. So I will close this for now.
However, if the issue is still reproducible, please reopen the ticket?

**Closed by hideki** 2016-08-18 18:27 UTC
Labels: bug, in progress
