### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.couchbase.litecore.C4.getVersion() 

### ISSUE THREAD

**Issue by tapeo** [couchbase/couchbase-lite-android#1795] opened 2018-12-12 12:00 UTC
When app is installed in system crash. When I update it with manually it doesn't do anymore.

Stack trace:  
java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.couchbase.litecore.C4.getVersion() (tried Java_com_couchbase_litecore_C4_getVersion and Java_com_couchbase_litecore_C4_getVersion__)
 at com.couchbase.litecore.C4.getVersion(Native Method)
 at com.couchbase.lite.CBLVersion.getUserAgent(CBLVersion.java:32)
 at com.couchbase.lite.AbstractDatabase.<init>(AbstractDatabase.java:117)
 at com.couchbase.lite.Database.<init>(Database.java:35)

**Comment by pasin** [comment] 2018-12-12 16:15
Can you explain about `When app is installed in system crash`? What does it mean?

**Comment by tapeo** [comment] 2018-12-13 09:06
If the app is in the /system folder, the problem appear. If the app is simply installed there is no error.

**Comment by Mahan3340** [comment] 2019-03-12 13:58
when this bug is going to be fixed ?

**Comment by bmeike** [comment] 2019-03-12 16:20
I'm going to need more detail to be able to understand and reproduce this problem.

You cannot install an app in the system folder.  Do you mean `/system/app`?  Maybe `system/priv-app`?  That is a write only volume.  Are you installing an app that uses CB-Lite as part of the system?

Manual updates *always* go in `data/app`.  If you do a manual update, the app is no longer in /system/app.  That would explain why it works after an update.

**Comment by Mahan3340** [comment] 2019-03-12 16:46
@bmeike check this [1878](https://github.com/couchbase/couchbase-lite-android/issues/1878 , I'm having the same issue, but not produced in this way. The app simply will install on Emulators but won't start and crash with this exception
)

**Comment by bmeike** [comment] 2019-03-12 17:01
I've commented on #1878.  Again, I will need substantially more detail, there.  That issue is pretty clearly unrelated to this one.

**Comment by Mahan3340** [comment] 2019-03-12 17:09
@bmeike Okay this "No implementation found for java.lang.String com.couchbase.litecore.C4.getVersion()" was common between them thought they have the same origin, besides that this issue was the only thing found on the whole web pointing (partially) to this exception

**Comment by bmeike** [comment] 2019-03-15 19:41
Got it.  So...  Where, exactly, are you installing the app?  If it is on the system partition, how are you installing the app there?

It sounds like the problem is, incidentally, showing up in a CB library because initializing that class is one of the very first things that happens during class loading.  The root cause, however, is that your app can't find the Android Runtime environment.  That's weird...

**Comment by bmeike** [comment] 2019-03-15 19:45
Just noticed this.  It's probably the issue you are having: https://github.com/couchbase/couchbase-lite-android/issues/1769

**Comment by bmeike** [comment] 2019-03-15 19:51
Duplicate of https://github.com/couchbase/couchbase-lite-android/issues/1769

**Closed by bmeike** 2019-03-15 19:51 UTC
Labels: icebox

**Comment by SagarPatil04** [comment] 2019-03-21 10:27
#1795 marked duplicate of #1769 and #1769 marked duplicate of #1795
