### ISSUE TITLE
Compress (gzip) data uploaded by the replicator

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-android#168] opened 2014-01-16 19:47 UTC
Compressing the documents being uploaded by the replicator would be a significant win since JSON compresses really well, and devices are often on low-bandwidth networks. The Sync Gateway now (as of today) supports receiving such gzip-encoded request bodies.

Same as couchbase/couchbase-lite-ios#240 -- see the 3 commits there for reference.

**Comment by zgramana** [comment] 2015-01-16 19:18
Duplicate of couchbase/couchbase-lite-java-core#172

**Closed** 2015-01-16 19:18 UTC
Labels: enhancement, performance, S3: major
