### ISSUE TITLE
Exception in change tracker java.io.EOFException

### ISSUE THREAD

**Issue by atom992** [couchbase/couchbase-lite-android#777] opened 2016-02-06 16:13 UTC
I am using couchbase-lite-android 1.2.0-null on Android 5.0.1 with sync_gateway 1.2.0, And I found the following error log:
```
ChangeTracker  W  com.couchbase.lite.replicator.ChangeTracker@e0989ee: Exception in change tracker
               W  java.io.EOFException
               W      at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:169)
               W      at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:140)
               W      at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.loadMore(UTF8StreamJsonParser.java:180)
               W      at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd2(UTF8StreamJsonParser.java:2777)
               W      at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:2772)
               W      at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:652)
               W      at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserialize
                  r.java:443)
               W      at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:473)
               W      at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:330)
               W      at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:25)
               W      at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3560)
               W      at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2646)
               W      at com.couchbase.lite.replicator.ChangeTracker.runLoop(ChangeTracker.java:350)
               W      at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:226)
               W      at java.lang.Thread.run(Thread.java:818)
```

**Comment by hideki** [comment] 2016-02-06 18:59
Hi @atom992,
Thank you very much for your bug report. It seems Gzipped response from sync_gateway was truncated. Did CBL recover from this error?
/Hideki

**Comment by atom992** [comment] 2016-02-06 20:20
yes, I am not find any sync issue. but I am not sure if this error cause potential issue.

**Comment by hideki** [comment] 2016-02-06 21:21
I assume Gzipped response from sync_gateway was truncated. This could be caused by network issue or sync_gateway issue, or something else. If CBL can not recover from this error, it is bug.

I know stacktrace might make developer to worry. We will update logging message for this.

Thanks!

**Comment by hideki** [comment] 2016-02-06 21:40
I will close this. If you observe this exception frequently, please reopen this.

**Comment by atom992** [comment] 2016-03-13 06:26
Hi, I collected more info post here:
log:
```
                        [37;100m V [0m com.couchbase.lite.replicator.ChangeTracker@22c09861: Making request to http://10.1.1.1/sgdb/_changes
                        [37;100m V [0m com.couchbase.lite.replicator.ChangeTracker@22c09861: got response. status: HTTP/1.1 200 OK mode: LongPoll
                        [37;100m V [0m com.couchbase.lite.replicator.ChangeTracker@22c09861: /entity.getContent().  mode: LongPoll
                        [37;100m V [0m com.couchbase.lite.replicator.ChangeTracker@22c09861: readValue
                        [30;103m W [0m com.couchbase.lite.replicator.ChangeTracker@22c09861: Exception in change tracker
                        [30;103m W [0m java.io.EOFException
                        [30;103m W [0m     at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:169)
                        [30;103m W [0m     at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:140)
                        [30;103m W [0m     at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.loadMore(UTF8StreamJsonParser.java:180)
                        [30;103m W [0m     at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd2(UTF8StreamJsonParser.java:2777)
                        [30;103m W [0m     at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:2772)
                        [30;103m W [0m     at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:652)
                        [30;103m W [0m     at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:443)
                        [30;103m W [0m     at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:473)
                        [30;103m W [0m     at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:330)
                        [30;103m W [0m     at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:25)
                        [30;103m W [0m     at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3560)
                        [30;103m W [0m     at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2646)
                        [30;103m W [0m     at com.couchbase.lite.replicator.ChangeTracker.runLoop(ChangeTracker.java:358)
                        [30;103m W [0m     at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:228)
                        [30;103m W [0m     at java.lang.Thread.run(Thread.java:818)
```

HTTP Request/Response:
```
POST /sgdb/_changes HTTP/1.1
Content-Type: application/json
User-Agent: CouchbaseLite/1.2 (1.2.0/3fa390b596672fa39243cb9f3457c276eb53707b)
Accept-Encoding: gzip
Cookie: SyncGatewaySession=ddc9087a6c876ab1bf72e82bf1dd31079c71557d
Content-Length: 100
Host: 10.1.1.1
Connection: Keep-Alive

{"style":"all_docs","heartbeat":300000,"feed":"longpoll","active_only":null,"limit":50,"since":9249}HTTP/1.1 200 OK
Date: Sun, 13 Mar 2016 05:08:26 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
cache-control: private, max-age=0, no-cache, no-store
content-encoding: gzip
server: Couchbase Sync Gateway/1.2.0

1e
‹
```

Hope it can helps.

**Comment by hideki** [comment] 2016-05-02 19:11
Hi @atom992,

From information you provided, I am not sure where problem is.
I am wondering if you use proxy server between CBL and Sync Gateway, and it might close connection.
We needs more information about this issue!

Thanks!

**Comment by atom992** [comment] 2016-05-03 03:24
yes, there is a nginx server before Sync Gateway, but I am using [this](http://developer.couchbase.com/documentation/mobile/1.2/develop/guides/sync-gateway/nginx/configuring-nginx-for-sync-gateway/index.html) to deploy proxy server.

**Comment by hideki** [comment] 2016-05-03 04:09
Hi @atom992,
Could you please test without proxy server? If it works fine without proxy, I believe issue is proxy server configuration or bug in proxy server.
Thanks!

**Comment by atom992** [comment] 2016-05-03 04:17
When I used forestDb as store, this issue is not appear.
I will do more test while I am using SQLite as store.

**Comment by hideki** [comment] 2016-06-02 22:13
@atom992,
Do you have any update about this issue?
If not, I'd like to close the ticket.
Thanks!

**Comment by hideki** [comment] 2016-06-08 18:58
As we don't have additional information to investigate this issue further, so I will close this ticket. Please reopen the ticket if you still encounter this issue.

**Closed** 2016-06-08 18:58 UTC
Labels: needsmoreinfo, reproduce/investigate
