### ISSUE TITLE
Regression: SQLiteException: no such table: maps_1 (code 1)

### ISSUE THREAD

**Issue by mtrakal** [couchbase/couchbase-lite-android#1080] opened 2017-02-24 13:08 UTC
We had this issue in some previous CBL (think that in `1.2.1`). Our app version: 3.6
But it's back after upgrade from `1.3.1-91` to `1.4.4x`. Our app version 4.4

http://crashes.to/s/fa605cc8295
Note to self: 5702f8d9ffcdc042506d114f

```java
Fatal Exception: java.lang.RuntimeException: Unable to create application com.droid4you.application.wallet.Application: com.couchbase.lite.internal.database.sqlite.exception.SQLiteException: no such table: maps_1 (code 1): , while compiling: SELECT key, value, docid, revs.sequence FROM 'maps_1', revs, docs WHERE 1 AND revs.sequence = 'maps_1'.sequence AND docs.doc_id = revs.doc_id ORDER BY key, docid LIMIT ? OFFSET ?
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4687)
       at android.app.ActivityThread.access$1400(ActivityThread.java:159)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:5419)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by com.couchbase.lite.internal.database.sqlite.exception.SQLiteException: no such table: maps_1 (code 1): , while compiling: SELECT key, value, docid, revs.sequence FROM 'maps_1', revs, docs WHERE 1 AND revs.sequence = 'maps_1'.sequence AND docs.doc_id = revs.doc_id ORDER BY key, docid LIMIT ? OFFSET ?
       at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
       at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:718)
       at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:431)
       at com.couchbase.lite.internal.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:595)
       at com.couchbase.lite.internal.database.sqlite.SQLiteProgram.(SQLiteProgram.java:64)
       at com.couchbase.lite.internal.database.sqlite.SQLiteQuery.(SQLiteQuery.java:37)
       at com.couchbase.lite.internal.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:48)
       at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1300)
       at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1239)
       at com.couchbase.lite.storage.SQLiteStorageEngineBase.rawQuery(SQLiteStorageEngineBase.java:183)
       at com.couchbase.lite.store.SQLiteViewStore.runQuery(SQLiteViewStore.java:1014)
       at com.couchbase.lite.store.SQLiteViewStore.regularQuery(SQLiteViewStore.java:627)
       at com.couchbase.lite.View.query(View.java:358)
       at com.couchbase.lite.Database.queryViewNamed(Database.java:2469)
       at com.couchbase.lite.Query.run(Query.java:446)
```

Maybe relevant?  #880, #966, #1008

**Comment by hideki** [comment] 2017-02-24 19:16
Hi @mtrakal,

Based on an error message, `no such table: maps_1 (code 1):`, it seems the issue is related with Arabic issue we fixed. As error message say `maps_1`, so it indicates that table name generations is fine. I guess that the table was created with previous version of CBL which has Arabic issue,  then upgrade to new one. Then new one try to query, but it can not find map_1 table.

**Comment by mtrakal** [comment] 2017-02-25 20:20
Looks, that users are really Arabic old users. No new users, but have no idea why it start crashing after upgrade to `1.4.4x`, because we have there workaround for migration: https://github.com/couchbase/couchbase-lite-android/issues/966#issuecomment-241646746

**Comment by hideki** [comment] 2017-02-26 01:16
@mtrakal Thanks for your inputs.

- The user uses the app with the old version of CBL which has the bug with Arabic, it created `maps_١` table.
- The user upgraded the app that includes the newer version of CBL which has the fix. Also, the app increased the view version number to `2` from `1`, I believe it recreates map table with `maps_1` table name.
- However, `maps_1` tables does not exist.... SQLiteException...

I guess that view query could be executed before maps table is recreated.

**Comment by djpongh** [comment] 2017-03-10 22:21
@sethrosetter @raghusarangapani is there a way to run our functional tests with Arabic locale?

**Comment by raghusarangapani** [comment] 2017-03-10 23:04
@hideki Do you know how to enable Arabic locale?

**Comment by hideki** [comment] 2017-03-10 23:17
@raghusarangapani 
[Settings] ->[Lanugage & Input]  -> [Language]

**Comment by raghusarangapani** [comment] 2017-03-24 23:19
I ran the testsuites/listener/shared/client_sg/test_views.py (which calls  /{db}/_design/{doc}) on nexus 6p with Android 7.1.1 with English(US) and Arabic. The test passed, no issues.

**Comment by sethrosetter** [comment] 2017-03-24 23:21
@raghusarangapani Is it easy for you to kick of the whole `client_sg` suite?

**Comment by raghusarangapani** [comment] 2017-03-24 23:57
Ran the entire client_sg suite against nexus 6p with Android 7.1.1 and Arabic locale. The test passed, no issues.

**Comment by hideki** [comment] 2017-03-25 04:45
As test pass, I will close this.

**Closed** 2017-03-25 04:45 UTC
