### ISSUE TITLE
`SelectResult.all().from("xxx")` should work with Join ?

### ISSUE THREAD

**Issue by AlBlanc** [couchbase/couchbase-lite-android#1413] opened 2017-10-10 18:30 UTC
Hello,

I don't know if this is a bug or a misuse of the library, I am trying to build a CBL query which should be the equivalent of `SELECT user.* FROM friend JOIN user ON friend.user_id = user.id`. 
I figured out a way to make it works but not really convenient to use, the problem is: We must specify explicitely all the fields we want to retrieve:
```
LiveQuery friendsQuery = Query.select(
    SelectResult.expression(Expression.property("user_id").from("friendship")),
    SelectResult.expression(Expression.property("id").from("user")),
    SelectResult.expression(Expression.property("full_name").from("user")))
    .from(DataSource.database(mDatabase).as("friendship"))
    .join(Join.join(DataSource.database(mDatabase).as("user"))
    .on(Expression.property("user_id").from("friendship").equalTo(Expression.property("id").from("user"))))
    .where(Expression.property("type").from("friendship").equalTo("friend")
    .and(Expression.property("type").from("user").equalTo("user")))
    .toLive();
```

We've tried: `SelectResult.all().from("friendship")` but it returns a null `LiveQueryChange` object in the `LiveQueryChangeListener`

Second point:
 I would like to Join on document ID, as you can see in the previous query, I made the join on the `id` document field, but we should be able to make join on the document ID, aren't we?
I tried the following join but it returns me a null result (In the `LiveQueryChangeListener`):
```
  .join(Join.join(DataSource.database(mDatabase).as("user"))                                      
  .on(Expression.property("user_id").from("friendship").equalTo(Expression.meta().getId())))

```

**Comment by hideki** [comment] 2017-10-11 00:49
Hi @AlBlanc 
I wrote the simple unit test for JOIN with Select.ALL query. I could not reproduce the problem that returns `null` for the joined data source.
https://github.com/couchbase/couchbase-lite-android/blob/feature/2.0/android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/QueryTest.java#L1676-L1718

**Comment by AlBlanc** [comment] 2017-10-11 09:48
Thank you @hideki, I am going to reproduce your query today. I'll come back asap. About the null values, how can i help you to reproduce the issue? I can't share you the whole project source code but I can share you my screen maybe?

What about the join on document IDs? Can we do it or we can make join only on document fields?

**Comment by hideki** [comment] 2017-10-11 19:40
Hi @AlBlanc,

About Join on document ID case, in your sample query, it needs to specify the data source name.
-> `Expression.meta().getId().from("<HERE>")`

I wrote sample Join query on document ID. Please refer it.
https://github.com/couchbase/couchbase-lite-android/blob/a460f205cdf59cfb617ab2b1df2ae62685b5b40f/android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/QueryTest.java#L1720-L1760

**Comment by hideki** [comment] 2017-10-11 19:43
Hi @AlBlanc,
Regarding `null` result issue for `SelectResult.all()`, can you share the query code?

**Comment by hideki** [comment] 2017-10-16 20:07
Hi @AlBlanc,
Do you have any update on this issue?

**Comment by AlBlanc** [comment] 2017-10-17 07:35
Hi,

I don't have my laptop with me, let me try tonight with your latest release.

**Comment by hideki** [comment] 2017-10-24 21:44
Hi @AlBlanc,
I will close this ticket. If you still encounter the problem, could you please reopen the ticket?

**Closed by hideki** 2017-10-24 21:44 UTC
Labels: ready
