### ISSUE TITLE
Query enumeration error: LiteCoreException

### ISSUE THREAD

**Issue by gsdigital2017** [couchbase/couchbase-lite-android#1755] opened 2018-09-02 04:14 UTC
According to the docs, following is the code snippet on Query. **This is not working and gives Query enumeration error: LiteCoreException{domain=5, code=2, msg=array/iterator index out of range: iterating past end of array}**

Query query = QueryBuilder
    .select(SelectResult.expression(Meta.id),
        SelectResult.property("name"),
        SelectResult.property("type"))
    .from(DataSource.database(database))
    .where(Expression.property("type").equalTo(Expression.string("hotel")))
    .orderBy(Ordering.expression(Meta.id));

try {
    ResultSet rs = query.execute();
    for (Result result : rs) {
        Log.i("Sample", String.format("hotel id -> %s", result.getString("id")));
        Log.i("Sample", String.format("hotel name -> %s", result.getString("name")));
    }
} catch (CouchbaseLiteException e) {
    Log.e("Sample", e.getLocalizedMessage());
}

______________________________________________________________________________________________________________
**However, following is working:**

Query query = QueryBuilder
    .select(SelectResult.expression(Meta.id),
        SelectResult.property("name"),
        SelectResult.property("type"))
    .from(DataSource.database(database))
    .where(Expression.property("type").equalTo(Expression.string("hotel")))
    .orderBy(Ordering.expression(Meta.id));

try {
    ResultSet rs = query.execute();
    List<Result> listResult = rs.allResults();
    for (Result row : listResult) {
        Log.i("Sample", String.format("hotel id -> %s", row.getString("id")));
        Log.i("Sample", String.format("hotel name -> %s", row.getString("name")));
    }
} catch (CouchbaseLiteException e) {
    Log.e("Sample", e.getLocalizedMessage());
}

**Comment by pasin** [comment] 2018-09-06 04:45
For some reason, I'm not able to reproduce the issue. Also the [QueryTest](https://github.com/couchbase/couchbase-lite-android/blob/master/android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/QueryTest.java#L72-L79) has always verified the fast iteration with the ResultSet.

Is it possible that the ResultSet has been iterated more than one time or the ResultSet.next() is called before using for-loop to iterate?

**Comment by gsdigital2017** [comment] 2018-09-06 08:06
I encountered the following thread.

https://github.com/couchbase/couchbase-lite-android/issues/1604

Check the comment from the bottom.

**Comment by pasin** [comment] 2018-10-30 17:57
The following code could reproduce the issue:

```Java
for (ResultSet resultSet : resultSets){
            List<Result> allResults = resultSet.allResults();
            for (Result result : allResults){
                
            }
        }
```

**Comment by djpongh** [comment] 2019-01-04 23:18
@pasin , can we close this then?

**Comment by pasin** [comment] 2019-01-16 21:15
I have made sure that there will be no error shown in the log when trying to re-enumerate the query result set after all results have been enumerated. Instead, there will be a warning massage in the log. We can close the issue now.

**Closed by pasin** 2019-01-16 21:15 UTC
Labels: P1: high, backlog, bug, ffc
