### ISSUE TITLE
doc update is not getting replicated when android is in offline

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-android#1664] opened 2018-03-15 21:01 UTC
### Environment 
* Version:   IOS 702 | Android 2.0.0-435
* Client OS: Todo app , ios 
* Server:    sg - 823 [config](https://gist.github.com/tleyden/533d4a180af8962669c554332b7e54b3)

### steps to reproduce : 
1. login to todo app on ios and android as two differrent users.
1. Take ios offline (wifi off), 
1. create list on android
1. share list with ios user
1. Create doc in android 
1. Get ios online(wifi on), doc will get replicated to ios 
1. update doc in android

Result : Doc does not get updated on ios . Try updating the doc on ios, it won't get replicated to android.

I tried same steps with android offline and created doc in ios i,e vice versa of same steps as above and it worked fine and works as expcted.

### cbl logs : 
Android : https://gist.github.com/sridevi-15/8ccefb9ba712f16378885d23708143c1
ios : https://gist.github.com/sridevi-15/8e394aae381c04ab5bf7085d8793dc88

## sg logs : 
https://gist.github.com/sridevi-15/13f7a7ba8aba7cbf04b9881c4fb4481b

 I also tried ios to ios i.e ios simulator to ios device with ios device offline -> it passed
I tried android to android i.e android emulator to android device with android device offline -> it failed.

I also tried ios device with android emulator having ios device offline -> it failed. but not all the time, sometime with update on emulator did not replicated on device, but sometime it replicated.

I am attaching logs for Android and sg logs.

android logs : https://gist.github.com/sridevi-15/f5842c82562ae66afd7675ae58b07d2a
sg logs : https://gist.github.com/sridevi-15/263d0f40309777222d61ff934d1dccd8

**Comment by tleyden** [comment] 2018-03-16 21:10
Updated ticket to have android version: Android 2.0.0-435

**Comment by tleyden** [comment] 2018-03-16 23:50
I was able to repro under these conditions:

- Run SG in AWS
- Using an ios device (as opposed to simulator)
- Android emulator

**Comment by tleyden** [comment] 2018-03-19 19:21
From what I can tell, the cblite android client is getting rejected by sync gateway when it tries to send the revision of the doc after the checkbox is checked.  It looks like it's getting a 409 error in response to the `ProposeChanges` request, and not retrying.

I'm still trying to figure out why it's getting the 409 response.

It doesn't show clearly in the SG logs:

```
2018-03-19T19:10:15.714Z SyncMsg: [523efe64] #017: Type:proposeChanges #Changes: 1 User:hideki
2018-03-19T19:10:15.715Z SyncMsg+: [523efe64] #017: Type:proposeChanges   --> OK Time:897.199µs User:hideki
```

but I can see it in the blip wireshark trace:

![screen shot 2018-03-19 at 12 19 04 pm](https://user-images.githubusercontent.com/296876/37617300-fb4535f0-2b6f-11e8-924e-fb89c119a994.png)

Full sg logs: https://gist.github.com/tleyden/53ad297da4b08cf767c11d157081d45c

**Comment by tleyden** [comment] 2018-03-19 19:42
Looks like cblite-android is not sending the parent revid in this case, which causes SG to reject the update.  

SG logs:

```
2018-03-19T19:39:45.424Z SyncMsg: [2df068bf] #021: Type:proposeChanges #Changes: 1 User:hideki
2018-03-19T19:39:45.424Z CRUD+: CheckProposedRev docid: "3ceb2a13-1fb9-4481-9c01-a2466a8d9c6d" revid: "2-6499ad90e2d892447072bbd7ccc0602e5b5db659" parentRevId: ""
2018-03-19T19:39:45.425Z CRUD+: CheckProposedRev returning ProposedRev_Conflict since parent revision mismatch. docid: "3ceb2a13-1fb9-4481-9c01-a2466a8d9c6d" revid: "2-6499ad90e2d892447072bbd7ccc0602e5b5db659" parentRevId: "".  Doc in db: &{syncData:{CurrentRev:1-1f00b72146d9f0eb70c37da1a6ebf690adb354a7 NewestRev: Flags:0 Sequence:37 UnusedSequences:[] RecentSequences:[37] History:map[1-1f00b72146d9f0eb70c37da1a6ebf690adb354a7:0xc420c6bda0] Channels:map[moderators:<nil> task-list.hideki.1832a451-939b-4830-992c-318e1ace96bc:<nil>] Access:map[] RoleAccess:map[] Expiry:<nil> Cas:0x0000c9978d691d15 TombstonedAt:0 UpstreamCAS:<nil> UpstreamRev: TimeSaved:2018-03-19 19:38:25.979406137 +0000 UTC Deleted_OLD:false addedRevisionBodies:[] removedRevisionBodyKeys:map[]} _body:map[task:hidekilist7taskA taskList:map[owner:hideki id:hideki.1832a451-939b-4830-992c-318e1ace96bc] type:task _deleted:false complete:false createdAt:2018-03-19T19:38:25.074Z] rawBody:[] ID:3ceb2a13-1fb9-4481-9c01-a2466a8d9c6d Cas:152
```

**Comment by tleyden** [comment] 2018-03-19 19:54
I tried to repro the same steps but using an ios simulator instead of an android emulator, but could not repro.  Looks to be specific to cblite android.

**Comment by tleyden** [comment] 2018-03-19 20:55
Updated repro steps

### Environment 
* Version: Android 2.0.0-435
* Client app: Todo app android
* Server:    sg - 823 [config](https://gist.github.com/tleyden/533d4a180af8962669c554332b7e54b3)

### steps to reproduce : 
1. login to todo app android 
1. create list on android
1. Create doc in android 
1. update doc in android

Result : The initial doc will get pushed to sync gateway, but updates will be rejected w/ the error mentioned in https://github.com/couchbase/couchbase-lite-android/issues/1664#issuecomment-374343980

**Comment by tleyden** [comment] 2018-03-19 23:17
After adding the doc in android, I see this log message:

```
03-19 23:03:09.980 11755 11835 I LiteCore [Sync]: {DBWorker#4} Marking rev 'a51006d4-c2e2-4e54-a191-6fe19600bd59' 1-9371a57be5f40e41816c50c2996b7514e195bf9c (#47) as current for remote db 1
```

and then verified that SG has that revision.

However, after making another update, I see:

```
03-19 23:15:04.338 11755 11836 I LiteCore [Sync]: {DBWorker#4} remoteRevID of 'a51006d4-c2e2-4e54-a191-6fe19600bd59' is
```

where it seems to have forgotten about the remoteRevId, which corresponds to what I'm seeing on the SG side as described in https://github.com/couchbase/couchbase-lite-android/issues/1664#issuecomment-374343980

**Comment by hideki** [comment] 2018-03-19 23:29
@tleyden 

`remoteRevID` is not set yet when calling `logDebug("remoteRevID of '%.*s' is %.*s", SPLAT(doc->docID), SPLAT(remoteRevID));`

need to call after line of `remoteRevID = alloc_slice(foreignAncestor);`?
```
bool DBWorker::addChangeToList(const C4DocumentInfo &info, C4Document *doc, vector<Rev> &changes) {
        alloc_slice remoteRevID;
        if (_getForeignAncestors && _checkpointValid) {
            // For proposeChanges, find the nearest foreign ancestor of the current rev:
            Assert(_remoteDBID);
            c4::sliceResult foreignAncestor( c4doc_getRemoteAncestor(doc, _remoteDBID) );
            logDebug("remoteRevID of '%.*s' is %.*s", SPLAT(doc->docID), SPLAT(remoteRevID));
            if (_skipForeignChanges && foreignAncestor == slice(info.revID))
                return false;   // skip this rev: it's already on the peer
            remoteRevID = alloc_slice(foreignAncestor);
        }
        changes.emplace_back(info, remoteRevID);
        return true;
    }
```

**Comment by tleyden** [comment] 2018-03-19 23:38
Thanks @hideki, I noticed that too .. but ignored it since I could see that `foreignAncestor` was a 0 length slice in the debugger.  Changing the log to:

```
            c4::sliceResult foreignAncestor( c4doc_getRemoteAncestor(doc, _remoteDBID) );
            // log("remoteRevID of '%.*s' is %.*s", SPLAT(doc->docID), SPLAT(remoteRevID));
            if (_skipForeignChanges && foreignAncestor == slice(info.revID))
                return false;   // skip this rev: it's already on the peer
            remoteRevID = alloc_slice(foreignAncestor);
            log("remoteRevID of '%.*s' is %.*s", SPLAT(doc->docID), SPLAT(remoteRevID));
```

gives the same result:

```
03-19 23:34:49.548 12270 12350 I LiteCore [Sync]: {DBWorker#4} remoteRevID of 'a51006d4-c2e2-4e54-a191-6fe19600bd59' is
```

**Comment by tleyden** [comment] 2018-03-20 00:33
## Verifying the `markSynced` behavior

After adding the first revision of a doc, I see this in the cblite logs:

```
03-20 00:21:44.149 13457 13591 I LiteCore [Sync]: {DBWorker#4} Marking rev 'ec343966-76fd-4881-9661-4ea1b068b4a9' 1-95795445f7225fb856500d1108c2025d0794de3c (#56) as current for remote db 1
```

and if I curl that document on Sync Gateway port 4985, I get:

```
$ http GET 'http://$host:4985/todo/ec343966-76fd-4881-9661-4ea1b068b4a9?attachments=false&atts_since=&open_revs=&revs=false&show_exp=false'  ... 

HTTP/1.1 200 OK
Content-Length: 293
Content-Type: application/json
Date: Tue, 20 Mar 2018 00:31:00 GMT
Etag: "1-95795445f7225fb856500d1108c2025d0794de3c"
Server: Couchbase Sync Gateway/2.0 branch/feature/cblite_android_issue_1664 commit/96ca446+CHANGES

{
    "_deleted": false,
    "_id": "ec343966-76fd-4881-9661-4ea1b068b4a9",
    "_rev": "1-95795445f7225fb856500d1108c2025d0794de3c",
    "complete": false,
    "createdAt": "2018-03-20T00:21:34.884Z",
    "task": "hidekilist11TaskH",
    "taskList": {
        "id": "hideki.25397cf3-05ec-4cb2-a811-e5e73bb75032",
        "owner": "hideki"
    },
    "type": "task"
}
```

however, `cblite` doesn't indicate that the latest rev has been updated on the remote:

```
$ cblite revs hideki.cblite2 ec343966-76fd-4881-9661-4ea1b068b4a9
Document "ec343966-76fd-4881-9661-4ea1b068b4a9"
 * 1-95795445f7225fb856500d1108c2025d0794de3c     ----KL #56, 140 bytes  [CURRENT]
```

**Comment by tleyden** [comment] 2018-03-20 01:14
Update from working w/ @snej over hipchat:

Looking at the raw doc in sqlite3 shows that the flag is set to 8, which means that doc has been sync'd to the remote:

```
sqlite> SELECT * FROM kv_default WHERE key='d4f3179c-81d1-4887-9d3d-81cefdc8ca6f';
'd4f3179c-81d1-4887-9d3d-81cefdc8ca6f',57,8,X'0119f0b63658c1c8b86ae2b447aa0608b65a900e27',X'000000aaffff82150119f0b63658c1c8b86ae2b447aa0608b65a900e27004f11686964656b694c69737431315461736b4900447461736b004f18323031382d30332d32305430303a34323a35392e3132365a4f2b686964656b692e32353339376366332d303565632d346362322d613831312d6535653733626237353033320046686964656b69007002000180060004801f70050002803200038009000634000007803500088044800b00000000'
```

however emitting the doc via `cblite` doesn't show the latest (and only) revision as being pushed to the remote:

```
$ cblite revs hideki.cblite2 d4f3179c-81d1-4887-9d3d-81cefdc8ca6f
Document "d4f3179c-81d1-4887-9d3d-81cefdc8ca6f"
* 1-19f0b63658c1c8b86ae2b447aa0608b65a900e27     ----KL #57, 140 bytes  [CURRENT]
```

Also it's worth noting that Hideki was able to reproduce serious issues as well, where a user could not pull their own data replicated from Sync Gateway, but he was not able to repro the issue when running SG locally.  I also saw similar behavior as I was not able to initially repro this issue until I switched to the SG that @sridevi-15 had setup on AWS.

Hideki's config: https://github.com/couchbaselabs/mobile-training-todo/blob/feature/2.0/objc/sync-gateway-config.json (local SG + walrus mode.)

**Comment by hideki** [comment] 2018-03-20 01:59
I tested this scenario with the environment which has SG build 823 and CBS 5.1.0 on the local computer. However, I could not reproduce this. I am wondering if CBS on AWS is bad state or something?

**Comment by snej** [comment] 2018-03-20 04:30
My apologies -- I forgot you have to use the `--remotes` flag to get `cblite revs` to show info on remotes. Using that flag, it's showing the right info:
```
Document "d4f3179c-81d1-4887-9d3d-81cefdc8ca6f"
* 1-19f0b63658c1c8b86ae2b447aa0608b65a900e27     ----KL #57, 140 bytes  [CURRENT]  [REMOTE#1]
[REMOTE#1] = ws:ec2-174-129-56-140.compute-1.amazonaws.com:4984/todo/_blipsync
```

**Comment by tleyden** [comment] 2018-03-20 04:39
In a recent repro run, doc `ba0a53f6-07f0-44af-b0d3-f0b7fe02391c` had it's 2nd update rejected by `proposeChanges` w/ 409 errors, while another doc `9c42819d-02a6-4acc-979c-c7096b71f06c` was able to successfully push updated revs.

This was reflected in the `cblite revs --remotes` output for each doc:

```
$ cblite revs --remotes hideki.cblite2 ba0a53f6-07f0-44af-b0d3-f0b7fe02391c
Document "ba0a53f6-07f0-44af-b0d3-f0b7fe02391c"
 * 1-ff15b1f7a61dc3cf8b260883927fc5994a661d66     ------ #62
   * 2-78d3156136b9f61150fbe8f7abf2ac248e1472b0   -----L #63, 126 bytes  [CURRENT]
```

vs:

```
$ cblite revs --remotes hideki.cblite2 9c42819d-02a6-4acc-979c-c7096b71f06c
Document "9c42819d-02a6-4acc-979c-c7096b71f06c"
 * 1-2df62746371b09ace270508efe8ab43aae01dc0a     ------ #60, 126 bytes
   * 2-7d097b094e2501865dabaa71a250e1d9422295f9   ----KL #61, 126 bytes  [CURRENT]  [REMOTE#1]
[REMOTE#1] = ws:ec2-174-129-56-140.compute-1.amazonaws.com:4984/todo/_blipsync
```

Full SG logs:
https://gist.githubusercontent.com/tleyden/90d602476abdc20c36a3ee0dbfc11b88/raw/cbb8d2859a7dc84a3730ec20afa2c9a286890025/gistfile1.txt

Packet capture **Profile:proposeChanges** for rev gen 2:

```
BLIP Couchbase Mobile
    BLIP Message Number: 16
    BLIP Frame Flags: 0
    BLIP Properties Length: 23
    BLIP Properties: Profile:proposeChanges
    BLIP Message Body: [["9c42819d-02a6-4acc-979c-c7096b71f06c","2-7d097b094e2501865dabaa71a250e1d9422295f9","1-2df62746371b09ace270508efe8ab43aae01dc0a",126]]

```

and 

```
BLIP Couchbase Mobile
    BLIP Message Number: 24
    BLIP Frame Flags: 0
    BLIP Properties Length: 23
    BLIP Properties: Profile:proposeChanges
    BLIP Message Body: [["ba0a53f6-07f0-44af-b0d3-f0b7fe02391c","2-78d3156136b9f61150fbe8f7abf2ac248e1472b0","",126]]

```

**Comment by snej** [comment] 2018-03-20 04:51
I'm pretty sure the problem is that `c4doc_update` is clobbering the `kSynced` flag. CBL already has a C4Document in memory from the first time it saved, so the second time it saves it just passes that to `c4doc_update`. That function does use the sequence number to conditionally save and detect a conflict; but setting the `kSynced` flag doesn't change the sequence in the db, so the update doesn't know it's just overwritten that flag.

Fixing this isn't rocket science, but I'll have to think of the cleanest way to do it. Tomorrow...

**Comment by snej** [comment] 2018-03-20 18:10
Closing this, since the issue is down in LiteCOre.

**Closed by snej** 2018-03-20 18:10 UTC
Labels: P1: high, ready

**Comment by hideki** [comment] 2018-03-21 00:56
@sridevi-15 
please verify the bug fix with http://mobile.maven.couchbase.com/feeds/dev//com/couchbase/lite/couchbase-lite-android/2.0.0-453

**Comment by sridevi-15** [comment] 2018-03-22 23:47
Tested with build 454. Issue is fixed and works as expected
