### ISSUE TITLE
very slow replication (build 1.3.0-33)

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-android#946] opened 2016-07-15 11:39 UTC
My app is syncing only about 4000 documents with a few attachments.  The db size is less that 4Mb but it takes it over a minute to sync.  The sync gateway is running locally, so this isn't even over the internet.  As my app grows this isn't going to be viable.  The equivalent in iOS takes barely a couple f seconds.

**Comment by hideki** [comment] 2016-07-15 16:00
By our internal performance testing, CBL Android's pull replication is around 50% slower with 1000 documents without an attachment. We will measure pull replication performance with attachments.

**Comment by prasannakumark** [comment] 2016-07-20 06:13
+1

**Comment by npomfret** [comment] 2016-07-21 11:27
My gut feeling, although I don't yet have the figures to back it up is there are orders of magnitude difference.  My iphone seems to be able to sync over wifi to a server on the internet at around 2 mega bytes per second. An android phone seems to take about 20 seconds or more to sync a single mega byte.  No the phones aren't identical obviously, the iPhone is a lot more powerful.  But they are connecting to the same server, over the same network.

**Comment by hideki** [comment] 2016-08-19 20:26
Hi @npomfret,

I measured the pull replication performance with following condition.

- Devices: Nexus 5, 6, and 9 (All Android: 6.0.1)
- Sync Gateway: 1.2.1 which is installed on local OSX machine.
- Network: Office Wifi
- Test code:
https://github.com/couchbase/couchbase-lite-android/blob/c690c74581a5d79d32678b3582ecec5d51283def/src/androidTest/java/com/couchbase/lite/performance/Test07_PullReplication.java
- Number of documents: 4000
- document size is 1000 (Main part is 500 character, 2 text attachments (250 character each))
- Total size is around 4MB.

Note: This is just measured pull replication elapsed time.

Results:
```
Nexus 5 (32bit) - Android 6.0.1 (API23)
PullReplicationPerformance: PerformanceStats: 41115 msec (4000, 500, 2, 250)

Nexus 6 (32bit) - Android 6.0.1 (API23)
PullReplicationPerformance: PerformanceStats: 35440 msec (4000, 500, 2, 250)

Nexus 9 (64bit) - Android 6.0.1 (API23)
PullReplicationPerformance: PerformanceStats: 28740 msec (4000, 500, 2, 250)
``` 

Around 30 - 40 seconds for 4000 documents with few attachments are expected time.

Question: How did you measure your performance?

Thanks!
Hideki

**Comment by npomfret** [comment] 2016-08-19 22:55
I've not done anything that accurate but I will try and get some done over the weekend and let you know.

**Comment by pasin** [comment] 2016-08-22 19:26
I have run the same test with CBL iOS 1.3.0 (iPhone 6, iOS 9.3.4) and SGW 1.3. iOS took around 60 - 70 seconds to finish the pull. So for this case, Android seems to run faster. Probably the issue is not at the replication.

**Comment by hideki** [comment] 2016-08-22 21:01
@npomfret and @prasannakumark,

According to our internal performance testing, the pull replication itself is not slow. 
As you use REST API, I guess slowness comes from CBL Router codes, Web server CBL is using. If you could identify, it is great.

I will close this ticket. Please open new ticket if you could find performance bottleneck.

Thanks!

**Closed by hideki** 2016-08-22 21:01 UTC
Labels: bug, enhancement, reproduce/investigate, review
