### ISSUE TITLE
MainActivity has leaked IntentReceiver com.couchbase.lite.android.AndroidNetworkReachabilityManager$ConnectivityBroadcastReceiver@a5f69ba that was originally registered here. Are you missing a call to unregisterReceiver()?

### ISSUE THREAD

**Issue by rizwanbpatel** [couchbase/couchbase-lite-android#1367] opened 2017-08-26 15:54 UTC
Similar Issues reported earlier:
 
https://github.com/couchbase/couchbase-lite-android/issues/511
https://github.com/couchbase/couchbase-lite-android/issues/313

**Version:**
1. Android API 23 
2. Couchbase Lite : com.couchbase.lite:couchbase-lite-android:1.4.0
3. Couchbase Sync Gateway :  1.4
4. Couchbase Server : 4.6.0-3453 Enterprise Edition (build-3453)

**App Components Design**
1. Main Activity
2. Fragment {Customer List}
3. DatabaseManager <- Provide point of interaction to the all parties interested from the application. Only one instance is available across.
4. Push/Pull replication are started as part of the instance creation of database manager.

**Steps To Reproduce**
1. Run the Android app on emulator.
2. Fetch the documents
2.1: Check if the shared db manager available if yes, use it otherwise create new with the replication.
2.2: Documents get fetched correctly.
3. OnClick handling of the fetched document for drill-down screen components
3.1 : Explicitly created a RunTime exception to trigger that would indeed crash the activity/app. (This step has been done to reproduce the subjected issue.)
3.2: App crashed with the stack trace at the back end:

**StackTrace**

```
08-26 20:40:51.946 19549-19549/com.rp.cust E/ActivityThread: Activity com.rp.cust.MainActivity has leaked IntentReceiver com.couchbase.lite.android.AndroidNetworkReachabilityManager$ConnectivityBroadcastReceiver@a5f69ba that was originally registered here. Are you missing a call to unregisterReceiver()?
android.app.IntentReceiverLeaked: Activity com.rp.cust.MainActivity has leaked IntentReceiver com.couchbase.lite.android.AndroidNetworkReachabilityManager$ConnectivityBroadcastReceiver@a5f69ba that was originally registered here. Are you missing a call to unregisterReceiver()?
    at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:918)
    at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:719)
    at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1172)
    at android.app.ContextImpl.registerReceiver(ContextImpl.java:1152)
    at android.app.ContextImpl.registerReceiver(ContextImpl.java:1146)
    at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:554)
    at com.couchbase.lite.android.AndroidNetworkReachabilityManager.startListening(AndroidNetworkReachabilityManager.java:43)
    at com.couchbase.lite.NetworkReachabilityManager.addNetworkReachabilityListener(NetworkReachabilityManager.java:37)
    at com.couchbase.lite.replicator.ReplicationInternal.startNetworkReachabilityManager(ReplicationInternal.java:366)
    at com.couchbase.lite.replicator.ReplicationInternal.start(ReplicationInternal.java:289)
    at com.couchbase.lite.replicator.PusherInternal.start(PusherInternal.java:121)
    at com.couchbase.lite.replicator.ReplicationInternal$14.doIt(ReplicationInternal.java:1355)
    at com.couchbase.lite.replicator.ReplicationInternal$14.doIt(ReplicationInternal.java:1349)
    at com.github.oxo42.stateless4j.StateConfiguration$3.doIt(StateConfiguration.java:135)
    at com.github.oxo42.stateless4j.StateConfiguration$3.doIt(StateConfiguration.java:133)
    at com.github.oxo42.stateless4j.StateRepresentation.executeEntryActions(StateRepresentation.java:118)
    at com.github.oxo42.stateless4j.StateRepresentation.enter(StateRepresentation.java:97)
    at com.github.oxo42.stateless4j.StateMachine.publicFire(StateMachine.java:199)
    at com.github.oxo42.stateless4j.StateMachine.fire(StateMachine.java:126)
    at com.couchbase.lite.replicator.ReplicationInternal$1.run(ReplicationInternal.java:240)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
```

**Comment by hideki** [comment] 2017-09-27 23:02
Hi @rizwanbpatel,

The exception, `android.app.IntentReceiverLeaked`, is caused by forgetting to call [`unregisterReceiver `](https://developer.android.com/reference/android/content/Context.html#unregisterReceiver(android.content.BroadcastReceiver)). The `unregisterReceiver` is called when the Replicator stopped, or `Manager.close()` is called.

I don't know your application architecture. Also, I cannot guess how the crashed app (step3) can reach step 4 (this exception). Because of RuntimeException at Step 3, the application missed the chance to stop the replicator, then at Step 4, it seems the application starts new Replicator which tries to register same `BroadcastReceiver` instance again.

To avoid this exception, I recommend to catch the `RuntimeException` and call `Manager.close()` method to unregister the BroadcastReciever. As `Manager.close()` closes the associated Database instances. So, if the application can keep running, the application needs to reopen the databases.

**Comment by hideki** [comment] 2017-09-27 23:06
As the scenario that causes `IntentReceiverLeaked ` exception cannot be avoided by the CBL, so this scenario should be taken cared by the application level. I will close this ticket. If this issue is caused by CBL, please reopen this ticket.

**Closed by hideki** 2017-09-27 23:06 UTC
Labels: review

**Comment by hideki** [comment] 2017-09-27 23:14
Hi @rizwanbpatel,
I am wondering if `IntentReceiverLeaked ` is caused by using Activity to instantiate https://github.com/couchbase/couchbase-lite-android/blob/master/src/main/java/com/couchbase/lite/android/AndroidContext.java#L30 .
Can you try to obtain Context by [`Context. getApplicationContext()`](https://developer.android.com/reference/android/content/Context.html#getApplicationContext()) instead of `Activity`?
