### ISSUE TITLE
Subsequent ResultSet from Query.run() returns different non-deleted copy of document just previously deleted via Database.delete(document)

### ISSUE THREAD

**Issue by ascendancy05** [couchbase/couchbase-lite-android#1385] opened 2017-09-06 20:53 UTC
couchbase-lite-android 2.0.0-DB016

In our app, we call ```Database.delete(document)``` to delete a document that is amongst a list of other documents meeting certain query criteria, and the deletion succeeds without error. Checking ```document.isDeleted()``` returns ```true``` immediately after.  

After this, we do a search on the same ```Database``` via ```Query.run()``` and get back a list of objects. The object we expect to be deleted not only comes in this ```ResultSet``` but when you call ```isDeleted()``` on the document it now returns ```false```. Also the ```id``` of the document is different.

Possible steps to reproduce:
Start by adding a bunch of documents of a certain type
Delete some of those documents
Search for documents of the same type
Search returns some/all of the deleted documents

**Comment by ascendancy05** [comment] 2017-09-07 14:31
Also to add some more context: doing insertions also seems to have a similar affect where the first document of a certain type that is inserted does not get returned in the search done immediately after saving that document, and after re-adding again it does show up in the search results but with a different document id than the first one

**Comment by ascendancy05** [comment] 2017-09-07 18:28
Ok some more information: we were able to identify an inconsistency in the behavior of ```ResultSet```, where doing ```ResultSet.next()``` would sometimes return ```null``` even when there were still supposed to be more results than it claimed. Whereas using the ```iterator()``` on ```ResultSet``` and doing ```iterator.next()``` returns all the values as expected.

So I would spend time comparing the behavior of ```ResultSet.next()``` and ```ResultSet.iterator().next()``` as the first of these seems to have a bug

**Comment by hideki** [comment] 2017-09-07 18:30
Hi @ascendancy05,
Thank you very much for your inputs!
Don't you mind to write code snippet to reproduce the problem?
Thanks a lot!
Hideki

**Comment by ascendancy05** [comment] 2017-09-07 18:34
I've been trying to; I grabbed the sample TODO List project for DB16 and hacked some stuff in there but was unable to reproduce.

**Comment by ascendancy05** [comment] 2017-09-07 18:40
```
+    public Result next() {
+        try {
+            if (c4enum.next()) {
+                if (c4enum.getFullTextTermCount() > 0)
+                    return new FullTextResult(this, c4enum);
+                else
+                    return new Result(this, c4enum);
+            } else
+                return null;
+        } catch (LiteCoreException e) {
+            Log.w(TAG, "Query enumeration error: %s", e);
+            return null;
+        }
+
+    }
+
+    Result get(int index) {
+        try {
+            if (c4enum.seek(index)) {
+                if (c4enum.getFullTextTermCount() > 0)
+                    return new FullTextResult(this, c4enum);
+                else
+                    return new Result(this, c4enum);
+            } else
+                return null;
+        } catch (LiteCoreException e) {
+            throw LiteCoreBridge.convertRuntimeException(e);
+        }
+    }
```

So comparing those two functions from ```ResultSet.java``` in ```com.couchbase.lite``` it seems that ```c4enum.next()``` is returning a ```null``` for whatever reason, but if you use the iterator ```c4enum.seek(index)``` works. So looks like if there is indeed a bug here which it certainly feels like its in the C++ code

**Comment by hideki** [comment] 2017-09-07 20:58
Hi @ascendancy05,

I wrote a simple unit test that tests the query with the deleted document. However, I can not reproduce the problem. Can you review the following unit test codes?

```java
    @Test
    public void testQueryDeletedDocument() throws CouchbaseLiteException {

        // Insert two documents
        Document task1 = createTaskDocument("Task 1");
        Document task2 = createTaskDocument("Task 1");
        assertEquals(2, db.getCount());

        // query documents
        Query q = Query.select(expression(meta().getId()), all()).from(database(this.db)).where(property("type").equalTo("task"));
        ResultSet rs = q.run();
        Result r;

        // ResultSet.next()
        int counter = 0;
        while ((r = rs.next()) != null) {
            Log.i(TAG, "Round 1: [next] Result -> " + r.toMap());
            counter++;
        }
        assertEquals(2, counter);

        // Iterator
        counter = 0;
        for (Result result : rs) {
            Log.i(TAG, "Round 1: [Iterator] Result -> " + result.toMap());
            counter++;
        }
        assertEquals(2, counter);

        // delete task 1
        assertFalse(task1.isDeleted());
        db.delete(task1);
        assertEquals(1, db.getCount());
        assertTrue(task1.isDeleted());

        // query documents again
        rs = q.run();
        // ResultSet.next()
        counter = 0;
        while ((r = rs.next()) != null) {
            assertEquals(task2.getId(), r.getString(0));
            Log.i(TAG, "Round 2: [next()] Result -> " + r.toMap());
            counter++;
        }
        assertEquals(1, counter);

        // Iterator
        counter = 0;
        for (Result result : rs) {
            assertEquals(task2.getId(), result.getString(0));
            Log.i(TAG, "Round 2: [Iterator] Result -> " + result.toMap());
            counter++;
        }
        assertEquals(1, counter);
    }

    private Document createTaskDocument(String title) throws CouchbaseLiteException {
        Document doc = createDocument();
        doc.setString("type", "task");
        doc.setString("title", title);
        doc.setBoolean("complete", false);
        return save(doc);
    }
```

**Comment by hideki** [comment] 2017-09-18 21:59
As we don't have additional information about this ticket, I will close this for now. If the issue is still reproducible, please reopen the ticket.

**Closed by hideki** 2017-09-18 21:59 UTC
Labels: ready, reproduce/investigate

**Comment by ascendancy05** [comment] 2017-09-18 22:26
This is ok by me. We were able to find a workaround using the iterator as mentioned earlier and was unable to reproduce using the sample app
