### ISSUE TITLE
Pull-replicated attachments secretly gzipped without API support? (CouchDB)

### ISSUE THREAD

**Issue by hinesmr** [couchbase/couchbase-lite-android#327] opened 2014-06-08 09:34 UTC
There are two nasty bugs so far (as of the Jenkins verison 396):

1. The API call revision.getAttachment(filename).getGZipped() returns false when actually the document is compressed! Yikes =(
2. Content-type sent to the browser using a Listener says ("text/plain"), when in reality the content is gzipped! Ouch! =(

Steps to reproduce:

1. Start a pull-replication from a couchdb server with some attachments.
2. Try to retrieve the attachments via either the API or the Listener and you'll get a compressed attachment with no indication that it was actually compresed via getGZipped() or content-type.

**Comment by hideki** [comment] 2015-02-17 05:35
It seems that the problem is CouchDB treats an image file as "text/plain". Then CBL Android confuses its file type.

CoudDB Admin UI
![screen shot 2015-02-16 at 9 32 47 pm](https://cloud.githubusercontent.com/assets/15889/6223648/66159656-b623-11e4-88a7-fbcded46430a.png)

CBL Android
```
{_id=foo, _rev=1-db390ccdfba12742ab6d99dbdf6e43b5, _attachments={attach={length=162218, digest=sha1-nZtDqqjGIUqQP1RDqG/kl2RJnag=, revpos=1, content_type=text/plain, stub=true}}}  
```

**Comment by hideki** [comment] 2015-02-17 05:50
In the comment of https://github.com/couchbase/couchbase-lite-android/issues/327#issuecomment-45754346, the customer specified "text/plain" as mime-type even though the attachment is jpg file. It makes CBL Android to be confused.
```
db["foo"] = { '_attachments' : { 'attach' : { 'content_type' : 'text/plain', "data" : str(pic) } } }
```

By specifying 'image/jpeg', CBL Android can replicate the image attachment correctly and store it in the database.
```
db["foo"] = { '_attachments' : { 'attach' : { 'content_type' : 'image/jpeg', "data" : str(pic) } } }
```

**Comment by hideki** [comment] 2015-02-17 06:04
I posted sample app I wrote for this. https://github.com/hideki/couchbase-lite/tree/master/test/AttachmentWithCouchDB

As we could not reproduce this issue by specifying "image/jpeg", I will close this ticket. If this is still reproducible, please reopen this.

**Comment by hinesmr** [comment] 2015-02-18 01:17
Why does the compression of the attachment depend on its content type at all?

What if my attachment was a binary program? What would CBL do then?

**Comment by hideki** [comment] 2015-02-18 01:29
Hi @hinesmr,

Compression and Mime-Type are independent. We added gzip support into CBL Android/Java a month ago, that changes could handle gzipped data correctly from CouchDB.

> What if my attachment was a binary program? What would CBL do then?

I believe you need to specify "application/octet-stream" as MIME-TYPE. http://en.wikipedia.org/wiki/Internet_media_type

To display image file which is stored as attachment on Android, I needed to set appropriate MIME-TYPE.

If you still have this test environment, could you please try with CBL Android from master branch?

**Comment by hinesmr** [comment] 2015-02-18 01:45
Oh----- added a month ago. That's great. I don't have the test environment right now in front of me ----- can I wait for the community release in the future so I can test with my app?

**Comment by hideki** [comment] 2015-02-18 01:52
@hinesmr Thank you very much for all your helps. Please let us know if this issue is still reproducible with latest CBL Android.

**Comment by snej** [comment] 2015-02-18 02:05
IIRC, CouchDB will automatically gzip an uploaded attachment if its type is declared as matching text/*.

The replicator just preserves the encoding of attachments it copies.if the original attachment was gzipped, the replicated copy will be too.

**Comment by hideki** [comment] 2015-02-18 02:14
@senj Thank you for your inputs. I will test with plain text file to put on CouchDB with "text/plain" as mime-type. After replicated from CouchDB to CBL, Should the ungzipped attachment be stored in CBL storage? Or gzipped one should be stored in CBL storage?

**Comment by snej** [comment] 2015-02-18 04:10
It should have the same encoding it does in CouchDB.

**Comment by hideki** [comment] 2015-02-18 04:31
@snej Thank you for your confirmation.

**Comment by hideki** [comment] 2015-02-19 02:06
I tested the pull replication with image attachment which is specified "text/plain" as attachment MIME-TYPE for CouchDB. The attachment should be gzipped in CouchDB.

At CBL Android side, the attachment is stored as it is after docs are replicated. With following codes, the image attachment can be successfully retrieved from CBL db.

```
        Document d = pullDB.getDocument("foo");
        Log.e(TAG, "" + d.getProperties());
        Revision rev = d.getCurrentRevision();
        Attachment att = rev.getAttachment("attach");
        if (att != null) {
            InputStream is = null;
            try {
                // Unzip
                is = new GZIPInputStream(att.getContent());
            } catch (CouchbaseLiteException e1) {
                e1.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            }
            Drawable drawable = Drawable.createFromStream(is, "src name");
            ImageView imageView = (ImageView)findViewById(R.id.imageView);
            imageView.setImageDrawable(drawable);
        }
```
Sample app codes is [here](https://github.com/hideki/couchbase-lite/blob/master/test/AttachmentWithCouchDB/app/src/main/java/self/hideki/attachmentwithcouchdb/MainActivity.java#L185-L207)

As CBL Android with master branch works as expected, so I will close this ticket again. Please reopen this if the issue is still reproducible with latest CBL Android build.

**Closed by hideki** 2015-02-19 02:06 UTC
Labels: parity, S3: major, testneeded, waffle:in progress

**Comment by hinesmr** [comment] 2015-02-19 02:28
Thanks for your patience everyone. (I used to have some code testing for the Gzip "magic" code, but I shouldn't need that anymore in the future, now).
