### ISSUE TITLE
Severe replication slowdown on large datasets

### ISSUE THREAD

**Issue by ascendancy05** [couchbase/couchbase-lite-android#1646] opened 2018-03-08 16:55 UTC
This is on both DB20 with SG 1.5, and DB22 with SG 2.0

We have a large dataset (~100k documents) that we are trying to replicate down in one shot. At the very beginning, we can see >1k documents per second at times being replicated down. However, as the sync continues, replication slows down almost to single digits per second. We also tested this on a larger cluster and experienced the same degree of slowdown (several thousand documents/sec down to <100 documents/sec)

A coworker of mine also experienced this in iOS previously and wrote in some hacks to detect this slowdown and restart replication, which would speed it back up again. This sounds like an issue in lite-core, but I wanted to give this visibility here.

As far as reproducing, the code is pretty much just boilerplate. I would suggest standing up a cluster with >100k documents in it with a few simple indexes and trying to replicate those down

**Comment by hideki** [comment] 2018-03-08 17:49
Hi @ascendancy05, 
Can you share the sample document?

**Comment by ascendancy05** [comment] 2018-03-08 18:45
```
[
  {
    "data": {
      "$hs": {
        "account": "UrbanGourmet",
        "channels": [
          "UrbanGourmet::Manufacturer::f08250d9-8a09-4c41-95c9-f738fe010edc",
          "UrbanGourmet::Manufacturer::*"
        ],
        "create": [
          "UrbanGourmet@ADMIN",
          "UrbanGourmet@REP",
          "UrbanGourmet@DIRECT"
        ],
        "delete": [
          "UrbanGourmet@ADMIN",
          "UrbanGourmet@REP",
          "UrbanGourmet@DIRECT"
        ],
        "type": "UrbanGourmet::Item",
        "update": [
          "UrbanGourmet@ADMIN",
          "UrbanGourmet@REP",
          "UrbanGourmet@DIRECT"
        ]
      },
      "$schema": "",
      "_sync": {
        "cas": "",
        "channels": {
          "UrbanGourmet::Manufacturer::*": null,
          "UrbanGourmet::Manufacturer::f08250d9-8a09-4c41-95c9-f738fe010edc": null
        },
        "history": {
          "channels": [
            [
              "UrbanGourmet::Manufacturer::*",
              "UrbanGourmet::Manufacturer::f08250d9-8a09-4c41-95c9-f738fe010edc"
            ]
          ],
          "parents": [
            -1
          ],
          "revs": [
            "1-e779e30dd18fe142e351c900eb443608"
          ]
        },
        "recent_sequences": [
          478
        ],
        "rev": "1-e779e30dd18fe142e351c900eb443608",
        "sequence": 478,
        "time_saved": "2018-02-21T16:26:31.630712075Z"
      },
      "account": "UrbanGourmet",
      "barcode": null,
      "category": "879c8561-b58c-4aa8-a51e-f6332ddd3869",
      "categoryPosition": 7,
      "conditionalData": {
        
      },
      "ctime": "2017-06-01T18:35:03.832468Z",
      "ctimeOnServer": "2017-06-01T18:35:03.832468Z",
      "entityType": "Item",
      "externalID": null,
      "hasGeneratedSKU": false,
      "isHidden": false,
      "isHiddenForCustomers": false,
      "isImplicitlyHidden": false,
      "isImplicitlyHiddenForCustomers": false,
      "longDesc": "Lush and creamy, with a mild, earthy flavor, eggplant has the most velvety texture in the vegetable family. It's high in healthy fiber. We love it sliced, brushed with olive oil and salt, and grilled or roasted. We also love it breaded, fried, and smothered in fried onions. Come to think of it, we just plain love it.\n\nOrganic, Locally grown in New York State",
      "minQty": 1,
      "mtime": "2018-02-21T16:06:43.413129Z",
      "mtimeOnServer": "2018-02-21T16:06:43.413129Z",
      "multQty": 1,
      "name": "Organic Eggplant",
      "objID": 148,
      "owner": "4b864d77-c3fb-4d15-8eaf-280ffe706c04",
      "pricingUnit": "lb",
      "pricingUnitPerSaleUnit": "25.000000000",
      "saleUnit": "Box",
      "sku": "3445",
      "unitPrice": "1.99"
    }
  }
]
```

**Comment by hideki** [comment] 2018-03-16 00:38
Performance measurement data

Test tool: https://github.com/couchbase/couchbase-lite-android/tree/master/tools/perftest
CBL: 2.0.0-DB023 (Beta 2)
Device: Nexus 6P (Android 8.10 API 27)
Sync Gateway: Mackbook Pro  - walrus mode (in memory) - 2.0.0-821 (beta 2 candidate build)
Network: office Wifi

Number of document: 10K
Document size: See above comment (All 10K doc has same data.)

Push replication 
```
03-15 17:31:25.582  8028  8059 W System.err: Push 100000 documents in 149.600802 sec
03-15 17:31:25.587  8028  8059 W System.err: Push 100000 docs:  Range: 149.601 ... 149.601 sec, Average: 149.601, median: 149.601, std dev:  0.00
03-15 17:31:25.590  8028  8059 W System.err:                     Range:   1.496 ...   1.496 ms/doc, Average:   1.496, median:   1.496, std dev:  0.00
03-15 17:31:25.591  8028  8059 W System.err:                      Rate: 668 docs/sec
```

**Comment by hideki** [comment] 2018-03-16 00:56
Hi @ascendancy05,
I measured push & pull performance with using DB023 (Beta2) and Sync Gateway 2.0.0-821 with 10K document. Each document is same as the document you provided. See details in the previous comment.
To pull replicatew 10K document, it takes around 40 secs. I believe this is reasonable speed. Could you please try DB023. DB023 also requires Sync Gateway Beta2 build.
Thanks!

**Comment by hideki** [comment] 2018-03-16 01:03
## Performance measurement data (DB022 - Beta 1)

### Test condition
Test tool: https://github.com/couchbase/couchbase-lite-android/tree/master/tools/perftest
CBL: 2.0.0-DB022 (Beta 1)
Device: Nexus 6P (Android 8.10 API 27)
Sync Gateway: Mackbook Pro  - walrus mode (in memory) - 2.0.0-773 (beta 1 )
Network: office Wifi
Number of document: **10K**
Document size: **same content with prev comment** (All 10K doc has same data.)

### Push replication 
```

```

### Pull replication
```

```

**Comment by ascendancy05** [comment] 2018-03-16 14:26
Will try and take a look if not today by mid next week and let you know

**Comment by hideki** [comment] 2018-03-16 21:45
Hi @ascendancy05 ,
We have planned to release CBL 2.0.0 near future. If we could not reproduce the problem soon, we need to postpone the bug fix in next release. If you can observe replication slowness with Beta2 build, please let us know soon.
Thanks!

**Comment by ascendancy05** [comment] 2018-03-19 13:40
Hey @hideki , I will focus on trying to get this running today so I can get you some feedback ASAP. Hopefully not too high a level of interrupts today here :)

**Comment by ascendancy05** [comment] 2018-03-20 17:20
So my testing is pretty inconclusive to this point; I am syncing down from an external server and while I can confirm I am not seeing the consistent fast to slow replication anymore as the number of documents synced increases, I am seeing fluctuations in the speed which could perhaps just be network flakiness. At this juncture, I'm willing to close this out for the time being until we can definitively further reproduce this

**Comment by hideki** [comment] 2018-03-20 17:38
Hi @ascendancy05,

Thank you for sharing test result.

According to the Engineer who writes the replication codes, there was a memory leak with Beta 1 (DB022). In the original report, replicating many documents caused replication slowness. I assume memory leak could cause the frequent garbage collection, and it could make the replication/application slowness. We fixed the memory leak with Bata 2 (DB023), the slowness by GC could be solved.

I will close this ticket for now. Please let us know if you can observe the replication slowness again.

Thank you!

**Closed by hideki** 2018-03-20 17:38 UTC
Labels: P2: medium, needsmoreinfo, ready, reproduce/investigate
