### ISSUE TITLE
database.getDocument(docId) returns null

### ISSUE THREAD

**Issue by hex6ng** [couchbase/couchbase-lite-android#480] opened 2014-12-27 02:42 UTC
getDocument method call with a predefined document ID is returning null.

**Comment by tleyden** [comment] 2015-01-09 00:59
Can you provide a code example?

We have an existing unit test that demonstrates this works:

https://github.com/couchbase/couchbase-lite-android/blob/9cee6ad3bbae1cd45c31a759923c8729c1ffc1ef/src/androidTest/java/com/couchbase/lite/DocumentTest.java#L91-L100

I'm going to close this, but if you can demonstrate an issue I will re-open.

**Closed by tleyden** 2015-01-09 00:59 UTC

**Comment by elrondshep** [comment] 2015-06-29 16:33
I'm not sure what I'm doing wrong here, but I'm experiencing the same thing. I was using version 1.0.4 and upgraded to 1.1.0 and it started happening. I downgraded again and it's still happening.

I have a persistenceManager class that handles all the crud operations for couchbase. In my constructor I have this:

    public PersistenceManager() {
        try {
            Manager manager = new Manager(new AndroidContext(mContext), Manager.DEFAULT_OPTIONS);

            // create a name for the database and make sure the name is legal
            if (!Manager.isValidDatabaseName(DATABASE_NAME)) {
                throw new PersistenceException("Database with that name already exists");
            }
            // create a new database
            mDatabase = manager.getDatabase(DATABASE_NAME);
        } catch (CouchbaseLiteException e) {
            // Thrown creating a database if something goes wrong
            throw new PersistenceException("Unable to create a database for injection");
        } catch (IOException e) {
            // Thrown creating a manager if something goes wrong
            throw new PersistenceException("Unable to create a manager for injection");
        }
        load();
    }

The load method is pre-populating some mock data for now, but I'll be using this to setup some required documents with non-mock data in the future and want their id's to be known with specific internal unique ids.

    private void load() {

        Document document = mDatabase.getDocument("all_anime");
        if(document == null) {
            //Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Map com.couchbase.lite.SavedRevision.getProperties()' on a null object reference
            throw new PersistenceException("Unable to create a document with the provided ID");
        } else if(document.getProperty("tabTitle") == null) {
            List<LongList> lists = new ArrayList<>();
            lists.add(new LongList("Popular", "Most Popular", 428));
            lists.add(new LongList("Seasons", "Sorted by Seasons", 8));

            Map<String,Object> newTab = new HashMap<>();
            newTab.put("tabTitle", "All Anime");
            newTab.put(LongListDAOImpl.LISTS, lists);
            try {
                document.putProperties(newTab);
            } catch (CouchbaseLiteException e) {
                Log.e(TAG, "Cannot save document", e);
            }
        }
    }
    
I removed the application from the device and started with a fresh install, thinking maybe it's device specific. Still happens - get's into that first block.
