### ISSUE TITLE
Can't stop replicator properly when try to close a database

### ISSUE THREAD

**Issue by fijemax** [couchbase/couchbase-lite-android#1722] opened 2018-04-18 10:03 UTC
Hello,
I developped an Android application based on couchbase lite 1.5.
I actualy migrate the application on 2.0 version but I have some problems/questions with new `Replicator` class.

My application use several replicators and some times I need to close database. I correctly call stop on all my replicators and wait for `ActivityLevel.STOPPED` on each of them, but only the last replicator instanciated passed to `STOPPED`.
This cause this backtrace when I call `close` method on database : 
```
04-18 12:01:56.270 11570-11585/mapotempo.com.fleet.test W/System.err: CouchbaseLiteException{domain='CouchbaseLite', code=16, msg=Cannot close the database.  Please stop all of the replicators before closing the database.}
04-18 12:01:56.272 11570-11585/mapotempo.com.fleet.test W/System.err:     at com.couchbase.lite.AbstractDatabase.close(AbstractDatabase.java:440)
04-18 12:01:56.272 11570-11585/mapotempo.com.fleet.test W/System.err:     at com.couchbase.lite.Database.close(Database.java:25)
04-18 12:01:56.272 11570-11585/mapotempo.com.fleet.test W/System.err:     at mapotempo.com.fleet.core.DabaseHandler.release(DabaseHandler.java:235)
04-18 12:01:56.273 11570-11585/mapotempo.com.fleet.test W/System.err:     at mapotempo.com.fleet.ExampleInstrumentedTest.useAppContext(ExampleInstrumentedTest.java:100)
04-18 12:01:56.273 11570-11585/mapotempo.com.fleet.test W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-18 12:01:56.274 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
04-18 12:01:56.274 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
04-18 12:01:56.275 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
04-18 12:01:56.275 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
04-18 12:01:56.276 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
04-18 12:01:56.276 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
04-18 12:01:56.277 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
04-18 12:01:56.277 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
04-18 12:01:56.277 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
04-18 12:01:56.278 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
04-18 12:01:56.278 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
04-18 12:01:56.279 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
04-18 12:01:56.279 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
04-18 12:01:56.280 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.runners.Suite.runChild(Suite.java:128)
04-18 12:01:56.281 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.runners.Suite.runChild(Suite.java:27)
04-18 12:01:56.282 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
04-18 12:01:56.283 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
04-18 12:01:56.284 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
04-18 12:01:56.284 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
04-18 12:01:56.285 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
04-18 12:01:56.285 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
04-18 12:01:56.286 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.runners.Suite.runChild(Suite.java:128)
04-18 12:01:56.286 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.runners.Suite.runChild(Suite.java:27)
04-18 12:01:56.286 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
04-18 12:01:56.287 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
04-18 12:01:56.287 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
04-18 12:01:56.288 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
04-18 12:01:56.288 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
04-18 12:01:56.289 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
04-18 12:01:56.289 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
04-18 12:01:56.289 11570-11585/mapotempo.com.fleet.test W/System.err:     at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
04-18 12:01:56.290 11570-11585/mapotempo.com.fleet.test W/System.err:     at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
04-18 12:01:56.290 11570-11585/mapotempo.com.fleet.test W/System.err:     at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:375)
04-18 12:01:56.291 11570-11585/mapotempo.com.fleet.test W/System.err:     at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2075)
```
What is the good way to use `Replicator` class ?

**Comment by hideki** [comment] 2018-04-18 17:12
Hi @fijemax,

Thank you for using CBL 2.0 and filing the ticket.

From the log message, one or more Replicators are still running (ACTIVE state) when DB tried to close it. I believe application waits for all replicators become the STOPPED state. If not, please wait till all replicators are stopped, then close DB.

Another possibility is there is a bug in CBL. Possibly it is an event notification code or a stopping replicator code.

Could you please make sure if an application waits till all replicators are stopped.

Thanks!

**Comment by rajagp** [comment] 2018-04-18 19:18
@hideki  Some additional info from my discussions in the forums - https://forums.couchbase.com/t/replicator-with-couchbase-lite-android-2-0/16570/3

**Comment by HodGreeley** [comment] 2018-04-18 21:40
Added further comment to the forum post.  It looks like if the replication has already stopped before using the recommended way of determining state (with a ReplicationChangeListener), the code using the latch may not see the state change and hang.

**Comment by rajagp** [comment] 2018-04-19 13:08
@HodGreeley  The issue isn't that the latch isn't called (and as a consequence close isn't called). The issue is that the some of the replicators continue to remain in opened state because of which the database close failed.

**Comment by HodGreeley** [comment] 2018-04-19 14:34
@rajagp The original issue reported indicated the replicators remained active, but it wasn't clear how stopping was being handled.  In the follow up, it appears @fijemax reimplemented the code using the latch approach, then reported the latch timed out.  That could happen under the conditions I cited, which means there's no bug confirmed in CBL yet.

I think we need clarification on whether there's a confirmed issue remaining with multiple replicators possibly reporting as stopped when they aren't.  Looks like there was just a follow up post indicating there's still a problem.

@fijemax are you confirming the replications are still active before shutting down?  That would eliminate the potential problem I noticed.

**Comment by rajagp** [comment] 2018-04-19 14:37
@HodGreeley  When latch times out, the database is closed. So that's not the issue.
"Sometimes the timeout exceed and mDatabase.close() is caled during a replicator is running (I tryed with with longer timeout > 1 hour)."

**Comment by fijemax** [comment] 2018-04-19 14:56
I wrote a simple android instrumented test : 
https://github.com/Mapotempo/fleet-android-app/blob/dev-cb-2.0/fleet/src/androidTest/java/mapotempo/com/fleet/DatabaseHandlerInstrumentedTest.java

**Comment by HodGreeley** [comment] 2018-04-19 15:53
@rajagp yeah, ok, I think I wasn't clear on that sentence you quoted, but I see what you mean.

**Comment by rajagp** [comment] 2018-04-19 18:08
@fijemax Can you add some relevant log messages and share the debug output - Please share  it as a gist file instead of embedding it here.

- log the state of the active replicators BEFORE you call stop on it .
- Log the replicator state within change listener - (So we see what happens when you call stop on both of them)
- Please extend the latch time out to several minutes so it does not time out. To see if replicators ever stop
- Log the state of the replicators just before you call close on database

Any exceptions of failures reported ...

**Comment by fijemax** [comment] 2018-04-25 07:57
Did you reproduce the bug ?

**Comment by fijemax** [comment] 2018-05-17 09:13
I renamed this issue correclty

**Comment by fijemax** [comment] 2018-07-04 13:47
Hello
Some news on this issue ?

**Comment by pasin** [comment] 2018-07-10 20:39
@fijemax from the log, one of the replication is still in BUSY state after latch timeout. The log doesn't provide any info about the current activity of the replication. Could you enable Replicator and Network logging domain using Database.setLogLevel(level, domain) and share the log when stopping the replicators?

```
Database.setLogLevel(LogDomain. REPLICATOR, LogLevel.VERBOSE);
Database.setLogLevel(LogDomain.NETWORK, LogLevel.VERBOSE);
```

**Comment by borrrden** [comment] 2018-07-23 23:14
I noticed this in the logs:

```
04-20 16:15:48.368 24566-24587/mapotempo.com.fleet.test E/LiteCore: Assertion failed: !_responseHeaders (/home/couchbase/jenkins/workspace/couchbase-lite-android-edition-build/couchbase-lite-android-ee/libs/couchbase-lite-android/libs/couchbase-lite-core/Replicator/c4Replicator.hh:135, in replicatorGotHTTPResponse)/data/app/mapotempo.com.fleet.test-oaOchi8KVHo-QzJEAuL2nQ==/lib/arm64/libLiteCoreJNI.so non-virtual thunk to C4Replicator::replicatorGotHTTPResponse(litecore::repl::Replicator*, int, fleeceapi::AllocedDict const&)/data/app/mapotempo.com.fleet.test-oaOchi8KVHo-QzJEAuL2nQ==/lib/arm64/libLiteCoreJNI.so litecore::repl::Replicator::_onHTTPResponse(int, fleeceapi::AllocedDict)/data/app/mapotempo.com.fleet.test-oaOchi8KVHo-QzJEAuL2nQ==/lib/arm64/libLiteCoreJNI.so std::__ndk1::__function::__func<std::__ndk1::__bind<void (litecore::repl::Replicator::*&)(int, fleeceapi::AllocedDict), litecore::repl::Replicator*, int&, fleeceapi::AllocedDict&>, std::__ndk1::allocator<std::__ndk1::__bind<void (litecore::repl::Replicator::*&)(int, fleeceapi::AllocedDict), litecore::repl::Replic
04-20 16:15:48.371 24566-24587/mapotempo.com.fleet.test W/LiteCore: Caught exception in Actor: assertion failed
```

It could be relevant.  It looks like one of the replicators is getting a 401 Unauthorized return value as well.

**Comment by borrrden** [comment] 2018-07-24 00:52
I ran the exact test copied and pasted (with some minor adjustments for nonprovided API like FleetException) and it passed.  Does this fail every time, or intermittently?  Also what does the Sync Gateway config look like?  If you could provide a project that reproduces the issue then it would speed up the fix process.

**Comment by fijemax** [comment] 2018-07-24 07:35
Hello,
I ran my test again and I get exactly same problem.

Did you ran test several time ?
Sometime test successful ...

```
mapotempo.com.fleet.api.FleetException: Error during database closing
at mapotempo.com.fleet.core.DatabaseHandler.release(DatabaseHandler.java:180)
at mapotempo.com.fleet.DatabaseHandlerInstrumentedTest.simpleDatabaseHandlerTest(DatabaseHandlerInstrumentedTest.java:110)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:375)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2075)
Caused by: CouchbaseLiteException{domain='CouchbaseLite', code=16, msg=Cannot delete the database.  Please stop all of the replicators before closing the database.}
at com.couchbase.lite.AbstractDatabase.delete(AbstractDatabase.java:476)
at com.couchbase.lite.Database.delete(Database.java:25)
at mapotempo.com.fleet.core.DatabaseHandler.release(DatabaseHandler.java:175)
```

**Comment by fijemax** [comment] 2018-07-24 07:52
Sometime test run ok, I reproduce automaticly several time to reproduce my bug.

**Comment by borrrden** [comment] 2018-07-24 23:42
Running against the (almost) latest commit doesn't result in this happening, however when I checked out the 2.0.2 source it happened on the first try so that suggests to me that this problem has been addressed, and will be fixed in the next release (2.1).  If you are feeling adventurous you might try compiling from source to confirm yourself as well.

**Comment by fijemax** [comment] 2018-07-25 12:38
I don't tried with 2.1 version, if the bug is already fixed in futur release can we close this issue ?

**Comment by pasin** [comment] 2018-07-25 18:23
@fijemax you may try with 2.1.0-162 and see if the issue's still reproducible. We could re-open the issue if the issue still exists. Thanks.

**Closed by pasin** 2018-07-25 18:23 UTC
Labels: P1: high, backlog, needsmoreinfo, reproduce/investigate
