### ISSUE TITLE
Endless loop in pull replication when using builds after 0.0.0-671 and 0.0.0-672

### ISSUE THREAD

**Issue by vbenso** [couchbase/couchbase-lite-android#845] opened 2016-04-16 19:49 UTC
The title is self explanatory,
until 0.0.0-668, replication works fine. 
SyncGateway's version is 
==== Couchbase Sync Gateway/1.2.0(79;9df63a5) ====

**Comment by hideki** [comment] 2016-04-16 22:58
Hi @vbenso,

I tested  using GrocerySync sample app with 0.0.0-672 against `Couchbase Sync Gateway/1.2.0(79;9df63a5)`. However, I could not reproduce the problem.

I observed same problem against CouchDB 1.6.0 during my development. In case of calling POST /{db}/_changes with `since` parameter in JSON body against CouchDB, CouchDB returns changes since 0 always. It caused endless loop. But I have never seen this issue with Sync Gateway.

Could you please provide more information?

Thanks,
Hideki

**Comment by vbenso** [comment] 2016-04-17 14:27
@hideki perhaps this problem only happens for certain kinds of channels, or is related to another more complex structures that aren't present in the GrocerySync sample app.
I've upgraded my SyncGateway to master but it didn't change anything, so I'm attaching some logs to this  reply. Logs from sync_gateway and from logcat, when using 0.0.0-668 (working) and 0.0.0-671 (endless loop), 0.0.0-672 gave me also an endless loop, but I didn't see the need to attach another log.
BTW the application's name is com.precisagro.agcampofree.
[log0.0.0-668.zip](https://github.com/couchbase/couchbase-lite-android/files/222670/log0.0.0-668.zip)
[log0.0.0-671.zip](https://github.com/couchbase/couchbase-lite-android/files/222672/log0.0.0-671.zip)

**Comment by hideki** [comment] 2016-04-18 18:40
Hi @vbenso,

I believe https://github.com/couchbase/couchbase-lite-java-core/commit/c50d4919d9685c8e81383b46c03dad1b1ca37473 introduces this issue. If you can build from source code, you could revert this commit and build the project.

Thanks,
Hideki

**Comment by hideki** [comment] 2016-04-18 18:44
It seems Wrong URL escaping causes the issue
```
2016-04-17T10:16:50.106-03:00 HTTP:  #009: POST /test/_changes?feed=longpoll&heartbeat=300000&style=all_docs&since=3119%3A42&limit=50  (as 247.770.130-49)
```

**Comment by hideki** [comment] 2016-04-18 20:35
Fixed in couchbase-lite-java-core. PR: https://github.com/couchbase/couchbase-lite-java-core/pull/1206

**Comment by vbenso** [comment] 2016-04-18 21:15
@hideki Thanks for the fix. 

I've followed the instructions on compiling couchbase-lite-android but didn't succeed.
I know it's an unrelated issue, but given the fact that I'm posting issues here all the time, maybe by compiling and testing stuff on my machine(Ubuntu 15.04) I can be more helpful:construction_worker: than annoying :loudspeaker: 
```
➜  couchbase-lite-android git:(master) ./gradlew assemble --stacktrace
Parallel execution is an incubating feature.
build 'couchbase-lite-android':compileLint
:libraries:couchbase-lite-java-core:compileJava
:libraries:couchbase-lite-java-forestdb:compileLint
:libraries:couchbase-lite-java-native:sqlite-custom:compileLint
:libraries:couchbase-lite-java-forestdb:copyReleaseLint UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlite-default:compileLint
:libraries:couchbase-lite-java-native:sqlcipher:compileLint
:libraries:couchbase-lite-java-forestdb:mergeReleaseProguardFiles
:copyDebugLint
:libraries:couchbase-lite-java-forestdb:mergeReleaseProguardFiles UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlite-custom:copyReleaseLint UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlite-default:copyReleaseLint UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlcipher:copyReleaseLint
:mergeDebugProguardFiles UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlite-custom:mergeReleaseProguardFiles UP-TO-DATE
:libraries:couchbase-lite-java-forestdb:generateForestDBStoreJniHeaders UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlcipher:mergeReleaseProguardFiles
:libraries:couchbase-lite-java-native:sqlite-custom:preBuild UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlcipher:mergeReleaseProguardFiles UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlite-default:mergeReleaseProguardFiles UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlite-default:preBuild UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlite-default:preReleaseBuild UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlite-default:checkReleaseManifest
:libraries:couchbase-lite-java-native:sqlite-default:prepareReleaseDependencies UP-TO-DATE
:preBuild
:libraries:couchbase-lite-java-native:sqlite-custom:preReleaseBuild UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlcipher:preBuild UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlite-default:compileReleaseAidl UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlite-custom:checkReleaseManifest
:preDebugBuild UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlcipher:preReleaseBuild
:libraries:couchbase-lite-java-native:sqlite-custom:prepareReleaseDependencies UP-TO-DATE
:checkDebugManifest
:libraries:couchbase-lite-java-native:sqlite-custom:compileReleaseAidl
:libraries:couchbase-lite-java-native:sqlcipher:checkReleaseManifest
:preDebugAndroidTestBuild UP-TO-DATE
:preDebugUnitTestBuild UP-TO-DATE
:preReleaseBuild
:libraries:couchbase-lite-java-native:sqlcipher:prepareReleaseDependencies UP-TO-DATE
:preReleaseUnitTestBuild UP-TO-DATE
:generateDebugBuildConfig
:libraries:couchbase-lite-java-native:sqlcipher:compileReleaseAidl UP-TO-DATE
:generateDebugBuildConfig UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlite-custom:compileReleaseAidl UP-TO-DATE
:generateDebugAssets
:libraries:couchbase-lite-java-native:sqlite-custom:compileReleaseRenderscript UP-TO-DATE
:generateDebugResValues
:libraries:couchbase-lite-java-native:sqlcipher:compileReleaseRenderscript
:libraries:couchbase-lite-java-native:sqlite-default:compileReleaseRenderscript UP-TO-DATE
:processDebugJavaRes UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlcipher:compileReleaseRenderscript UP-TO-DATE
:compileDebugNdk UP-TO-DATE
:packageDebugJniLibs UP-TO-DATE
:generateDebugResValues UP-TO-DATE
:packageDebugRenderscript UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlite-custom:generateReleaseBuildConfig
:libraries:couchbase-lite-java-native:sqlite-default:generateReleaseBuildConfig UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlite-custom:generateReleaseBuildConfig UP-TO-DATE
:preBuild UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlcipher:compileLint UP-TO-DATE
:copyReleaseLint UP-TO-DATE
:mergeReleaseProguardFiles UP-TO-DATE
:checkReleaseManifest
:generateReleaseBuildConfig UP-TO-DATE
:generateReleaseAssets UP-TO-DATE
:generateReleaseResValues UP-TO-DATE
:processReleaseJavaRes UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlcipher:generateReleaseBuildConfig
:libraries:couchbase-lite-java-native:sqlite-custom:generateReleaseAssets UP-TO-DATE
:compileReleaseNdk
:libraries:couchbase-lite-java-native:sqlite-default:generateReleaseAssets UP-TO-DATE
:compileReleaseNdk UP-TO-DATE
:libraries:couchbase-lite-java-core:processResources
:libraries:couchbase-lite-java-native:sqlite-custom:mergeReleaseAssets UP-TO-DATE
:libraries:couchbase-lite-java-core:processResources UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlcipher:generateReleaseBuildConfig UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlite-default:mergeReleaseAssets UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlcipher:generateReleaseAssets UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlcipher:mergeReleaseAssets UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlcipher:generateReleaseResValues UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlcipher:generateReleaseResources UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlcipher:packageReleaseResources
:libraries:couchbase-lite-java-native:sqlite-custom:generateReleaseResValues
:libraries:couchbase-lite-java-core:classes UP-TO-DATE
:libraries:couchbase-lite-java-core:jar UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlcipher:processReleaseManifest UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlcipher:processReleaseResources UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlite-custom:generateReleaseResources UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlite-custom:packageReleaseResources UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlite-custom:generateReleaseResValues UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlite-custom:processReleaseManifest
:libraries:couchbase-lite-java-native:sqlite-default:generateReleaseResValues
:packageReleaseJniLibs UP-TO-DATE
:libraries:couchbase-lite-java-core:sourcesJar
:libraries:couchbase-lite-java-native:sqlite-custom:processReleaseResources UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlite-custom:generateReleaseSources UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlite-custom:ndkBuild UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlcipher:generateReleaseSources UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlcipher:ndkBuild UP-TO-DATE
:libraries:couchbase-lite-java-core:sourcesJar UP-TO-DATE
:packageReleaseRenderscript UP-TO-DATE
:sourcesJar UP-TO-DATE
:libraries:couchbase-lite-java-core:assemble UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlite-default:generateReleaseResValues UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlite-default:generateReleaseResources UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlite-default:packageReleaseResources UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlite-default:processReleaseManifest UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlite-default:processReleaseResources UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlite-default:generateReleaseSources UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlite-default:ndkBuild
make: Entering directory '/home/victor/Documents/software/couchbase-lite-android/libraries/couchbase-lite-java-native/sqlite-custom/src/main'
make: Entering directory '/home/victor/Documents/software/couchbase-lite-android/libraries/couchbase-lite-java-native/sqlcipher/src/main'
make: Entering directory '/home/victor/Documents/software/couchbase-lite-android/libraries/couchbase-lite-java-native/sqlite-default/src/main'
[arm64-v8a] Install        : libcbljavasqlitecustom.so => libs/arm64-v8a/libcbljavasqlitecustom.so
[arm64-v8a] Install        : libcbljavasqlitedefault.so => libs/arm64-v8a/libcbljavasqlitedefault.so
[arm64-v8a] Install        : libcbljavakey.so => libs/arm64-v8a/libcbljavakey.so
[arm64-v8a] Install        : libcbljavasqlcipher.so => libs/arm64-v8a/libcbljavasqlcipher.so
[arm64-v8a] Install        : libsqlite.so => libs/arm64-v8a/libsqlite.so
[x86_64] Install        : libcbljavasqlitedefault.so => libs/x86_64/libcbljavasqlitedefault.so
[arm64-v8a] Install        : libsqlcipher.so => libs/arm64-v8a/libsqlcipher.so
[x86_64] Install        : libcbljavakey.so => libs/x86_64/libcbljavakey.so
[arm64-v8a] Install        : libsqlite3.so => libs/arm64-v8a/libsqlite3.so
[x86_64] Install        : libcbljavasqlitecustom.so => libs/x86_64/libcbljavasqlitecustom.so
[x86_64] Install        : libcbljavasqlcipher.so => libs/x86_64/libcbljavasqlcipher.so
[x86_64] Install        : libsqlite.so => libs/x86_64/libsqlite.so
[mips64] Install        : libcbljavasqlitedefault.so => libs/mips64/libcbljavasqlitedefault.so
[x86_64] Install        : libsqlite3.so => libs/x86_64/libsqlite3.so
[mips64] Install        : libcbljavasqlitecustom.so => libs/mips64/libcbljavasqlitecustom.so
[x86_64] Install        : libsqlcipher.so => libs/x86_64/libsqlcipher.so
[mips64] Install        : libcbljavakey.so => libs/mips64/libcbljavakey.so
:libraries:couchbase-lite-java-forestdb:generateCBForestJniHeaders
[mips64] Install        : libcbljavasqlcipher.so => libs/mips64/libcbljavasqlcipher.so
[mips64] Install        : libsqlite.so => libs/mips64/libsqlite.so
[armeabi-v7a] Install        : libcbljavasqlitedefault.so => libs/armeabi-v7a/libcbljavasqlitedefault.so
[mips64] Install        : libsqlite3.so => libs/mips64/libsqlite3.so
Error: Could not find class file for 'com.couchbase.cbforest.Database'.
Error: Could not find class file for 'com.couchbase.cbforest.Document'.
Error: Could not find class file for 'com.couchbase.cbforest.DocumentIterator'.
Error: Could not find class file for 'com.couchbase.cbforest.ForestException'.
Error: Could not find class file for 'com.couchbase.cbforest.FullTextResult'.
Error: Could not find class file for 'com.couchbase.cbforest.Indexer'.
Error: Could not find class file for 'com.couchbase.cbforest.Logger'.
Error: Could not find class file for 'com.couchbase.cbforest.QueryIterator'.
Error: Could not find class file for 'com.couchbase.cbforest.View'.
:libraries:couchbase-lite-java-forestdb:generateCBForestJniHeaders FAILED
[armeabi-v7a] Install        : libsqlite.so => libs/armeabi-v7a/libsqlite.so
[armeabi] Install        : libcbljavasqlitedefault.so => libs/armeabi/libcbljavasqlitedefault.so
[armeabi-v7a] Install        : libcbljavasqlitecustom.so => libs/armeabi-v7a/libcbljavasqlitecustom.so
[armeabi-v7a] Install        : libsqlite3.so => libs/armeabi-v7a/libsqlite3.so
[armeabi] Install        : libcbljavasqlitecustom.so => libs/armeabi/libcbljavasqlitecustom.so
[armeabi] Install        : libsqlite3.so => libs/armeabi/libsqlite3.so
[x86] Install        : libcbljavasqlitecustom.so => libs/x86/libcbljavasqlitecustom.so
[armeabi] Install        : libsqlite.so => libs/armeabi/libsqlite.so
[x86] Install        : libcbljavasqlitedefault.so => libs/x86/libcbljavasqlitedefault.so
[mips64] Install        : libsqlcipher.so => libs/mips64/libsqlcipher.so
[x86] Install        : libsqlite3.so => libs/x86/libsqlite3.so
[armeabi-v7a] Install        : libcbljavakey.so => libs/armeabi-v7a/libcbljavakey.so
[mips] Install        : libcbljavasqlitecustom.so => libs/mips/libcbljavasqlitecustom.so
[armeabi-v7a] Install        : libcbljavasqlcipher.so => libs/armeabi-v7a/libcbljavasqlcipher.so
[x86] Install        : libsqlite.so => libs/x86/libsqlite.so
[mips] Install        : libcbljavasqlitedefault.so => libs/mips/libcbljavasqlitedefault.so
[armeabi-v7a] Install        : libsqlcipher.so => libs/armeabi-v7a/libsqlcipher.so
[armeabi] Install        : libcbljavakey.so => libs/armeabi/libcbljavakey.so
[mips] Install        : libsqlite3.so => libs/mips/libsqlite3.so
[mips] Install        : libsqlite.so => libs/mips/libsqlite.so
make: Leaving directory '/home/victor/Documents/software/couchbase-lite-android/libraries/couchbase-lite-java-native/sqlite-default/src/main'
make: Leaving directory '/home/victor/Documents/software/couchbase-lite-android/libraries/couchbase-lite-java-native/sqlite-custom/src/main'
[armeabi] Install        : libcbljavasqlcipher.so => libs/armeabi/libcbljavasqlcipher.so
[armeabi] Install        : libsqlcipher.so => libs/armeabi/libsqlcipher.so
[x86] Install        : libcbljavakey.so => libs/x86/libcbljavakey.so
[x86] Install        : libcbljavasqlcipher.so => libs/x86/libcbljavasqlcipher.so
[x86] Install        : libsqlcipher.so => libs/x86/libsqlcipher.so
[mips] Install        : libcbljavakey.so => libs/mips/libcbljavakey.so
[mips] Install        : libcbljavasqlcipher.so => libs/mips/libcbljavasqlcipher.so
[mips] Install        : libsqlcipher.so => libs/mips/libsqlcipher.so
make: Leaving directory '/home/victor/Documents/software/couchbase-lite-android/libraries/couchbase-lite-java-native/sqlcipher/src/main'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':libraries:couchbase-lite-java-forestdb:generateCBForestJniHeaders'.
> Process 'command 'javah'' finished with non-zero exit value 1

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':libraries:couchbase-lite-java-forestdb:generateCBForestJniHeaders'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:310)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.process.internal.ExecException: Process 'command 'javah'' finished with non-zero exit value 1
	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:365)
	at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:31)
	at org.gradle.api.tasks.AbstractExecTask.exec(AbstractExecTask.java:54)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:589)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:572)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 14 more


BUILD FAILED

Total time: 11.1 secs
```

**Comment by hideki** [comment] 2016-04-18 22:33
Hi @vbenso

I think some files are missing. You might forget to execute `git submodule update --init --recursive`. 

Add Couchbase Lite to your project as a submodule
https://github.com/couchbase/couchbase-lite-android/wiki/Add-Couchbase-Lite-to-your-project-as-a-submodule

Thanks!

**Closed** 2016-04-19 01:25 UTC
Labels: bug, needsmoreinfo, P1: high, review

**Comment by hideki** [comment] 2016-04-19 17:11
Hi @vbenso,
If you have time, could you please verify the fix with using 0.0.0-673?
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/0.0.0-673/
Thanks!
Hideki

**Comment by vbenso** [comment] 2016-04-19 22:04
Hi @hideki,
Tested against the couchbase-lite-java-core that I've managed to checkout yesterday(1fd6306) and it did work as expected. :+1: 
Just tested 0.0.0-673 and the replication behaved as expected. 
Thanks for the fix,
Victor

**Comment by hideki** [comment] 2016-04-19 22:18
@vbenso Thank you for verifying the fix and all your helps!
